[wip] add support for schemas
mikro-orm/mikro-orm pull request #1001
Opened 2020-10-27 15:02 UTC by patricklx

2020-10-28 08:39 UTC, B4nan commented on packages/knex/src/AbstractSqlConnection.ts
> +    this.schema = this.config.get('driverOptions').schema;
just one note, will ignore the rest until you provide some description and tests so i can understand it better...

`driverOptions` is wrong place for this, if we handle something in the ORM, the configuration should be above (probably in `ConnectionOptions` interface). `driverOptions` is for users to be able to override things that the ORM does, that is the only purpose.

2020-10-28 18:07 UTC, B4nan requested changes
thanks! added few suggestions to the code. here are some general remarks:

- the tests are failing with `no schema has been selected to create`
- we dont need all the pg tests twice, so please prune it to minimum that is actually needed to test the feature
- don't forget to add docs :] maybe new page in recipes section about multi tenancy, that would be great. doesn't have to be very verbose, just few notes about the setup with few code snippets

2020-10-28 18:07 UTC, B4nan commented on tests/bootstrap.ts
> +    schema: schema,
```suggestion
    schema,
```

2020-10-28 18:07 UTC, B4nan commented on tests/bootstrap.ts
> +    await connection.execute('SET search_path TO ??', [connection.getSchema()]);
could this happen automatically?

2020-10-28 18:45 UTC, B4nan commented on packages/knex/src/AbstractSqlConnection.ts
> +  * this is required to support schemas for migrations
I'd like to hear more about this, why is it required and how exactly it works? Is it only for migrations? If so, maybe we could do it in the `MigrationRunner` class instead? 

Also that comment belongs to the implementation, its not about the method itself.

2020-10-29 09:13 UTC, patricklx commented on packages/knex/src/AbstractSqlConnection.ts
> +  * this is required to support schemas for migrations
basically this is required so that when generating the migration files it also prefixes the table names with the schema name. this is done by calling `withSchema`. But yes, this is an ugly hack. I would need to replace all `knex.schema.createTable/alterTable` and so on with `knex.schema.withSchema().createTable` in schema generator i think

2020-10-29 09:15 UTC, B4nan commented on packages/knex/src/AbstractSqlConnection.ts
> +  * this is required to support schemas for migrations
sounds like better solution, there are only few of those and all of them in the same file...

2020-11-04 08:27 UTC, B4nan requested changes
> according to postgresql.org/docs/9.3/ddl-schemas.html#DDL-SCHEMAS-PATH
it is best to specify the search path instead of prefixing all identifiers

But then we are talking about postgres only support, but this should work just fine in mysql too (with hard coded schema names), right?

I see you removed the second postgres test file and just used schema in the existing one. i am not sure if that is the way to go, sounds like you are now testing only one edge case - usage with single (non standard) schema name. tests for implicit (public) schema are now gone this way, and you did not even test usage with multiple schemas (which this PR is about, right?)

My point was that you should test the feature you are adding, in the way it is supposed to be used. I'd say we should have a dedicated test file for multi schema support, just like we have for embeddables or composite keys. I'd rather not touch existing tests.

Also please rebase.

What are your plans with this? Want to ship v4.3 later this week finally, so asking if I should wait for this to be ready? But don't want to postpone for longer than few days, there are some bugfixes that need to go out :]

2020-11-04 08:27 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +      ret += `create schema "${this.connection.getSchema()}"`;
why is the semicolon missing? also i believe i already said you should use `platform.quoteIdentified()` here

2020-11-04 08:27 UTC, B4nan commented on packages/postgresql/src/PostgreSqlConnection.ts
> +      await this.execute('set search_path to ??', [this.config.get('schema')]);
is this really enough to run on connection instance? the ORM connection class is singleton, i'd say we need to run this on each knex connection (e.g. for each one in the pool)

2020-11-04 13:36 UTC, patricklx commented on packages/postgresql/src/PostgreSqlConnection.ts
> +      await this.execute('set search_path to ??', [this.config.get('schema')]);
but each orm will receive another connection instance or not?
so, if MikoORM.init() is called and then another time call MikoORM.init() with different schema name, the connection instance for those will be different?

2020-11-04 13:37 UTC, patricklx commented
> > according to postgresql.org/docs/9.3/ddl-schemas.html#DDL-SCHEMAS-PATH
> > it is best to specify the search path instead of prefixing all identifiers
> 
> But then we are talking about postgres only support, but this should work just fine in mysql too (with hard coded schema names), right?
> 
> I see you removed the second postgres test file and just used schema in the existing one. i am not sure if that is the way to go, sounds like you are now testing only one edge case - usage with single (non standard) schema name. tests for implicit (public) schema are now gone this way, and you did not even test usage with multiple schemas (which this PR is about, right?)
> 
> My point was that you should test the feature you are adding, in the way it is supposed to be used. I'd say we should have a dedicated test file for multi schema support, just like we have for embeddables or composite keys. I'd rather not touch existing tests.
> 
> Also please rebase.
> 
> What are your plans with this? Want to ship v4.3 later this week finally, so asking if I should wait for this to be ready? But don't want to postpone for longer than few days, there are some bugfixes that need to go out :]

i'm busy with other things right now... :[
it will not work for mysql since they do not have a similar thing as schemas which allows specific user permissions and so on

2020-11-04 13:41 UTC, B4nan commented
> i'm busy with other things right now... :[

Sure, no probs, just wanted to know if I should wait a bit more. 

> it will not work for mysql since they do not have a similar thing as schemas which allows specific user permissions and so on

In mysql, database is the same as schema (it is actually an alias). Users can have access to multiple databases. I don't see a reason why this could not work with mysql (obviously it won't work via `set search_path`, but it could with prefixed table names). Actually there are tests in mysql that are using multiple schemas already.

2020-11-04 13:49 UTC, B4nan commented on packages/postgresql/src/PostgreSqlConnection.ts
> +      await this.execute('set search_path to ??', [this.config.get('schema')]);
yes, but is that enough? there will be many actual connections, and you are running it only on a single one. 

this looks like correct way to do it:

> Note: Knex's PostgreSQL client allows you to set the initial search path for each connection automatically using an additional option "searchPath" as shown below.

```
var pg = require('knex')({
  client: 'pg',
  connection: process.env.PG_CONNECTION_STRING,
  searchPath: ['knex', 'public'],
});
```

http://knexjs.org/#Installation-client

2021-01-03 22:48 UTC, demsey2 commented
hey @patricklx are you planning to continue with that PR? I need that change too but for MySQL

2021-02-18 10:06 UTC, B4nan commented
There is another PR improving the multi schema support - #1424 - so would be good to collaborate.

2021-11-07 12:07 UTC, B4nan commented
Closing as the PR became stale and most of the changes are implemented in #2296.

2021-11-07 12:07 UTC, closed without merging