feat(config): add support for Typescript config files when running via ts-jest
mikro-orm/mikro-orm pull request #1155
Opened 2020-12-03 10:29 UTC by Ezard

Closes #1151

2020-12-03 10:40 UTC, Ezard commented
Just need to figure out how to test this properly

2020-12-03 11:29 UTC, B4nan requested changes
One missing thing is the jest config inside `package.json` (the way used here in the repository too).

2020-12-03 11:29 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +    return false;
this could be re-written to reduce complexity:

```suggestion
    if (process.argv.length <= 1 || !process.argv[1].includes('jest-worker')) {
        return false;
    }

    const packageConfig = await ConfigurationLoader.getPackageConfig();
    const jestConfig = await Utils.getJestConfig();

    return (packageConfig.jest && Utils.jestConfigUsesTsJest(packageConfig.jest)) || Utils.jestConfigUsesTsJest(jestConfig);
```

even better `(packageConfig.jest && Utils.jestConfigUsesTsJest(packageConfig.jest))` - the first condition should be handled in `jestConfigUsesTsJest` method

2020-12-03 11:29 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +      || (Object.values(jestConfig.transform ?? {}).some(transformer => transformer === 'ts-jest'));
not a big fan of splitting stuff to multiple lines randomly (prettier style, meh). much better to create new local variable (human style, lol):

```suggestion
    const usesJestTransformer = Object.values(jestConfig.transform ?? {}).some(transformer => transformer === 'ts-jest');
    return jestConfig.preset === 'ts-jest' || usesJestTransformer;
```

2020-12-03 13:51 UTC, Ezard commented on packages/core/src/utils/Utils.ts
> +import { ConfigurationLoader } from '@mikro-orm/core';
@B4nan ah thanks - didn't notice the IDE had done that

2020-12-04 14:55 UTC, Ezard commented
Thanks for the fast responses - I'll update the PR this weekend

2020-12-06 21:10 UTC, Ezard commented
> One missing thing is the jest config inside `package.json` (the way used here in the repository too).

This was already handled :)

I've implemented the rest of your suggestions though, so I just need to sort out some tests now

2021-01-14 15:18 UTC, B4nan commented
Do you plan to finish this? Should be enough to cover this via unit tests.

2021-01-14 17:43 UTC, Ezard commented
@B4nan sorry for dragging this out - I do intend to finish it, I've just been super busy
I'm rotating back onto a MikroORM-based project within the next week, so I'll finish it then

2021-01-26 20:52 UTC, Ezard commented
@B4nan I'm attempting to sort out tests; however, the fact that the code is written in Typescript is making it kinda hard 🤦‍♂️ 

For example, I wrote a test to ensure that `ConfigurationLoader.getConfigPaths()` returns the correct values when running via `ts-jest`, but since the tests are running via `ts-node`, that gets picked up instead and makes my test pointless

I traced how you're detecting the presence of `ts-node`, and for me at least it's picked up by `Utils.detectTsNode()` here:
```
  static detectTsNode(): boolean {
    return process.argv[0].endsWith('ts-node')
      || !!process[Symbol.for('ts-node.register.instance')]
      || process.argv.slice(1).some(arg => arg.includes('ts-node'))
      || (require.extensions && !!require.extensions['.ts'])
      || !!new Error().stack!.split('\n').find(line => line.match(/\w\.ts:\d/));  <------
  }
```

Should I just mock the `Error` object so I can manipulate its `stack` field? It seems a bit of a thing to do, so if you have any better suggestions then I'm all ears :)

2021-01-28 09:05 UTC, B4nan requested changes

2021-01-28 09:05 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +  private static async getJestConfig(): Promise<Dictionary> {
it feels more and more weird to even have a method that refers to `jest` (and now we even have 3 of them)... 

this all seems overcomplicated and the bit with jest config even seems wrong to me - why would existance of a config file (or anything inside it) mean we are running via ts-jest? 

there should be just one synchoronous method if something, and it feels like we should just improve the `detectTsNode` method instead of adding new ones - we don't really need to know if the user is running via ts-node or ts-jest, we care about the TS support in general.

2021-01-28 10:36 UTC, Ezard commented on packages/core/src/utils/Utils.ts
> +  private static async getJestConfig(): Promise<Dictionary> {
@B4nan the reason that the config needs to be read is because, without reading them, we're only able to determine if the user is running their code via Jest, and we're not able to tell if that code is JS or TS

Therefore, once we've determined that the user is running their code through Jest, we check the Jest config to see if that config supports TS files

If there's something that I've missed and there's a better way of detecting it, then I'd be more than happy to re-implement it

2021-01-28 10:45 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +  private static async getJestConfig(): Promise<Dictionary> {
My point is that this solution is fragile and makes the ORM dependent on jest somehow (which is indeed wrong). Furthermore you are dealing with some ways jest can be configured, but not all of them (e.g. it can be basically any JSON file as long as you point to it when running jest).

TBH I am yet to understand why do you need this change. I am jest user myself, still idk :] Could you create some repository that demonstrates the need?

Again the whole point of this is to decide whether the app is running with TS support or not. It is not about ts-node, babel, ts-jest, whatever - we don't care how it is done, we care about being able to require TS file in current context. 

Also the `useTsJest` flag in package.json does not make sense to me - those flags from package.json are only for CLI, ts-jest has nothing to do with CLI.

2021-01-28 15:57 UTC, Ezard commented on packages/core/src/utils/Utils.ts
> +  private static async getJestConfig(): Promise<Dictionary> {
@B4nan it was to allow for MikroORM config files to be written in Typescript

Like you said though, people have been doing just fine without support for this, so maybe I'm just an edge-case haha :)

I'll close the PR

2021-01-28 15:58 UTC, closed without merging

2021-01-28 17:27 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +  private static async getJestConfig(): Promise<Dictionary> {
I'd still like too see a repro for this, I am not against dealing with that, but it should be probably an extension to `detectTsNode` method (another heuristic), we might also rename the method to something like `detectTypeScriptSupport` so its more descriptive