feat: add explicit (multi) schema support
mikro-orm/mikro-orm pull request #1424
Opened 2021-02-12 03:35 UTC by Aeolun

Since I need this feature for our own usage, and I've found MikroORM to be a serious improvement over TypeORM. I'll build it regardless, but I hope it would be a good thing to have as part of the core, so I figured it'd be better to coordinate before it's fully done so I can adjust course to match conventions/wishes.

I realize someone else had started work on something like this before, but I couldn't really figure out what was going on in that PR, so I started from scratch.

Please let me know what you think.

2021-02-12 08:51 UTC, B4nan requested changes
Interesting, thanks a lot, gave it a quick look and if you can finalize it, will be happy to merge it. Few general hints:

- we need some documentation, right now this is just code and tests (but as you said, its a WIP, we can deal with that at the end - but a progress status in the PR description would be great to see what you plan and what is done already)
- do you plan to support postgres as well? not sure if things are possible with sqlite (i'd say nope?)
- what about schema diffing?
- the tests look a bit suspicious, e.g. entity generator snapshots are missing postgres entities?
- remove unrelated code style changes (e.g. the very first thing on the diff, I am not interested in wrapping each ternary expression in parens...)

2021-02-12 08:51 UTC, B4nan commented on packages/core/src/decorators/Entity.ts
> +  return function<T>(target: T & Dictionary) {
remove unrelated code style changes

2021-02-12 08:51 UTC, B4nan commented on packages/core/src/decorators/Entity.ts
> +    meta.class = (target as unknown) as Constructor<T>;
remove unrelated code style changes

2021-02-12 08:51 UTC, B4nan commented on packages/core/src/decorators/Entity.ts
> +  database?: string;
this looks like its not used anywhere

2021-02-12 08:51 UTC, B4nan commented on packages/core/src/metadata/EntitySchema.ts
> +  & ({ name: string } | { class: Constructor<T>; name?: string } | { name: string; schema: string })
this looks wrong, I'd say it should be this instead (otherwise you'd not allow using `class` with `schema`)
```suggestion
  & ({ name: string; schema?: string } | { class: Constructor<T>; name?: string; schema?: string })
```

2021-02-12 08:51 UTC, B4nan commented on packages/core/src/platforms/Platform.ts
> +    return true;
sounds like a bad default value to me, I'd rather override where it is actually possible than making all drivers enabled by default.

2021-02-12 08:51 UTC, B4nan commented on packages/core/src/typings.ts
> +  schema: string;
should be optional, or not?

2021-02-12 08:51 UTC, B4nan commented on tests/__snapshots__/SchemaGenerator.test.ts.snap
> +drop table if exists \`:memory:\`.\`mikro_orm_migrations\`;
this is obvious wrong :] i guess sqlite will need special treatment for the in memory db

2021-02-12 08:51 UTC, B4nan commented on tests/__snapshots__/SchemaGenerator.test.ts.snap
> +drop table if exists \`:memory:\`.\`mikro_orm_migrations\`;
same here

2021-02-16 01:30 UTC, Aeolun commented on packages/core/src/decorators/Entity.ts
> +  return function<T>(target: T & Dictionary) {
I think my autoformatter is a bit forward in this regard. I turned it off at some point. I'll look through the changelist to remove the extraneous changes. 

Do you you use a standard that I can set it to so it won't happen in the future?

2021-02-16 01:31 UTC, Aeolun commented on packages/core/src/decorators/Entity.ts
> +  database?: string;
`schema` is currently used, `database` isn't. I was planning to do a similar tableName/collection thing where you can use either, but I didn't know enough about the code yet to be sure I'd add it in the correct place.

2021-02-16 01:33 UTC, Aeolun commented on packages/core/src/metadata/EntitySchema.ts
> +  & ({ name: string } | { class: Constructor<T>; name?: string } | { name: string; schema: string })
Eh? I think I got some TS error somewhere in this regards. Maybe I added it here before I added it to `EntityMetadata<>`.

2021-02-16 01:36 UTC, Aeolun commented on packages/core/src/platforms/Platform.ts
> +    return true;
I thought about the existing drivers and how many of them support multiple schemas (most RDBMS do), then settled on this. No issues flipping it around though.

2021-02-16 01:38 UTC, Aeolun commented on tests/__snapshots__/SchemaGenerator.test.ts.snap
> +drop table if exists \`:memory:\`.\`mikro_orm_migrations\`;
Haha, yeah, I noticed this when I submitted it. Will be fixed in the next push.

2021-02-16 01:39 UTC, Aeolun commented on packages/core/src/typings.ts
> +  schema: string;
Not certain of the top of my head. I'll check.

2021-02-16 01:46 UTC, Aeolun commented
> Interesting, thanks a lot, gave it a quick look and if you can finalize it, will be happy to merge it. Few general hints:
> 
>     * we need some documentation, right now this is just code and tests (but as you said, its a WIP, we can deal with that at the end - but a progress status in the PR description would be great to see what you plan and what is done already)
> 
>     * do you plan to support postgres as well? not sure if things are possible with sqlite (i'd say nope?)
> 
>     * what about schema diffing?
> 
>     * the tests look a bit suspicious, e.g. entity generator snapshots are missing postgres entities?
> 
>     * remove unrelated code style changes (e.g. the very first thing on the diff, I am not interested in wrapping each ternary expression in parens...)

Indeed, it's not nearly done. Things that I can immediately think of that still need to be done:

- Support all currently supported databases (where possible)/features, otherwise gracefully fail. I started with MySQL because that's my use case and easiest to test.
- Write documentation. Better to do after the structure is finalized though.
- Tests for all the databases/scenarios. Might need you help pointing me towards things that need to be tested, as I'm not yet familiar with all possible permutations.

> * the tests look a bit suspicious, e.g. entity generator snapshots are missing postgres entities?

I'll have a look at this. Doesn't look like something I expected to happen.

2021-02-16 01:48 UTC, Aeolun commented
Just FYI, I may not respond to this every day, I get pulled in a bunch of different directions every week.

2021-02-16 08:08 UTC, B4nan requested changes

2021-02-16 08:08 UTC, B4nan commented on packages/migrations/src/Migrator.ts
> +      const tableNameWithSchema = table.schema ? `${table.schema}.${table.name}` : '';
you call this `tableNameWithSchema` but when the schema is not set, it is empty string? :]

2021-02-16 08:08 UTC, B4nan commented on packages/mysql-base/src/MySqlSchemaHelper.ts
> +    return `set names ${charset};\n${this.disableForeignKeysSQL()}\n\n`;
i kinda like this change, but it seems unrelated - i'd prefer to have a separate PR that would introduce this method - as long as the tests are passing, we can merge that right ahead

2021-03-19 03:00 UTC, Aeolun commented
Not dead yet. Just trying to find time to work on it again :)

2021-05-14 01:00 UTC, Aeolun commented on packages/core/src/typings.ts
> +  schema: string;
Yeah, point. I misunderstood what EntityProperty was.

2021-05-14 07:14 UTC, B4nan commented
Just a small heads up - if you want to see this being merged at some point, get rid of the unrelated changes, remove the NPM lock files (this project uses yarn, and I don't see why you should do any changes to its dependencies anyway), and rebase with master (as there is already some basic support for schemas in schema generator). I'd suggest to do it rather sooner than later, especially the rebase (you should rebase it regularly, otherwise it will get harder and harder).

2021-05-15 06:33 UTC, Aeolun commented
@B4nan Yeah, I merged with master again already.  A lot of the changes were implemented in a more or less compatible way, so it was much less work than I expected.

I’ll clean up the whole thing afterwards (and pull out the unrelated changes you mentioned before), it’s still strictly WIP. I just didn’t want the changes to be only on my machine so I pushed it up. 

On the plus side, it seems like everything related to entity generation works fine for postgres, mariadb and sqlite, now just need to check mongo.

2021-06-13 15:59 UTC, Aeolun commented
It's alive! Need to add a little bit more testing, and update the docs (mainly around entitygenerator), but it seems it's now doing what I expect in postgres, mysql and sqlite (where it's expected it does nothing).

2021-08-25 07:21 UTC, B4nan reviewed
do you still plan to finalize this? would be great to have it in v5

added few issues i spotted when peeking at the code that would be better resoved before actual review. also rebase is needed.

2021-08-25 08:03 UTC, Aeolun commented
@B4nan Yeah, it’s still on my todo list. Can hopefully finish all the outstanding issues the next time I work on it.

On Wed, Aug 25, 2021, at 4:21 PM, Martin Adámek wrote:
> 
> 
> ***@***.**** commented on this pull request.
> 
> do you still plan to finalize this? would be great to have it in v5
> 
> added few issues i spotted when peeking at the code that would be better resoved before actual review. also rebase is needed.
> 
> 
> In packages/knex/src/schema/SchemaGenerator.ts <https://github.com/mikro-orm/mikro-orm/pull/1424#discussion_r654796596>:
> 
> > +    } else {
> +      await this.dropSchemas();
> +    }
> +    return;
> +  }
> +
> +  private async dropDatabases() {
> +    await this.dropDatabase(this.config.get('dbName'));
> +    for (const extraSchema of this.getExtraSchemas()) {
> +      await this.dropDatabase(extraSchema);
> +    }
> +  }
> +
> +  private async dropSchemas() {
> +    if (this.config.get('schema')) {
> +      this.execute(this.helper.getDropSchemaSQL(this.config.get('schema')));
> 
> missing await
> 
> 
> In package.json <https://github.com/mikro-orm/mikro-orm/pull/1424#discussion_r654796633>:
> 
> > @@ -47,6 +47,7 @@
>      "publish:next": "lerna publish --canary major --preid dev --dist-tag next --force-publish",
>      "release:next": "yarn build && yarn publish:next",
>      "test": "jest --runInBand",
> +    "tsc": "tsc --noEmit",
> 
> should not be here
> 
> 
> In package.json <https://github.com/mikro-orm/mikro-orm/pull/1424#discussion_r654796648>:
> 
> > +  },
> +  "dependencies": {
> +    "jest-stare": "^2.2.2"
> 
> should not be here
> 
> 
> In package-lock.json <https://github.com/mikro-orm/mikro-orm/pull/1424#discussion_r654796734>:
> 
> > @@ -0,0 +1,11774 @@
> +{
> 
> remove the lock file, we are using yarn, not npm, and there should be no dependency changes in this PR
> 
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/mikro-orm/mikro-orm/pull/1424#pullrequestreview-687824572>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAIQSQWFWQLQHHKTIUJEC53T6SKYTANCNFSM4XP7PD6Q>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.
> 
>

2021-11-07 12:06 UTC, B4nan commented
Not sure if this PR is still relevant, given the changes from #2296

2021-11-08 07:47 UTC, Aeolun commented
@B4nan Probably not relevant any more. It looks like that does what I was trying to do with this one. Nice way of doing both multi-schema and multi-tenancy in one go.

If I find that #2296 doesn't do what I need, I'll submit a different PR based on that, but for now let's close this.

2021-11-08 07:47 UTC, closed without merging