feat(core): allow updating nested 1:1 and m:1 references with EntityAssigner
mikro-orm/mikro-orm pull request #1535
Opened 2021-03-08 13:34 UTC by jsprw

Currently, when you do the following:
```
const authorEntity = new Author('Jon2 Snow', 'snow3@wall.st');
book.author = authorEntity;

wrap(book).assign({ author: { name: 'Jon Snow2' } }, { mergeObjects: true });
console.log(book.author); // { ... name: 'Jon Snow2' ... }
console.log(book.author === authorEntity) // false
```
... it will try to create a new author entity with the name Jon Snow2 altough it can assign these values to the existing m:1 reference. Was doubting to fix the functionality for the mergeObjects flag, however that may be a breaking change.

Right now, it will only update loaded references; should I also implement initializing the enitity and then asssign the new values?

2021-03-15 17:23 UTC, B4nan requested changes

2021-03-15 17:23 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +
bad ident, how come this was not cought by eslint 🤫 
```suggestion

        return EntityAssigner.assignReference<T>(entity, value, props[prop], em!, options);
```

2021-03-15 17:23 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
we should handle identified references here too, also we first need to check if the entity is initialized

2021-03-15 17:23 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
also please try to get around that prototype pollution, it is probably not valid here, but let's play it safe

should be just about adding a check for `hasOwnProperty` at the `assign` method

2021-03-15 17:23 UTC, B4nan commented on tests/EntityAssigner.mysql.test.ts
> +  test('assign() should update m:1 or 1:1 nested entities [mysql]', async () => {
we need to test what happens if the relation is not there, if it is not populated, if it is a reference wrapper, ...

2021-03-15 17:25 UTC, B4nan commented
> should I also implement initializing the enitity and then asssign the new values?

The method is synchronous, you can't lazy load from there. 

But as I mentioned somewhere, I have a WIP that allows updating references (not loaded entities), see https://github.com/mikro-orm/mikro-orm/commit/78e5ef2efc2d38e179a379f890b03bd325245c99

I might postpone that change for v5, as it might be somehow breaking.

2021-03-15 19:12 UTC, jsprw commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
Doesn't it already do that?

options.updateNestedEntities: if the newly introduced flag is set
Utils.isEntity(entity[prop], false): whether the prop to be updated is an entity and not a reference
Utils.isPlainObject(value): whether the value to be set is an object and not a reference (number)

As it is a to 1 enitity, it is either initialized (object form) or else a reference right?

else: 

do the original behavior of the assign method.

2021-03-15 19:14 UTC, jsprw commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
I don't know why that error comes up now. As I did not change any of the property assignments. I just added an if-statement to check whether the to-be updated prop is an entity or not and if so, it just calls the same function with the entity and data.

Ill add a check but I thought that was not within the scope of this MR.

2021-03-15 19:14 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
> Utils.isEntity(entity[prop], false): whether the prop to be updated is an entity and not a reference

exactly, it does not allow references with the second `false` param, and that is what i am missing here (it will be more than just switching the flag, you will need to call `unwrap` on the wrapper first - it needs to be separate branch)

anyway, instead of guessing, add tests so you clearly see what it does and what not :] but i can assure you, this will ignore identified references.

2021-03-15 19:17 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
i think your confusion comes from the "reference" and "reference wrapper". a reference is an entity instance that is not initialized. still it is an entity instance.

on the other hand, reference wrapper = identified reference

2021-03-15 19:18 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
you actually did change the code paths, GH does a good job showing this. just click on `Show paths` to see yourself

![image](https://user-images.githubusercontent.com/615580/111208896-a0f1f980-85cb-11eb-8b2e-ed411ffcd1c7.png)

2021-03-15 20:29 UTC, jsprw commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
Ah, I see, but I don't understand why it has never shown that error before, see https://github.com/mikro-orm/mikro-orm/blob/master/tests/EntityAssigner.mysql.test.ts#L22. This test will fail now with that hasOwnProperty check.

2021-03-15 20:35 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
the `hasOwnProperty` check could be here, that should not cause any test failures. the problem is due to this newly introduced recursive assign in the end.

2021-03-15 21:00 UTC, jsprw commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
Yeah, understood. But doesn't that test demonstrate prototype pollution?

2021-03-15 21:02 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
nope, don't confuse prototype and instance properties

```ts
class A {}
const a = new A();
a.prop = 1; // instance
A.prototype.prop = 2; // prototype
```

2021-03-15 21:06 UTC, jsprw commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
Still confused how this in a second call may pollute the prototype. Anyways, moved the check.

2021-03-15 22:52 UTC, jsprw commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
would wrap(entity[prop]).isInitialized() cover the references? in my test cases, i saw it correctly being redirected to the assign reference method.

2021-03-15 22:57 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
yes it would, but the rest won't work, you can't call `assign(Reference, data)`. that is why i said you should have another branch that will handle reference wrapper and call `unwrap` on it first

something like this 

```ts
    if (Reference.isReference(value)) {
      value = value.unwrap();
    }

```

2021-03-15 22:59 UTC, jsprw commented on packages/core/src/entity/EntityAssigner.ts
> +        if (options.updateNestedEntities && Utils.isEntity(entity[prop], false) && Utils.isPlainObject(value)) {
Ah, excuse me, got it.

2021-03-16 08:11 UTC, B4nan commented on packages/core/src/entity/EntityAssigner.ts
> +          const unwrappedEntity = Reference.isReference(entity[prop]) ? entity[prop].unwrap() : entity[prop];
there is a helper for this already
```suggestion
          const unwrappedEntity = Reference.unwrapReference(entity[prop]);
```

2021-03-16 08:27 UTC, merged

2021-03-16 08:27 UTC, B4nan commented
Thanks!