feat(core): add PlainObject class that DTO's can extend to treat class as POJO
mikro-orm/mikro-orm pull request #1837
Opened 2021-05-19 21:36 UTC by Langstra

2021-05-20 14:14 UTC, B4nan requested changes
looking good, just two small docs issues

2021-05-20 14:14 UTC, B4nan commented on docs/docs/entity-manager.md
> +If you decide to abstract the filter options in your own object then you might run into the problem that the find option does not return the results you'd expect. This is due to the fact that the Fil
POJO comes from java and means plain old java object, here i'd call it plain old js object, but calling it json object seems weird :]

2021-05-20 14:14 UTC, B4nan commented on docs/docs/entity-manager.md
> +If you want to provide your own FilterQuery DTO, then your DTO class should extend the `PlainJson` class. This way MikroORM knows it should be treated as such.
the class is called `PlainObject` but you are referring to it in docs as `PlainJson`. I like `PlainObject` better, so lets just fix the docs.

2021-05-20 17:46 UTC, B4nan approved these changes

2021-05-27 14:14 UTC, Langstra commented
Can we merge this?

2021-05-28 15:28 UTC, merged