fix(core): use tsconfig-paths loadConfig function
mikro-orm/mikro-orm pull request #1854
Opened 2021-05-24 20:52 UTC by Langstra

This way the extended property of the tsconfig file can be read
property.

Fixes #1849

2021-05-25 07:24 UTC, B4nan requested changes

2021-05-25 07:24 UTC, B4nan commented on packages/core/src/utils/ConfigurationLoader.ts
> +    return Utils.requireFrom('tsconfig-paths', tsConfigPath).loadConfig(tsConfigPath);
the thing is, `tsconfig-paths` might not be there, its optional dependency needed only if you are using paths mapping - but we need to load the tsconfig to find out whether there is a paths mapping. 

in other words, this code can fail as the dependency won't be there unless explicitly installed by the user. and I'd rather not add a 3rd party depedency for such thing. 

on the other hand, `tsconfig-paths` is using JSON5 behind the scenes, which i was also considering as it would solve the problems with trailing commas in tsconfig files.

2021-05-25 07:24 UTC, B4nan commented on packages/core/src/utils/ConfigurationLoader.ts
> +          baseUrl: tsConfig.absoluteBaseUrl,
really `absoluteBaseUrl`? it is not documented in TS docs, is it something paths specific?

2021-05-25 22:12 UTC, Langstra commented
How about it this way? The `register` method returns the `tsconfig` which can be used to check for paths. Then the paths can be registered if they are there. This is even a lot easier than the first implementation where the tsconfig was loaded manually.

I'll have to fix the tests later, but wanted to leave this for feedback first.

2021-05-26 08:06 UTC, B4nan commented
Interesting! As long as it works :]

2021-05-26 21:15 UTC, Langstra commented
It does work, but I do not know how to mock the tsconfig-file. `jest.mock()` only mocks a module, but it does not load it is a module. I'd like some feedback on that or a suggestion on how to fix it.

2021-05-28 15:29 UTC, B4nan commented
No worries, I can look into that later myself, don't have much to advice without playing with it myself first :]

2021-05-28 15:30 UTC, merged