fix(schema): fix diffing mysql enum columns
mikro-orm/mikro-orm pull request #1866
Opened 2021-05-26 13:02 UTC by dmtar

In case of multiple schemas, by default the enum column definition was taken from the first schema in alphabetical order where the enum column may be in completely different state and causing non needed alters.

2021-05-26 13:09 UTC, B4nan commented on packages/mysql-base/src/MySqlSchemaHelper.ts
> +      where table_schema = database() and data_type = 'enum' and table_name = '${tableName}'`;
shouldn't we use the `schemaName` from parameter if its available (and fallback to `database()`)?

2021-05-26 14:25 UTC, B4nan commented on packages/mysql-base/src/MySqlSchemaHelper.ts
> +      where table_schema = database() and data_type = 'enum' and table_name = '${tableName}'`;
agreed

2021-05-28 21:02 UTC, B4nan requested changes
looks like we need more tests to get the coverage back to 100%

2021-06-11 14:57 UTC, B4nan commented
do you plan to finish this?

2021-06-14 07:36 UTC, dmtar commented
> do you plan to finish this?
Yes, was busy with lots of other stuff. I will try to do it this week

2021-06-19 13:41 UTC, closed without merging

2021-06-19 13:42 UTC, B4nan commented
Closing this as I did the change in https://github.com/mikro-orm/mikro-orm/commit/ecf79adc9e3fc1b3361649e88c5cdac80adb1626 and the multi schema will be handled in #1424, there is much more to change to have it working with multiple schemas and that PR will cover it.

Anyway, thanks for pointing this out!