Fix: Read replicas connection settings replaced by master settings
mikro-orm/mikro-orm pull request #1964
Opened 2021-06-25 18:13 UTC by rbrishabh

fixes #1963 

Hey @B4nan! How does this look?
let me know if this needs any changes!
Thanks

2021-06-25 18:17 UTC, B4nan requested changes
i guess that should make it work, would be great to add a test for this to ensure it really helps

2021-06-25 18:17 UTC, B4nan commented on packages/core/src/connections/Connection.ts
> +    this.options!.dbName = ret.database = (this.options!.dbName || this.config.get('dbName', url.pathname.replace(/^\//, '')));
let's use `??` instead

```suggestion
    this.options!.host = ret.host = (this.options!.host ?? this.config.get('host', url.hostname));
    this.options!.port = ret.port = (this.options!.port ?? this.config.get('port', +url.port));
    this.options!.user = ret.user = (this.options!.user ?? this.config.get('user', url.username));
    this.options!.password = ret.password = (this.options!.password ?? this.config.get('password', url.password));
    this.options!.dbName = ret.database = (this.options!.dbName ?? this.config.get('dbName', url.pathname.replace(/^\//, '')));
```

2021-06-25 18:25 UTC, rbrishabh commented
ok! I can do that! the test goes in here, right? `tests/Connection.test.ts`?

2021-06-25 18:41 UTC, B4nan commented
replicas are created in the constructor of `AbstractSqlDriver`, so we should test it from there. you could just initialize the ORM with given config that uses replicas (and has different connection options for them than the master db), mock the `getConnectionOptions` method of given connection class via `jest.spyOn` and check the params that were used.

2021-06-25 18:51 UTC, rbrishabh commented
got it! will get to this soon!

2021-07-21 16:33 UTC, rbrishabh commented
hi! I have a busy schedule and cant keep up with this now! Please feel free to continue it from here. I can close it for now

2021-07-31 08:15 UTC, ShinteiMai commented
@rbrishabh Hey, I would be glad to take over this issue. I'll continue from the work that you've done

2021-07-31 08:17 UTC, rbrishabh commented
Perfect! Go for it!

2021-07-31 08:18 UTC, rbrishabh commented
I've reopened the PR for you :)

2021-07-31 11:58 UTC, ShinteiMai commented
cc @rbrishabh I don't have write permission to your fork, so i forked my own repo then remote pulled your branch, here's the new PR https://github.com/mikro-orm/mikro-orm/pull/2081

2021-08-02 08:06 UTC, closed without merging