docs(recipes): add "Usage with AdminJS" recipe
mikro-orm/mikro-orm pull request #2321
Opened 2021-10-29 10:41 UTC by dziraf

Hello, I've been asked to create a recipe for usage with AdminJS. Please, let me know if this is fine and whether I have created/updated the required files. When I ran the development server, I had to duplicate my changes from `docs/docs/*` into `docs/versioned_docs/*` to be able to see them and it's the bit I'm actually confused about.

2021-10-31 16:42 UTC, B4nan requested changes
looking good, left few minor suggestions

2021-10-31 16:42 UTC, B4nan commented on docs/static/usage-with-adminjs/index.html
> +<!DOCTYPE html>
please remove this file, no need for redirects when you are adding new pages

2021-10-31 16:42 UTC, B4nan commented on docs/versioned_docs/version-4.5/usage-with-adminjs.md
> +  import AdminJS from 'adminjs';
no need for the initial indent, let's remove that

2021-10-31 16:42 UTC, B4nan commented on docs/versioned_docs/version-4.5/usage-with-adminjs.md
> +### MikroORM + Express Plugin
please keep one empty line after each heading

2021-11-03 11:39 UTC, dziraf commented
@B4nan thank you for your comments, I've done the changes you requested

2021-11-03 11:43 UTC, B4nan approved these changes

2021-11-03 11:43 UTC, merged