fix(pagination): move limit/offset to subquery to fix nested ordered pagination
mikro-orm/mikro-orm pull request #2351
Opened 2021-11-05 07:23 UTC by jamesmeneghello

Resolves #2095.

I have no idea if this is pure insanity or not, but it passes all tests (tests that were checking raw sql modified). The use of `min()` is required to sidestep group-by requirements.

2021-11-05 07:26 UTC, jamesmeneghello commented on packages/knex/src/query/QueryBuilder.ts
> +    const pks = this.prepareFields(meta.primaryKeys, 'sub-query') as any;
As much as I hate using `any` here, I'm not certain what the typing should be.

2021-11-05 07:31 UTC, jamesmeneghello commented on packages/knex/src/query/QueryBuilder.ts
> +    if (this._orderBy) {
This section is required to make the query SQL/92 compatible, which is required for the default SQL strictness for both PG and MySQL.

2021-11-05 13:08 UTC, B4nan commented
Amazing, thank you! Will try to review it soon and ship it to 4.x branch once merged.

Btw I believe the paginate flag was also failing on mysql 8, so maybe those changes will help with that too.

2021-11-05 14:07 UTC, jamesmeneghello commented
Not sure why the tests are failing, they work locally. I'll take a look this weekend.

2021-11-05 17:06 UTC, B4nan requested changes

2021-11-05 17:06 UTC, B4nan commented on packages/knex/src/query/QueryBuilder.ts
> +    const subSubQuery = this.getKnex().select(pks).from(knexQuery);
Do we actually need this subquery, when it does not have groupby/limit/offset? Feels redundant this way.

2021-11-05 17:06 UTC, B4nan commented on tests/issues/GH2095.test.ts
> +import { PostgreSqlDriver } from '../../packages/postgresql/src';
```suggestion
import { SchemaGenerator, PostgreSqlDriver } from '@mikro-orm/postgresql';
```

2021-11-06 10:08 UTC, jamesmeneghello commented on packages/knex/src/query/QueryBuilder.ts
> +    const subSubQuery = this.getKnex().select(pks).from(knexQuery);
Nope, totally redundant. Thanks!

2021-11-06 10:08 UTC, jamesmeneghello commented on packages/knex/src/query/QueryBuilder.ts
> +    if (this._orderBy) {
Yep, that was it - the original branch was off 4.5.9 iirc. Fixed now.

2021-11-06 10:12 UTC, B4nan commented on packages/knex/src/query/QueryBuilder.ts
> -    // https://stackoverflow.com/questions/17892762/mysql-this-version-of-mysql-doesnt-yet-support-limit-in-all-any-some-subqu
lets keep this comment, we still use 3 subqueries because of this

2021-11-06 10:12 UTC, B4nan commented on packages/knex/src/query/QueryBuilder.ts
> +    const subSubSubQuery = this.getKnex().select(pks).from(knexQuery);
also the variable name can stay as `subSubQuery`, right?

2021-11-06 10:14 UTC, B4nan commented on packages/knex/src/query/QueryBuilder.ts
> +    const pks = this.prepareFields(meta.primaryKeys, 'sub-query') as any;
what about just `as string[]` or `as unknown as string[]`?

2021-11-06 11:07 UTC, jamesmeneghello commented on packages/knex/src/query/QueryBuilder.ts
> -    // https://stackoverflow.com/questions/17892762/mysql-this-version-of-mysql-doesnt-yet-support-limit-in-all-any-some-subqu
2 subqueries now, I think?

2021-11-06 11:09 UTC, jamesmeneghello commented on packages/knex/src/query/QueryBuilder.ts
> +    const pks = this.prepareFields(meta.primaryKeys, 'sub-query') as any;
`string[]` works, thanks.

2021-11-06 11:11 UTC, jamesmeneghello commented on packages/knex/src/query/QueryBuilder.ts
> +    const subSubSubQuery = this.getKnex().select(pks).from(knexQuery);
Sure can!

2021-11-06 11:16 UTC, B4nan commented on packages/knex/src/query/QueryBuilder.ts
> -    // https://stackoverflow.com/questions/17892762/mysql-this-version-of-mysql-doesnt-yet-support-limit-in-all-any-some-subqu
oh right, i though you added extra one and now you removed it, but i see its the full diff of the PR and we now have one less query in there, nice!

2021-11-06 11:20 UTC, jamesmeneghello commented
One last change, just removing the extra logic around pks for SQL/92, as they never match anyway (`e0.id` vs `id`), which is what CodeCov caught.

2021-11-06 11:33 UTC, B4nan approved these changes

2021-11-06 11:49 UTC, merged