feat(core): add customOrder
mikro-orm/mikro-orm pull request #2444
Opened 2021-11-21 05:22 UTC by evantrimboli

2021-11-21 05:50 UTC, evantrimboli commented
@B4nan The test failures seem to do with the new entities, not sure where to correct that. Could you point me in the right direction?

2021-11-21 10:50 UTC, B4nan requested changes
thanks!

this definitely needs more tests, not just asserting the QB output, but actually testing this works in all SQL drivers (for mongo we would have to use aggregations, so lets skip that now)

please create the tests as suggested in the `tests/features` folder and test it actually works in all of pg/mysql/sqlite

2021-11-21 10:50 UTC, B4nan commented on packages/core/src/typings.ts
> +  customOrder?: PropertyOptions<T>['customOrder'];
maybe better to not import this at all and just inline the type (as the file where PropertyOptions is defined refereces typings.ts and vice versa)

2021-11-21 10:50 UTC, B4nan commented on tests/entities-sql/Task.ts
> +import { Entity, PrimaryKey, Enum, ManyToOne, Property } from '@mikro-orm/core';
instead of adding new entities here and dealing with all the snapshots, just create new test in features folder and define entities in the given file. that way there won't be any issues with the failed tests and the diff will be cleaner (no changed snapshots)

2021-11-21 10:50 UTC, B4nan commented on packages/knex/src/query/QueryBuilderHelper.ts
> +      const genExpr = customOrder
this looks weird, why dont you just inline it at the call site?

2021-11-21 10:50 UTC, B4nan commented on packages/knex/src/query/QueryBuilderHelper.ts
> +        const colPart = genExpr ? genExpr(rawColumn) : rawColumn;
you can remove all from lines 485-491 and here do just

```ts
const prop = this.getProperty(field, alias);
const customOrder = prop?.customOrder;
const colPart = customOrder ? this.platform.generateCustomOrder(rawColumn, customOrder) : rawColumn;

ret.push(`${colPart} ${order.toLowerCase()}`);
```

2021-11-21 23:12 UTC, B4nan requested changes
looking good, last two nitpicks!

2021-11-21 23:12 UTC, B4nan commented on packages/core/src/platforms/Platform.ts
> +    // ORDER BY (CASE WHEN priority = 'low' THEN 1 WHEN priority = 'medium' THEN 2) ... etc
let's put this into jsdoc of the method

2021-11-21 23:12 UTC, B4nan commented on tests/features/custom-order/custom-order.mysql.test.ts
> +    Object.assign(orm.config, { logger });
after you rebase this with latest changes from master, you will need to change this in all the tests to use `mockLogger()` function from `bootstrap.ts`
```suggestion
    const mock = mockLogger(orm, ['query']);
```

(don't forget to remove the import for `Logger`)

2021-11-21 23:17 UTC, B4nan commented
Would be good to mention this in the docs somewhere, not just as a decorator option, but with an example. Maybe a recipe, or we could squeeze it on the entity manager page.

2021-11-21 23:57 UTC, B4nan approved these changes

2021-11-21 23:58 UTC, B4nan commented
good job, one last thing is the broken linter, then we are good to merge

2021-11-22 00:04 UTC, evantrimboli commented
The linting didn't pick up anything locally, does it not run for the test folder?

2021-11-22 08:21 UTC, B4nan commented on packages/knex/src/AbstractSqlPlatform.ts
> +  generateCustomOrder(escapedColumn: string, values: unknown[]): string {
```suggestion
  /** @inheritDoc */
  generateCustomOrder(escapedColumn: string, values: unknown[]): string {
```

2021-11-22 08:21 UTC, B4nan commented on packages/core/src/platforms/Platform.ts
> +    throw new Error('Not supported');
this method is not covered by tests

2021-11-22 17:40 UTC, merged

2021-11-22 17:40 UTC, B4nan commented
thanks!