refactor(seeder): make more consistent
mikro-orm/mikro-orm pull request #2605
Opened 2022-01-05 23:05 UTC by r3tard

Hello

refactored seeder to be more consistent to migration package (`path` processing and default path): i think we shouldn't prepend `process.cwd()` to user path

deleted method `refreshDatabase`. `SchemaGenerator` exist only when user uses sql, but seeder for mongodb and custom drivers too, so user can explicit call `dropSchema` and `createSchema` methods on `SchemaGenerator`

BREAKING CHANGE:
- default seeders path: `./seeders` instead `./database/seeder` (like migrations `./migrations`). 
- removed `refreshDatabase` method on `SeedManager`

2022-01-09 11:44 UTC, B4nan commented
> i think we shouldn't prepend process.cwd() to user provided path

That's not how it works with migrations. You can provide absolute path, if you provide relative, `baseDir` is prepended, which defaults to `process.cwd()`. 

I also don't see a reason to remove the `refreshDatabase` method. But its location is indeed wrong, it should live on `SchemaGenerator`.

cc @Langstra

2022-01-09 12:13 UTC, Langstra commented
> > i think we shouldn't prepend process.cwd() to user provided path
> 
> That's not how it works with migrations. You can provide absolute path, if you provide relative, `baseDir` is prepended, which defaults to `process.cwd()`.
> 
> I also don't see a reason to remove the `refreshDatabase` method. But its location is indeed wrong, it should live on `SchemaGenerator`.
> 
> cc @Langstra

I'll also take some time tomorrow to review this.

2022-01-10 10:22 UTC, Langstra commented
I think most of these changes definitely are an improvement over te current code. Agree with B4nan that the `refreshDatabase` method is a useful one. 
I am unsure how the determination of the path works exactly with the migrations. The only thing I could find about providing a relative path is with the migration running itself, not with the generation of the migrations. So if you are okay with that, then I leave that up to you.

2022-01-10 17:27 UTC, r3tard commented
> Agree with B4nan that the `refreshDatabase` method is a useful one.

I added `refreshDatabase` method to `SchemaGenerator` and `refreshCollections` to `MongoDriver` (should it call `ensureIndexes` after `createCollections`?)

2022-01-10 17:35 UTC, B4nan requested changes
> I added refreshDatabase method to SchemaGenerator and refreshCollections to MongoDriver (should it call ensureIndexes after createCollections?)

Let's add a parameter for that (let's use an options object right ahead, with a single property for now), I'd do it by default, but it should be configurable.

The changes are looking good to me, thanks a lot! 

I'd like to support relative paths as we do in migrations. The way it works there is basically this line, that normalizes the path to absolute, prepending the `baseDir` if the path is relative. 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/migrations/src/Migrator.ts#L26

2022-01-11 09:32 UTC, B4nan requested changes
looking good, just one nitpick. if the test suite is green and we keep full branch coverage, we can merge

2022-01-11 09:32 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +      await this.rethrow(this.ensureIndexes());
no need to use `rethrow` from this method - all the methods it calls are using it internally
```suggestion
    await this.dropCollections();
    await this.createCollections();

    if (options.ensureIndexes) {
      await this.ensureIndexes();
```

2022-01-11 10:24 UTC, B4nan commented
Something's wrong with the tests. They all passed, but did not finish the process. This was not happening before and is not happening in master.

2022-01-11 11:05 UTC, r3tard commented
> Something's wrong with the tests. They all passed, but did not finish the process. This was not happening before and is not happening in master.

Now it should finish correctly, my bad.

2022-01-11 11:43 UTC, r3tard commented on packages/mongodb/src/MongoDriver.ts
> +      await this.rethrow(this.ensureIndexes());
removed `rethrow`

2022-01-11 12:11 UTC, merged