feat(core): add custom table check constraint support for postgres
mikro-orm/mikro-orm pull request #2688
Opened 2022-01-30 16:22 UTC by DASPRiD

Adds a new `@Check` decorator for entities, allowing to set up custom check
constraints. At the moment, this is only for Postgres, as MySQL only supports
check constraints as of version 8, which is above the minimum test version.

While SQLite does in theory support check constraints already, tests broke due
to some bug in Knex, which is why the implementation was skipped for now.

This partially addresses #1711

2022-01-30 16:39 UTC, DASPRiD commented
I gonna address the outstanding issues once I receive general sign-off or feedback on this PR :)

2022-01-30 16:56 UTC, B4nan requested changes
thanks, overall looking great!

would be good to support the property level checks too, but we can merge this first and add it later. will be happy to give it a shot myself, as i would rather not ship that `_custom` thing to stable v5

2022-01-30 16:56 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +    table.check(check.expression, {}, `${check.name}_custom`);
why the `_custom` suffix? can't say i like it, this should be fully configurable. is this kind of hack due to the missing support for property level check constraints? would be good to support those too, i guess it should be rather easy, or do you see problems with it? 

nit: not sure if the input type should be `CreateTableBuilder` - we use this for altering too, right?

2022-01-30 16:56 UTC, B4nan commented on packages/knex/src/schema/SchemaComparator.ts
> +      tableDifferences.addedChecks[check.name] = check;
i guess we should also do `changes++` here

2022-01-30 16:56 UTC, B4nan commented on packages/postgresql/src/PostgreSqlSchemaHelper.ts
> +import { schema } from '../../../tests/entities';
remove this

2022-01-30 16:56 UTC, B4nan commented on packages/postgresql/src/PostgreSqlSchemaHelper.ts
> +      expression: check.expression.replace(/^CHECK \(\((.+)\)\)$/, '$1'),
lets make this case insensitive

2022-01-30 16:56 UTC, B4nan commented on packages/sqlite/src/SqliteSchemaHelper.ts
> +import type { AbstractSqlConnection, Index ,Check } from '@mikro-orm/knex';
bad formatting

2022-01-30 16:56 UTC, B4nan commented on tests/features/schema-generator/check-constraint-postgres.test.ts
> +import { Check, Entity, EntitySchema, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';
the file name should be different, aligned with the rest (so `check-constraints.postgres.test.ts`)

2022-01-30 16:56 UTC, B4nan commented on tests/features/schema-generator/check-constraint-postgres.test.ts
> +    const generator = new SchemaGenerator(orm.em);
`orm.getSchemaGenerator()`

2022-01-30 16:58 UTC, B4nan commented
> Due to already existing other check constraints (namely, enums in Postgres), I decided to suffix all custom check constraint names with _custom, so I can filter them out where necessary.

If that is the only reason, I would definitely like to refactor it before stable v5 is out, but I can do that myself after we merge.

2022-01-30 17:04 UTC, DASPRiD commented
Thanks a lot for your quick feedback!

Would you like to me to address the mentioned points, or would you rather prefer to just fork from my branch, since you mentioned that you'd like to introduce some changes and additions to it anyway?

2022-01-30 17:06 UTC, B4nan commented
Yes please, address it here before we merge it (as said I am fine merging the `_custom` thingy for now). Would be good to also test the uncovered lines.

2022-01-30 17:21 UTC, DASPRiD commented on packages/knex/src/schema/SchemaGenerator.ts
> +    table.check(check.expression, {}, `${check.name}_custom`);
It seems to work fine for altering as well, and `CreateTableBuilder` was also used for all other alterations (see `createIndex` and `dropIndex`).

2022-01-30 17:34 UTC, B4nan commented
please dont rebase and force push, so i can see what you actually changed _after_ the review

2022-01-30 17:38 UTC, DASPRiD commented
> please dont rebase and force push, so i can see what you actually changed _after_ the review

Sorry, force of habit :) – Will to separate commits on here from now on!

2022-01-30 17:49 UTC, B4nan approved these changes
perfect!

2022-01-30 17:49 UTC, merged

2022-01-31 10:26 UTC, PodaruDragos commented
Hello guys
Are we aware that this PR breaks projects since it needs to add checks in migrations ?
I had to create migration again so that it adds checks, checks that I don't need.

```
    this.addSql('alter table "user" drop constraint if exists "user_id_check";');
    this.addSql('alter table "user" alter column "id" type bigint using ("id"::bigint);');
    this.addSql('alter table "user" drop constraint if exists "user_created_at_check";');
```

Do I need to do anything to ignore this ?
Is this behavior by default since the merging of this PR ?

2022-01-31 10:34 UTC, B4nan commented
It works just fine in the tests, so please provide reproduction so we can see more details. Not sure what you mean by "since it needs to add checks in migrations", this PR adds support for diffing check constraints. If you were using some before, you will need to define them in the entity definition (via the `@Check()` decorator), otherwise the ORM will try to remove them. That is correct behaviour, you need to define all check constraints now at the metadata level.

2022-01-31 11:39 UTC, PodaruDragos commented
I have no idea what so ever. If this persist I am gonna make a repro.
what I can tell you for sure is that I didn't have any `checks` before.

2022-01-31 12:22 UTC, B4nan commented
Don't be too concerned with the `drop constraint if exists` queries - [those are there for each column update query](https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlConnection.ts#L72), we do it blindly as we did not know before if there is a constrain or not. We could improve there finally, as we have this information. Will take a look if we can, I would very much like to get rid of this hack.

Try adding some logs to the schema comparator to see what caused the alter column query, there can be many reasons - obviously if it broke now, it might be because of the check constraints, but the ORM was using them only for enums in postgres, so it sounds weird to see a query for altering PK column (but I really can imagine you actually had such constraint before, PKs are unsigned and postgres does not have unsigned columns, it can be done only via check constraints, and maybe that is what you get from serial/bigserial meta types).

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaComparator.ts#L375

2024-12-23 05:44 UTC, denisamirov commented
> I have no idea what so ever. If this persist I am gonna make a repro. what I can tell you for sure is that I didn't have any `checks` before.

Hi. I have a similar problem. When setting constraints with the @Check, migrations are overwritten.
Have you found a solution?