fix: handle 'file://' urls in normalizePath/relativePath/absolutePath
mikro-orm/mikro-orm pull request #2697
Opened 2022-02-02 01:21 UTC by itsame-luigi

This fixes path handling in `Utils` to handle `file://` URLs, which can sometimes be introduced in stack traces in NodeJS.

Fixes #2654

2022-02-02 09:08 UTC, B4nan requested changes
thanks, the changes are looking rather good, but the tests will need a bit more love :]

2022-02-02 09:10 UTC, B4nan commented
> This also improves handling for absolute path components in normalizePath so that normalizePath("a", "C:/b") produces "C:/b" rather than "a/C:/b".

Now I see this. Well, I am not really interested in supported that, such input should be never used from the ORM, and if it would, we should fail instead of magically ignoring some part of that path.

2022-02-02 19:28 UTC, itsame-luigi commented on tests/Utils.test.ts
> +  test.each`
I had changed the test to use Jest's `.each` feature because the way the test was written a single failure would hide other later failures, making it hard to determine what impact a change had. These would be better written as individual tests rather than one test with a bunch of `expect`s, and `.each` is designed to provide that convenience (as each entry in the table equates to a separate test).

I can restore the original test definition, but you should consider leveraging `.each` for tests like this in the future (either using its template-string-literal table format, or the simpler array mechanism).

2022-02-02 19:32 UTC, itsame-luigi commented on packages/core/src/utils/Utils.ts
> +    for (let i = 0; i < parts.length; i++) {
> why would you iterate on all parts here, this can be problem only with the first one, right? can `start` actually be something else than `0` or `1`? for which case?

Since `normalizePath` takes possibly more than two inputs, there's no way to know which "part" will be absolute, and I preferred to future-proof `normalizePath` in the event later code is written that passes `normalizePath("./a", "b", "/c")`.

> this feels like if you would do `normalizePath('./relative', '/absolute')` you would somehow ignore the first part, which would be wrong. such call is obviously weird, but should end up with using the whole path and considering it as relative

I disagree that it is wrong, as that's exactly the bug I am trying to fix. In the linked issue, I mentioned part of the underlying problem was that `normalizePath` was generating something like this: `C:\dev\project\file:\C:\dev\project\entities\foo.ts`, because the 2nd part passed in is absolute.

2022-02-02 19:38 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +    for (let i = 0; i < parts.length; i++) {
> Since normalizePath takes possibly more than two inputs, there's no way to know which "part" will be absolute

Only the first part can be absolute, otherwise its invalid input. This was never supported. 

Supporting this here sounds more like you are trying to fix the bug on wrong place.

2022-02-02 19:40 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +    for (let i = 0; i < parts.length; i++) {
> I mentioned part of the underlying problem was that normalizePath was generating something like this: C:\dev\project\file:\C:\dev\project\entities\foo.ts, because the 2nd part passed in is absolute.

Yes, so the bug is somewhere above, where such path is being constructed, as that path is invalid.

2022-02-02 20:30 UTC, itsame-luigi commented on tests/Utils.test.ts
> +  const isWindows = process.platform === 'win32';
I can just mock the expected return value of `fileURLToPath` for each platform.

2022-02-02 20:36 UTC, B4nan commented on tests/Utils.test.ts
> +  test.each`
i dont mind using `test.each`, i just dont like the tagged literal signature :]

2022-02-02 20:40 UTC, itsame-luigi commented
> > This also improves handling for absolute path components in normalizePath so that normalizePath("a", "C:/b") produces "C:/b" rather than "a/C:/b".
> 
> Now I see this. Well, I am not really interested in supported that, such input should be never used from the ORM, and if it would, we should fail instead of magically ignoring some part of that path.

If that's the case, then `initEnumValues` needs to call `normalizePath` in the same way that `discoverDirectories` does:

```ts
const path = Utils.normalizePath(...(isAbsolute(filepath) ? [filepath] : [this.config.get('baseDir'), filepath]));
``` 

Alternatively, if `normalizePath` *does* handle absolute parts, then that line in `discoverDirectories` could be rewritten to this instead:

```ts
const path = Utils.normalizePath(this.config.get('baseDir'), filepath);
```

I suppose the question is this: Should `normalizePath` be more similar to `path.join` (which doesn't care about absolute parts), or `path.resolve` and `new URL(url, baseUrl)` (which do care about absolute parts)?

2022-02-02 20:46 UTC, B4nan commented
> Alternatively, if normalizePath does handle absolute parts, then that line in discoverDirectories could be rewritten to this instead:

Hmm ok I guess I am sold, let's keep it the way you proposed, but please document this in that method's jsdoc and adjust that `discoverDirectories` usage (maybe there are other places where we do this, I could imagine migrations and entity generator).

2022-02-02 22:00 UTC, B4nan commented
icymi

```
FAIL tests/features/entity-generator/EntityGenerator.test.ts
  ● EntityGenerator › generate entities from schema [mysql]

    expect(received).resolves.toBe(expected) // Object.is equality

    Expected: true
    Received: false

      12 |     const dump = await generator.generate({ save: true, baseDir: './temp/entities' });
      13 |     expect(dump).toMatchSnapshot('mysql-entity-dump');
    > 14 |     await expect(pathExists('./temp/entities/Author2.ts')).resolves.toBe(true);
         |                                                                     ^
      15 |     await remove('./temp/entities');
      16 |
      17 |     await orm.close(true);

      at Object.toBe (node_modules/expect/build/index.js:242:22)
      at Object.<anonymous> (tests/features/entity-generator/EntityGenerator.test.ts:14:69)
```

2022-02-03 07:18 UTC, B4nan commented on packages/entity-generator/src/EntityGenerator.ts
> +    const baseDir = Utils.normalizePath(options.baseDir || this.config.get('baseDir') + 'generated-entities');
this change seems wrong

2022-02-03 07:37 UTC, itsame-luigi commented on packages/entity-generator/src/EntityGenerator.ts
> +    const baseDir = Utils.normalizePath(options.baseDir || this.config.get('baseDir') + 'generated-entities');
Yeah, typo while trying to revert that change. Will push up a fix tomorrow.

2022-02-03 07:44 UTC, B4nan commented on packages/entity-generator/src/EntityGenerator.ts
> +    const baseDir = Utils.normalizePath(options.baseDir || this.config.get('baseDir') + 'generated-entities');
```suggestion
    const baseDir = Utils.normalizePath(options.baseDir || this.config.get('baseDir') + '/generated-entities');
```

2022-02-03 07:57 UTC, merged

2022-02-03 08:40 UTC, B4nan commented
Thanks a lot! Your PR is already part of just released `rc.2` version.

2022-02-05 12:14 UTC, B4nan commented
I am really glad you proposed that trick with supporting absolute paths at any position, it's really handy! (didn't even know this is how the `path.resolve` works)