feat(core): allow forcing write connection via `forceWriteConnection`
mikro-orm/mikro-orm pull request #2838
Opened 2022-03-01 11:17 UTC by oliversalzburg

This allows to bypass replica read attempts through the `FindOptions`, by setting the `forceWriteConnection` flag.

The intent is to allow users to force reads onto a master, if the user assumes that an entity has not been replicated yet.

2022-03-01 12:26 UTC, B4nan requested changes

2022-03-01 12:26 UTC, B4nan commented on tests/features/replica-selection.test.ts
> +    await new SchemaGenerator(orm.em).createSchema();
```suggestion
    await orm.getSchemaGenerator().refreshDatabase();
```

2022-03-01 12:26 UTC, B4nan commented on docs/docs/read-connections.md
> +const res4 = await em.findOne(Author, 1, { forceMasterRead: true }); // write connection
let's call it `forceWriteConnection`

2022-03-01 12:26 UTC, B4nan commented on tests/features/replica-selection.test.ts
> +      replicas:[ { host:'invalidhostname' } ],
```suggestion
      replicas: [{ host: 'invalidhostname' }],
```

2022-03-01 12:26 UTC, B4nan commented on tests/features/replica-selection.test.ts
> +    expect(readFromMaster).toBe(user);
No need for forking, we have the global context check disabled in tests.

But I am not sure what was this this test about. It would not fire any query, `findOne` with a PK condition will just take the entity from identity map. It would be passing even without that flag, and even if you would remove that entity from the database between the calls. 

You should check that it used the write connection, check this test: 

https://github.com/mikro-orm/mikro-orm/blob/master/tests/EntityManager.mysql.test.ts#L1943

Maybe you could just add this to the mysql test instead of creating new one.

2022-03-01 12:39 UTC, oliversalzburg commented on tests/features/replica-selection.test.ts
> +    expect(readFromMaster).toBe(user);
I missed those specific tests earlier. Good call. I updated the commit and am now waiting for checks to pass.

2022-03-01 13:43 UTC, B4nan requested changes

2022-03-01 13:43 UTC, B4nan commented on docs/docs/read-connections.md
> +const res4 = await em.findOne(Author, 1, { forceMasterRead: true }); // write connection
docs still using the old name

2022-03-01 13:44 UTC, B4nan commented
please dont rebase after you get a review, so we maintain the history

2022-03-01 13:48 UTC, oliversalzburg commented
Are the commits ultimately squashed before merging or does every single commit actually have to make sense?

2022-03-01 13:55 UTC, B4nan commented
Yes, only one commit will go to master and the commit message is based on the PR title (and I can override it when merging).

2022-03-01 14:54 UTC, B4nan commented
Yeah not a big deal for such a small PR, but I started to say this out load when I see it, otherwise things never change :]

2022-03-01 15:53 UTC, merged

2022-03-10 18:07 UTC, asiFarran commented
@B4nan @oliversalzburg, in our application the vast majority of queries should run against the master in order to support immediate-read-after-write scenarios, but we do want to use read-replicas for a few specific use-cases (e.g. customer search or analytics queries).

Using the pattern above we'd have to add `forceWriteConnection : true` to almost all queries which is .... you get it.

I would like to propose the following (more generic) pattern:
1. Add a `useReadReplicasByDefault?: boolean`  to [Configuration](https://github.com/mikro-orm/mikro-orm/blob/ffe6bd886ddc0c97bbfde600c3bec26570f3ca33/packages/core/src/utils/Configuration.ts#L41). This defaults to `true` so no breaking change and existing behavior is maintained.
2. Replace  `forceWriteConnection` on `FindOptions` with a `useConnection?: 'read' | 'write'` property that lets the developer be specific in both directions
3. Use both the configurable default and the optional explicit setting to choose the connection.

This way the connection resolution strategy is completely configurable and can support all scenarios.

Does this sound reasonable to you ? I'm happy to open a PR for it

2022-03-10 18:07 UTC, asiFarran commented
@B4nan @oliversalzburg, in our application the vast majority of queries should run against the master in order to support immediate-read-after-write scenarios, but we do want to use read-replicas for a few specific use-cases (e.g. customer search or analytics queries).

Using the pattern above we'd have to add `forceWriteConnection : true` to almost all queries which is .... you get it.

I would like to propose the following (more generic) pattern:
1. Add a `useReadReplicasByDefault?: boolean`  to [Configuration](https://github.com/mikro-orm/mikro-orm/blob/ffe6bd886ddc0c97bbfde600c3bec26570f3ca33/packages/core/src/utils/Configuration.ts#L41). This defaults to `true` so no breaking change and existing behavior is maintained.
2. Replace  `forceWriteConnection` on `FindOptions` with a `useConnection?: 'read' | 'write'` property that lets the developer be specific in both directions
3. Use both the configurable default and the optional explicit setting to choose the connection.

This way the connection resolution strategy is completely configurable and can support all scenarios.

Does this sound reasonable to you ? I'm happy to open a PR for it

2022-03-10 18:10 UTC, B4nan commented
Sounds good to me, PR welcome. Given this PR is not yet shipped in stable, I don't mind replacing the newly added `forceWriteConnection` with `useConnection`.

2022-03-14 13:11 UTC, oliversalzburg commented
Awesome change btw :)