feat(core): allow entity metadata hooks to also be functions
mikro-orm/mikro-orm pull request #2895
Opened 2022-03-11 12:55 UTC by techmunk

2022-03-11 12:58 UTC, techmunk commented
I'm not sure the typing of hooks is 100% correct, but I'm not savvy enough with typescript to get it more accurate.

2022-03-11 13:08 UTC, techmunk commented
Thanks @B4nan. I had considered the subscribers, however I was building this functionality onto a base entity and was hoping to keep it contextualized to that entity. Does the `getSubscribedEntities` method of an entity subscriber work for base entities?

2022-03-11 13:14 UTC, B4nan commented
With a bit of metadata magic you could automatically list entity types that extends specific base entity. But the approach this PR allows seems to be much cleaner.

2022-03-11 13:15 UTC, B4nan commented
Speaking of base entities, it would be probably good idea to add a test that defines a hook on base entity this way too.

2022-03-11 13:17 UTC, B4nan commented
And we also need a mention about this new feature to the docs. I would add it to the entity schema docs, as that is the main use case for it.

2022-03-11 15:09 UTC, techmunk commented
@B4nan I've pushed an update with some docs written and some tests on a base entity. I did have one strange issue with the base entity that I could not get to the bottom of though....

When the base entity schema was just an object (and not an EntitySchema instance), the hook functions would be in the hooks array, but would be `null`. Changing the schema to use `new EntitySchema()` instead, fixed this issue.

I don't really understand why, but I assume there's something in the entity discovery that works  a bit differently in those two cases.

2022-03-11 15:11 UTC, techmunk commented
To be clear, only the functions would be null, the string method names were there and fine.

2022-03-11 15:23 UTC, B4nan requested changes

2022-03-11 15:23 UTC, B4nan commented on docs/docs/entity-schema.md
> +const beforeUpdate2 = (args: EventArgs) => args.entity.version++
```suggestion
const beforeUpdate2 = (args: EventArgs) => args.entity.version++;
```

2022-03-11 15:23 UTC, B4nan commented on docs/docs/entity-schema.md
> +export const schema = new EntitySchema<BookTag>({
this is inferred from `class`

```suggestion
export const schema = new EntitySchema({
```

2022-03-11 15:23 UTC, B4nan commented on packages/core/src/events/EventManager.ts
> +    const listeners: (readonly [PropertyKey | NonNullable<EventSubscriber<T>[keyof EventSubscriber<T>]>, EventSubscriber<T> | AnyEntity<T>])[] = [];
please extract this into a new type, its too complex and reduces readabilty, same for the `runListener` usage

2022-03-11 15:23 UTC, B4nan commented on packages/core/src/events/EventManager.ts
> +        return subscriber[hook]!(args as (EventArgs<T> & FlushEventArgs & TransactionEventArgs));
let's extract `EventArgs<T> & FlushEventArgs & TransactionEventArgs` to a type too

2022-03-13 08:22 UTC, merged

2022-03-13 10:40 UTC, techmunk commented
@B4nan Thanks. I was actually just sitting down to work on this and saw that you merged it! Cheers for all the hard work you put in!

2022-03-13 11:32 UTC, B4nan commented
FYI just finished with simplifying the implementation as well as types a bit: https://github.com/mikro-orm/mikro-orm/commit/f3599292515941d3bef365160b18685eb15227d3

2022-03-13 11:39 UTC, techmunk commented
That's a much cleaner implementation. :+1: