fix(postgres): do not ignore custom PK constraint names
mikro-orm/mikro-orm pull request #2931
Opened 2022-03-19 10:47 UTC by jbl428

resolve #2930

2022-03-19 11:05 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
it really feels wrong to me, i would expect this call to stay as is. `createPrimary` is there to disallow creating PKs. how can that be controlled based on naming strategy? naming strategy tells us how to name the PK, not whether it should be generated

2022-03-19 12:30 UTC, jbl428 commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
> let me know if i am wrong :)

I think that `createPrimary` is somewhat misleading because PK is generated even if it is `false`.
I think it has different meanings depending on the context.

- `createTable` method: should use custom PK name
- `alterTable` method: should create PK

Maybe we can handle this by making separated `createPrimaryKey` method. what do you think?

2022-03-19 12:41 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
> I think that createPrimary is somewhat misleading because PK is generated even if it is false.

not thru this method, it literally skips primary keys based on this flag. i dont understand why that behaviour should be altered based on anything related to naming strategy. definitely not because we have it explicitly set in the configuration, that to me seems like something that should be transparent, it cant have any side effects. 

> I think it has different meanings depending on the context.

it has always the same meaning - skip PK indexes. the value is different based on where it is used, not the meaning.

2022-03-19 12:52 UTC, jbl428 commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
> and lastly, it sounds very weird to me to depend on whether there is an override for NS - as it can be easily an override for the very same value as the default for given driver was.

I thought that `Configuration` instance is override only by user. 😢 
I have added codes checking if it has overide naming strategy since it requires one more sql to have custom PK name and we usually don't need to custom PK names.

2022-03-19 13:16 UTC, jbl428 commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
because of my English, myabe I didn't fully understand what you said 😢 
but If we have the following code

```ts
@Entity()
class A {

  @PrimaryKey()
  id!: number;

}
```

Since `id` is considered as `autoincrement`, `createPrimay` valus is `false`. 
but the following sql is genereated.

```sql
create table "a" ("id" serial primary key, "prop" varchar(255) not null);
```

so i have thought that `createPrimary` is somewhat misleading. :)

2022-03-19 13:48 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
> I thought that Configuration instance is override only by user. 😢

First of all, there are defaults in place, there is no way to distinguish default value from what a user sets (other than comparing to the defaults) - and even if there was one, I don't understand why it should make any difference. The value is important, not whether its default or user provided. Second, the NS does not have to be custom, e.g. you might want to use `EntityCaseNamingStrategy`, as is, without any overrides. Your code would alter behaviour just because someone used different NS than the driver's default one. Third, we might change how the defaults work in some future versions. 

Regarding the confusion, its an internal/private method, feels like you are basing your expectations on public API based on internal method's parameter. 

I will check the code myself when I have time so I can suggest some other way. I would say we should do this based on whether the NS produces a value other than what the driver would do by default (without providing one). The default is to produce PK name as "{table}_pkey", which is what you get if you dont specify the name explicitly.

Those two statements produce the same:

```sql
create table "label2" ("uuid" uuid not null primary key, "name" varchar(255) not null);
```

and 

```sql
create table "label2" ("uuid" uuid not null, "name" varchar(255) not null);
alter table "label2" add constraint "label2_pkey" primary key ("uuid");
```

So if we see the NS gives us something else, we should use the explicit second query with the name, otherwise there is no need for it. This logic should be in the `SchemaHelper` level probably, where it can be driver specific (note that other SQL drivers usually enforce the PK name, like in mysql its always `PRIMARY`). There we could have something like `getDefautlPrimaryName` method.

2022-03-20 08:01 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
I'd say the way I described above should be fine, let's have a driver specific method that will give us the default PK name and compare that with the NS. Currently we have `Platform.getIndexName()` which handles the driver specific cases, so we should have the `getDefaultPrimaryName` method next to it I guess.

Will you have time for this later today? No pressure, but I'd like to ship new stable version, so want to know whether I should wait for this one, but it can of course be part of any other future version.

2022-03-20 10:21 UTC, jbl428 commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index,
Sorry for late response. 
I think I do not have enough time today. so this one would be part of next version. :)

2022-03-22 07:34 UTC, B4nan requested changes

2022-03-22 07:34 UTC, B4nan commented on packages/core/src/platforms/Platform.ts
> +  }
this seems like a wrong default to me, how can you then compare the default implementation with the one from naming strategy, if both ways use the naming strategy?

2022-03-22 08:02 UTC, B4nan requested changes
i would say this can be done in much more readable way, now it seems quite confusing to me, please give it another try, or i can take over if you want :]

2022-03-22 08:02 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index, tableDef, true);
i dont understand why the `createPrimary` is no longer driven by this, i believe it was still valid, and now you just hide it inside the method implementation, making it much more complex

2022-03-22 08:24 UTC, B4nan commented
Based on the code changes, it feels like you wanted to make all the existing tests pass. That is wrong, the snapshots are not 100% correct, this change should be reflected in them too. One example is that `Label2` entity I mentioned above, the PK name it uses explicitly in current snapshots is the default and _should not_ be explicitly stated. Maybe that is the reason why the implementation looks overcomplicated.

2022-03-22 14:42 UTC, jbl428 commented
> Maybe that is the reason why the implementation looks overcomplicated.

Yes, you are right. I have thought that this PR should not impact existing behavior and only add functionality to have custom PK name in postresql.

If we are allowed to change existing behavior. I think I can make more readable code.

2022-03-22 15:00 UTC, jbl428 commented on packages/knex/src/schema/SchemaGenerator.ts
> +  private createIndex(table: Knex.CreateTableBuilder, index: Index, tableDef: DatabaseTable, createPrimary = false, useExplicitPKName = false) {
I have one question.
Could we change existing behavior to have explicit PK name when PK column is `autoincrement`?

2022-03-22 15:05 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +  private createIndex(table: Knex.CreateTableBuilder, index: Index, tableDef: DatabaseTable, createPrimary = false, useExplicitPKName = false) {
> If PK columns is autoincrement and table.primary() is fired

It should not be fired, that is the exact reason why we have the `createPrimary` parameter

> Could we change existing behavior to have explicit PK name when PK column is autoincrement?

Nope, that would affect most of the users in a bad way I'd say. I want the exact opposite, have the names there only when needed, not always. 

> If table.primary() is not fired. It generates primary key keyword anyway.

That's because the `column.primary()` is called for those. As said above, we have the `createPrimary` parameter to distinguish.

2022-03-22 15:27 UTC, jbl428 commented on packages/knex/src/schema/SchemaGenerator.ts
> +        this.createIndex(table, index, tableDef, true);
To check if `table.primary()` should be called. 

- Have override for NS  <- should be called
- Not have override and table has some `autoincrement` <- should not be called
- Not have override and table do not have `autoincrement` <- should be called

To handle the above branches in `createIndex`. I have changed the `createPrimary` code.

2022-03-22 15:57 UTC, B4nan commented
maybe i should finish this myself, i just checked the code more in depth and it is a bit more complicated, as the current code was doing some workaround to make things work the way they work, and those should be refactored as well, otherwise we cant make this cleaner.

will try to spend some time with it and report back to you

2022-03-23 09:37 UTC, merged

2022-03-23 09:37 UTC, B4nan commented
Thanks a lot!