fix(mongo): add retry limit to 3 if indexing fails while adding invalid indexes
mikro-orm/mikro-orm pull request #3272
Opened 2022-07-01 04:09 UTC by jagzmz

Relates to https://github.com/mikro-orm/mikro-orm/issues/3261

@B4nan I am not sure how would I reproduce the error on tests, they are not complete as of now, any suggestions ?

2022-07-01 07:50 UTC, B4nan commented
Here it should be enough if you define the unique constraint, but dont create it right ahead, create the two rows, and then call `ensureIndexes()` afterwards. First comment out the changes you made to verify such test will fail, then see how your fix is working.

2022-07-01 13:07 UTC, B4nan approved these changes
thanks! just few nits before we merge

2022-07-01 13:07 UTC, B4nan commented on tests/features/schema-generator/GH3261.test.ts
> +  @Property({ type: 'boolean' })
```suggestion
  @Property()
```

2022-07-01 13:07 UTC, B4nan commented on tests/features/schema-generator/GH3261.test.ts
> +
```suggestion

```

2022-07-01 13:07 UTC, B4nan commented on tests/features/schema-generator/GH3261.test.ts
> +    dbName: 'GH3216',
```suggestion
    dbName: 'mikro-orm-test-gh3261',
```

2022-07-01 13:07 UTC, B4nan commented on tests/features/schema-generator/GH3261.test.ts
> +  });
`em.create` is sync method

```suggestion
  const user1 = orm.em.create(User, {
    email: 'test',
  });
  const user2 = orm.em.create(User, {
    email: 'test',
  });
```

2022-07-01 13:10 UTC, B4nan requested changes

2022-07-01 13:10 UTC, B4nan commented on packages/mongodb/src/MongoSchemaGenerator.ts
> +  async ensureIndexes(options: EnsureIndexesOptions = {}, retryLimit = 3): Promise<void> {
actually, lets not introduce another parameter, we already have the options there, so lets just add the `retryLimit` inside that
```suggestion
  async ensureIndexes(options: EnsureIndexesOptions = {}): Promise<void> {
    options.retryLimit ??= 3
```

2022-07-01 13:10 UTC, B4nan commented on packages/mongodb/src/MongoSchemaGenerator.ts
> +      await this.ensureIndexes({ retry: collectionsWithFailedIndexes }, retryLimit - 1);
```suggestion

      if (options.retryLimit === 1) {
        const failedIndexes = res.filter(r => r.status === 'rejected').map((r: Dictionary, id) => `${promises[id][0]} - ${r.reason}`);
        throw new Error(`Failed to create indexes: ${failedIndexes.join(', ')}`);
      }

      await this.ensureIndexes({
        retry: collectionsWithFailedIndexes,
        retryLimit: retryLimit - 1,
      });
```

2022-07-02 03:26 UTC, jagzmz commented on packages/mongodb/src/MongoSchemaGenerator.ts
> +  async ensureIndexes(options: EnsureIndexesOptions = {}, retryLimit = 3): Promise<void> {
Updated!

2022-07-02 03:26 UTC, jagzmz commented on packages/mongodb/src/MongoSchemaGenerator.ts
> +      await this.ensureIndexes({ retry: collectionsWithFailedIndexes }, retryLimit - 1);
Updated

2022-07-02 07:35 UTC, B4nan commented on packages/mongodb/src/MongoSchemaGenerator.ts
> +      if (options.retryLimit === 1) {
```suggestion

      if (options.retryLimit === 0) {
```

2022-07-02 07:35 UTC, B4nan commented on packages/mongodb/src/MongoSchemaGenerator.ts
> +      await this.ensureIndexes({
```suggestion

      await this.ensureIndexes({
```

2022-07-02 07:36 UTC, B4nan approved these changes

2022-07-02 07:36 UTC, merged

2022-07-02 07:37 UTC, B4nan commented
Thanks!