feat: add support for full text searches
mikro-orm/mikro-orm pull request #3317
Opened 2022-07-19 21:13 UTC by jsprw

Add a $fulltext operator that can be used in queries on SQL databases. 

Based on !621 by @thekevinbrown. This version has also added support for creating required indexes with the decorator `@Index({ type: 'fulltext' })` and full text searching in MongoDB. Documentation could possibly be improved with more clear instructions.

Closes: #620

2022-07-19 23:39 UTC, B4nan requested changes
Looking great, thanks a lot! Did a quick first pass and left some comments. Would be definitely good to describe this more in the docs, otherwise it could get lost.

2022-07-19 23:39 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +    } else if (typeof object === 'object') {
```suggestion
    }

    if (typeof object === 'object') {
```

2022-07-19 23:39 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +  static hasNestedKey(object: any, key: string): boolean {
let's not use `any`, either its object, so `Dictionary`, or `unknown`
```suggestion
  static hasNestedKey(object: Dictionary, key: string): boolean {
```

2022-07-19 23:39 UTC, B4nan commented on packages/knex/src/query/QueryBuilderHelper.ts
> +      const entityMetadata = this.metadata.get(this.entityName);
lets use just `meta`, as in the whole codebase
```suggestion
      const meta = this.metadata.get(this.entityName);
```

2022-07-19 23:39 UTC, B4nan commented on packages/knex/src/query/QueryBuilderHelper.ts
> +    if (op === '$fulltext') {
maybe this could be handled in the `getOperatorReplacement` like the other operators? just like the regexp operator

2022-07-19 23:39 UTC, B4nan commented on packages/knex/src/schema/SchemaComparator.ts
> +    if (index1.expression || index2.expression || index1.type === 'fulltext' || index2.type === 'fulltext') {
is this safe? cant we compare full text indexes in better way?

2022-07-19 23:39 UTC, B4nan commented on packages/knex/src/schema/SchemaGenerator.ts
> +        throw new Error('Full text index is only supported on one column.');
is this artificial limitation of does it work this way on database level?

2022-07-19 23:39 UTC, B4nan commented on docs/docs/query-conditions.md
> +| `$fulltext` | full text | A driver specific full text search function. Requires an FTS5 table for SQLITE and an index with type 'fulltext' for other drivers.
```suggestion
| `$fulltext` | full text       | A driver specific full text search function. Requires an FTS5 table for SQLITE and an index with type 'fulltext' for other drivers. |
```

also whats FTS5? can we add short explanation to parens maybe?

2022-07-19 23:39 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +      data['$text'] = { $search: data['$fulltext'] };
any reason for using bracket syntax? maybe better use casting if its about that, instead of bracket syntax and ignore comments - that feels less confusing i guess

2022-07-19 23:39 UTC, B4nan commented on packages/mongodb/src/MongoPlatform.ts
> +    return operator === '$not' || operator === '$fulltext';
```suggestion
    return ['$not', '$fulltext'].includes(operator);
```

2022-07-20 08:20 UTC, jsprw commented on packages/knex/src/schema/SchemaComparator.ts
> +    if (index1.expression || index2.expression || index1.type === 'fulltext' || index2.type === 'fulltext') {
i can't really compare it as the returned columnNames from the database are an expression and the two objects don't have too much overlap:

Postgres:
```
{
  "columnNames": ["to_tsvector(simple::regconfig, title::text)"],
  "composite": false,
  "keyName": "book2_title_index",
  "unique": false,
  "primary": false
}
VS
{
  "keyName": "book2_title_index",
  "columnNames": ["title"],
  "composite": false,
  "primary": false,
  "unique": false,
  "type": "fulltext",
  "expression": <undefined>
}
```

MySQL/MariaDB:

```
{
  "columnNames": ["title"],
  "keyName": "book2_title_index",
  "unique": false,
  "primary": false
}
VS
{
  "keyName": "book2_title_index",
  "columnNames": ["title"],
  "composite": false,
  "primary": false,
  "unique": false,
  "type": "fulltext",
  "expression": undefined
}
```

2022-07-20 08:27 UTC, jsprw commented on packages/knex/src/query/QueryBuilderHelper.ts
> +    if (op === '$fulltext') {
Maybe, but it's more than just replacing the operator. It executes quite different than other operators, it is not A operator B but different for the platforms, fe Postgres: to_tsvector('simple', :column:) @@ plainto_tsquery(:query)

2022-07-20 08:28 UTC, jsprw commented on packages/knex/src/schema/SchemaComparator.ts
> +    if (index1.expression || index2.expression || index1.type === 'fulltext' || index2.type === 'fulltext') {
Yes, understandable. I will also write a comment what could be done/improved for later versions.

2022-07-20 08:53 UTC, B4nan commented
It would be also great to catch up with the code coverage. But I am open for merging it without full branch coverage, will be happy to fill that gap myself afterwards.

2022-07-20 11:14 UTC, jsprw commented on packages/knex/src/schema/SchemaGenerator.ts
> +        throw new Error('Full text index is only supported on one column.');
Resolved it by allowing many columns to be used for this index, see upcoming commit. I don't know what the behaviour will be when full text searching a column which has an index that consists of multiple comments.

2022-07-20 11:29 UTC, jsprw commented on packages/mongodb/src/MongoDriver.ts
> +      data['$text'] = { $search: data['$fulltext'] };
It was quite hard to do as the copy is made to the same argument of type T. And modifying T might break something or we had to cast to unknown. I solved it by creating a new variable where copied data is stored (which is more easily casted).

2022-07-20 11:42 UTC, jsprw commented
What to do in the future:

- Add more thorough index diffing (see https://github.com/mikro-orm/mikro-orm/pull/3317#discussion_r925316081)
- Add support for passing language in the `@Index()` decorator. Right now it takes the simple approach while English or any other language might be more suitable to find more matches. (see https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-PARSING-DOCUMENTS, https://dev.mysql.com/doc/refman/8.0/en/fulltext-natural-language.html).
- Add support for ranking (see https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-RANKING, https://dev.mysql.com/doc/internals/en/full-text-search.html, https://www.mongodb.com/docs/manual/core/text-search-operators/)
- Add support for selecting text search mode (https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html)
- All drivers have a different way to set up a query (while offering the same functionality, see links in `docs/docs/query-conditions.md`). We could include typed support for constructing queries that are converted to the platform's style dynamically. Like this for `{ title: { $fulltext: { $include: ['keyword1', 'keyword2'], $exclude: ['keyword3'] } } }` or even { title: { $fulltext: { $or: [{ $include: ['keyword1', 'keyword2'], $exclude: ['keyword3'] }, { $include: ['keyword4'], $exclude: ['keyword1'] ] } } }.

Do I forget any?

2022-07-26 19:48 UTC, B4nan commented
> For the second I tried to switch the column type to 'tsvector' by doing meta.get('Book2').properties.title.columnTypes[0] = 'tsvector' running generator.getUpdateSchemaSQL() + execute() but that didn't work

Oh right, I see what's happening, unknown types will get mapped to `UnknownType` that defaults to string basically, and ignores provided `columnType`, good catch! [Fixed here](https://github.com/mikro-orm/mikro-orm/commit/f0a20fafa1425ca20f4f6fb2977eae7773d6ac6a).

2022-07-26 22:09 UTC, jsprw commented
> > For the second I tried to switch the column type to 'tsvector' by doing meta.get('Book2').properties.title.columnTypes[0] = 'tsvector' running generator.getUpdateSchemaSQL() + execute() but that didn't work
> 
> Oh right, I see what's happening, unknown types will get mapped to `UnknownType` that defaults to string basically, and ignores provided `columnType`, good catch! [Fixed here](https://github.com/mikro-orm/mikro-orm/commit/f0a20fafa1425ca20f4f6fb2977eae7773d6ac6a).

Nice, I will merge the changes and rewrite the test. Thanks!

> Btw I had to remove the default value (empty string), otherwise the query would fail. Maybe that's something to handle as well, not sure what the semantics are, never user this feature myself.

You mean the column default? I will test it now to see what you mean. I added tsvector columns with a default of empty string and it worked fine?

2022-07-30 08:26 UTC, B4nan approved these changes
Gave it another look, last piece I havent really reviewed is the docs. 

Generally looking pretty much ready to me, just few nits.

2022-07-30 08:26 UTC, B4nan commented on packages/core/src/platforms/Platform.ts
> +  /* istanbul ignore next */
i dont the ignore comments much in here, but note we test similar things in here

https://github.com/mikro-orm/mikro-orm/blob/master/tests/DatabaseDriver.test.ts

it might also be better to throw instead of provide default that is not really a good default :] (at least it looks like you override this method in each supported driver)

2022-07-30 08:26 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +  static hasNestedKey(object: Dictionary, key: string): boolean {
this sounds more accurate i guess?

```suggestion
  static hasNestedKey(object: unknown, key: string): boolean {
```

2022-07-30 08:26 UTC, B4nan commented on packages/mariadb/src/MariaDbPlatform.ts
> +    return `alter table ${this.quoteIdentifier(schemaName ? `${schemaName}.${tableName}` : tableName)} add fulltext index ${this.quoteIdentifier(indexName)}(${columns.map(c => this.quoteIdentifier(c.
lets use some temp vars so we dont have such a noodle :]

2022-07-30 08:26 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +    // copy to new variable to prevent changing the T type or doing as unkown casts
```suggestion
    // copy to new variable to prevent changing the T type or doing as unknown casts
```

2022-07-30 08:26 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +    // seach all documents where the field has a text index.
```suggestion
    // search all documents where the field has a text index.
```

2022-07-31 08:31 UTC, B4nan commented
I'd like to include this in 5.3, ideally I would ship that today evening or something like that. Let me know if you have time to finish this, I'll be happy to merge it and do the final steps myself if not, in the end its pretty much done.

2022-07-31 09:05 UTC, jsprw commented on packages/postgresql/src/types/FullTextType.ts
> +    return 'tsvector';
The column type is tsvector and not string on the db side. This custom type can be used for having a more performant full text search on postgres.

2022-07-31 09:06 UTC, jsprw commented on packages/core/src/platforms/Platform.ts
> +  /* istanbul ignore next */
Ah I see. Good suggestion.

2022-07-31 09:07 UTC, jsprw commented on packages/core/src/utils/Utils.ts
> +  static hasNestedKey(object: Dictionary, key: string): boolean {
Well hasnestedkey only works on object types. If typescript compiles with unknown, it should be fine.

2022-07-31 09:09 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +  static hasNestedKey(object: Dictionary, key: string): boolean {
It works with arrays too, you should not represent array via `Dictionary` (I know its assignable, that's not really changing anything).

2022-07-31 09:09 UTC, jsprw commented
I have applied your suggestions, I will not be home until later tonight. So if you could apply the last suggestions, that’d be great (especially if you ship it tonight). Else i can implement them around 22 or 23h.

2022-07-31 09:14 UTC, B4nan commented
Ok no worries, will do it myself if I feel like releasing today. Might as well spend some time developing other things and ship it tomorrow morning. 

Anyway, thanks a lot, nice to see a complete solution for this!

2022-07-31 18:44 UTC, jsprw commented
I am going to work on this now!

2022-07-31 19:31 UTC, jsprw commented
Implemented your suggestions, it's now awaiting tests.

2022-07-31 19:54 UTC, B4nan commented on packages/postgresql/src/types/FullTextType.ts
> +    return 'tsvector';
totally missed this comment. the thing is - `compareAsType` is used only when diffing values, if its `string/number/boolean` it will be compared by value (via `===`), otherwise it gets compared generically, which is slow(er).

2022-07-31 19:57 UTC, jsprw commented on packages/postgresql/src/types/FullTextType.ts
> +    return 'tsvector';
Oh I see - misunderstood it indeed. I have changed it, will run tests locally before pushing.

2022-07-31 20:06 UTC, B4nan commented on packages/postgresql/src/types/FullTextType.ts
> -    return 'tsvector';
we should keep the method and change the value to `string` instead, or extend the `StringType`, as right now it would default to `any` which is again generic comparison

2022-07-31 20:11 UTC, jsprw commented on packages/postgresql/src/types/FullTextType.ts
> -    return 'tsvector';
Fixed!

2022-07-31 20:25 UTC, B4nan approved these changes

2022-07-31 20:25 UTC, B4nan commented on packages/postgresql/src/types/FullTextType.ts
> +export class FullTextType extends Type<string, string> {
one last thing - lets add this type to the `types` map here too:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/types/index.ts#L30

2022-07-31 20:28 UTC, jsprw commented on packages/postgresql/src/types/FullTextType.ts
> +export class FullTextType extends Type<string, string> {
I don't think that we should do that, it would reference `@mikro-orm/postgresql` from `@mikro-orm/core`. This type should only be used in PostgreSQL as it's the only driver where you need a different type to store full text data. Could move the file to `core` with a warning or whatsoever?

2022-07-31 20:30 UTC, B4nan commented on packages/postgresql/src/types/FullTextType.ts
> +export class FullTextType extends Type<string, string> {
oh right, its pg only type

2022-07-31 20:31 UTC, merged

2022-07-31 20:32 UTC, jsprw commented on packages/postgresql/src/types/FullTextType.ts
> +export class FullTextType extends Type<string, string> {
```
import { t } from "@mikro-orm/core";
import { FullTextType } from "./FullTextType";

t.tsvector = FullTextType; // typescript error though

export { FullTextType };
```
We could add it lazily like this in `packages/postgresql/src/types/index.ts`?

2022-07-31 20:35 UTC, B4nan commented on packages/postgresql/src/types/FullTextType.ts
> +export class FullTextType extends Type<string, string> {
that wont help much i guess, lets keep it like it is and try it in the wild

2022-10-16 03:30 UTC, jagabs commented
anyone experiencing this in postgres?

<img width="374" alt="Screen Shot 2022-10-16 at 11 28 26 AM" src="https://user-images.githubusercontent.com/17292042/196016564-7a3771d6-a5b6-4aaa-a268-35c5529d8ec4.png">

for migration
   ` this.addSql('create index "tbl_employee_employee_name_index" on "public"."tbl_employee" using gin(to_tsvector(\'simple\', "employee_name"));');`

entity
` @Index({ type: "fulltext" })
  @Property({ columnType: "text", type: FullTextType })
  public employeeName: string;`
  
  i tried using this
  `@Index({ type: 'fulltext' })
  @Property({ type: FullTextType, onUpdate: (book) => book.title })
  searchableTitle!: string;`
  
  but im not sure what values to add in db migration.
  
  Thanks

2022-10-17 10:28 UTC, B4nan commented
> `@Property({ columnType: "text", type: FullTextType })`

This seems wrong, I think you should not override the column type, it needs to be `tsvector`. Note that you say you tried to drop that, but your example code is for a different property (`employeeName` vs `searchableTitle`).

> but im not sure what values to add in db migration.

I dont understand this, you are not using schema generator?

2022-10-17 11:36 UTC, jsprw commented
The tabs on the documentation site don't show correctly (https://mikro-orm.io/docs/query-conditions#postgresql). I understand the confusion.

It should show two possible ways to do FTS on Postgres. 

1. You can use a column to store full text searching metadata. Below the title and description property is duplicated to the searchable column for the fts metadata. This works the best if you have multiple properties that should be searchable by one fts query. Note that you have to use the `FullTextType` (so, columntype = tsvector) for the searchable column.

```
@Property()
  title!: string;

@Property()
  description!: string;

  @Index({ type: 'fulltext' })
  @Property({ type: FullTextType, onUpdate: (book) => book.title + ' ' + book.description })
  searchable!: string;
```

You could also use a index on an existing column. Then you can just add @Index with type `fulltext`.

```
 @Index({ type: 'fulltext' })
  @Property()
  title!: string;
```

As noted above, you use `FullTextType` and try to override the type. You should just use:

```
@Index({ type: "fulltext" }) 
@Property({ type: "text" })
public employeeName: string;
```

2022-11-27 13:41 UTC, Jedliu commented
Thank you for all your efforts. I'm using PostgreSQL. 

Is there any update for the `setweight` and advanced `constructing queries` as below?

> What to do in the future:
> 
> * Add more thorough index diffing (see [feat: add support for full text searches #3317 (comment)](https://github.com/mikro-orm/mikro-orm/pull/3317#discussion_r925316081))
> * Add support for passing language in the `@Index()` decorator. Right now it takes the simple approach while English or any other language might be more suitable to find more matches. (see https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-PARSING-DOCUMENTS, https://dev.mysql.com/doc/refman/8.0/en/fulltext-natural-language.html).
> * Add support for ranking (see https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-RANKING, https://dev.mysql.com/doc/internals/en/full-text-search.html, https://www.mongodb.com/docs/manual/core/text-search-operators/)
> * Add support for selecting text search mode (https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html)
> * All drivers have a different way to set up a query (while offering the same functionality, see links in `docs/docs/query-conditions.md`). We could include typed support for constructing queries that are converted to the platform's style dynamically. Like this for `{ title: { $fulltext: { $include: ['keyword1', 'keyword2'], $exclude: ['keyword3'] } } }` or even `{ title: { $fulltext: { $or: [{ $include: ['keyword1', 'keyword2'], $exclude: ['keyword3'] }, { $include: ['keyword4'], $exclude: ['keyword1'] ] } } }`.
> 
> Do I forget any?

2022-11-27 14:40 UTC, Jedliu commented
Btw, possible to include the highlighting function? Thank you,

2022-11-29 03:46 UTC, Jedliu commented
Just reviewed your code and found the to_tsvector was written fixed in the code [https://github.com/mikro-orm/mikro-orm/blob/8b8f14071b92e91161a32aa272315a0ecce1bc0b/packages/postgresql/src/types/FullTextType.ts#L13](FullTextType) so it's not possible to use `setweight` or change another `regconfig` (e.g `to_tsvector('english', 'your content')` or use another segment tool to preprocess the content.

Here is a code snippet which might be an option.
```typescript
@Index({ type: 'fulltext' })
@Property({
  type: FullTextType,
  nullable: true,
  onCreate: (book: Book) => `setweight(to_tsvector('english', '${book.title}'),'A') || setweight(to_tsvector('english', '${book.description}'),'B')`,
  onUpdate: (book: Book) => `setweight(to_tsvector('english', '${book.title}'),'A') || setweight(to_tsvector('english', '${book.description}'),'B')`,
})
searchableContent!: string;
```
@jsprw  Let me know your comments and see if I can help. Thanks,

2022-11-29 09:34 UTC, B4nan commented
You can create your own `FullTextType` if you don't like how it's designed, this is fully under your own control - you can as well override just the `columnType` while using it. Note that your proposed API wouldn't work, `onCreate/onUpdate` need to return runtime values, not SQL fragments.

2022-11-29 10:43 UTC, Jedliu commented
That's right. Have to update [AbstractSqlDriver.ts](https://github.com/mikro-orm/mikro-orm/blob/89b4dab31bdac52e1a6a4a281dd3bbd50b3745ec/packages/knex/src/AbstractSqlDriver.ts#L344) to make the proposed API work. 
Do you have any better suggestions for running these raw SQL fragments? Thank you,

2022-11-29 10:45 UTC, B4nan commented
As said above, create your own custom type, where you have absolute control over both the value and the SQL fragment.

https://mikro-orm.io/docs/custom-types

2022-11-29 14:09 UTC, Jedliu commented
> You can create your own `FullTextType` if you don't like how it's designed, this is fully under your own control - you can as well override just the `columnType` while using it. Note that your proposed API wouldn't work, `onCreate/onUpdate` need to return runtime values, not SQL fragments.
Thank you. I will look into this.

@jsprw your idea looks much more promising. Thanks for taking the time to do this.