Check for multiple decorator lines
mikro-orm/mikro-orm pull request #3668
Opened 2022-10-27 05:55 UTC by rstims

When upgrading from 5.4.2 to 5.5.0 I received an error saying the path of the entity couldn't be found, after find where the path is resolved, I logged out the stack from the error thrown in `Utils.lookupPathFromDecorator` and it looks like the assumption was only one line would have a decorator identifier, but mine had two as seen in the logged output below. This PR is an attempt to fix account for multiple lines or just a single. Thank you.
```
[
  'Error',
  '    at Function.lookupPathFromDecorator (/Users/rstimmler/Code/mpx-api-service/node_modules/@mikro-orm/core/utils/Utils.js:508:26)',
  '    at Function.getMetadataFromDecorator (/Users/rstimmler/Code/mpx-api-service/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:26:36)',
  '    at /Users/rstimmler/Code/mpx-api-service/node_modules/@mikro-orm/core/decorators/Entity.js:8:49',
  '    at DecorateConstructor (/Users/rstimmler/Code/mpx-api-service/node_modules/reflect-metadata/Reflect.js:541:33)',
  '    at Reflect.decorate (/Users/rstimmler/Code/mpx-api-service/node_modules/reflect-metadata/Reflect.js:130:24)',
  '    at Object.__decorate (/Users/rstimmler/Code/mpx-api-service/node_modules/tslib/tslib.js:99:96)',
  '    at Object.<anonymous> (/Users/rstimmler/Code/mpx-api-service/src/entity/requirement.ts:23:23)',
  '    at Module._compile (node:internal/modules/cjs/loader:1159:14)',
  '    at Module.m._compile (/Users/rstimmler/Code/mpx-api-service/node_modules/ts-node/src/index.ts:1618:23)',
  '    at Module.m._compile (/Users/rstimmler/Code/mpx-api-service/node_modules/ts-node/src/index.ts:1618:23)'
]
```

2022-10-31 11:32 UTC, B4nan requested changes
please add tests for this

https://github.com/mikro-orm/mikro-orm/blob/master/tests/Utils.test.ts#L286

also I'd be interested in hearing how did you end up with such stack trace :]

2022-10-31 11:32 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +      const re = stack[line].match(/\(.+\)/i)
please remove this change, its unrelated to your PR and only changes code style.

2022-10-31 11:32 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +    if (stack[line].includes('Reflect.decorate') || Utils.normalizePath(stack[line]).includes('node_modules/tslib/tslib')) {
```suggestion

    if (stack[line].includes('Reflect.decorate') || Utils.normalizePath(stack[line]).includes('node_modules/tslib/tslib')) {
```

2022-10-31 11:33 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +    if (stack[line].includes('Reflect.decorate') || Utils.normalizePath(stack[line]).includes('node_modules/tslib/tslib')) {
also please add a comment above this second `if` statement explaining why the check happens twice, this looks like a mistake in code rather than a fix

2022-10-31 15:08 UTC, rstims commented
> also I'd be interested in hearing how did you end up with such stack trace :]

I honestly have no clue. Any thing you want me to test?

2022-10-31 15:11 UTC, B4nan commented
Let's start with your tsconfig.json and ORM config, and info about how you build the app - also check if it happens only in dev mode (via ts-node) or also when running against compiled JS.

2022-10-31 16:17 UTC, rstims commented
> Let's start with your tsconfig.json and ORM config, and info about how you build the app - also check if it happens only in dev mode (via ts-node) or also when running against compiled JS.
> 
> edit: and of course provide your entity definition, maybe you are using multiple decorators on one property or something like that? but we have tests for that too...

Hmmm, wonder if using it with [Type GraphQL](https://typegraphql.com/) is causing it.... otherwise, I'll post those other things ASAP.

2022-11-05 21:54 UTC, closed without merging

2022-11-05 23:14 UTC, oxc commented
I would assume it's related to `importHelpers: true` in tsconfig.

2022-11-08 17:10 UTC, rstims commented
> I would assume it's related to `importHelpers: true` in tsconfig.

@oxc Here is what the stack looks like after making importHelpers `false`

```
'Error',
  '    at Function.lookupPathFromDecorator (/Users/rstimmler/Code/mpx-api-service/node_modules/@mikro-orm/core/utils/Utils.js:508:26)',
  '    at Function.getMetadataFromDecorator (/Users/rstimmler/Code/mpx-api-service/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:26:36)',
  '    at /Users/rstimmler/Code/mpx-api-service/node_modules/@mikro-orm/core/decorators/Entity.js:8:49',
  '    at DecorateConstructor (/Users/rstimmler/Code/mpx-api-service/node_modules/reflect-metadata/Reflect.js:541:33)',
  '    at Reflect.decorate (/Users/rstimmler/Code/mpx-api-service/node_modules/reflect-metadata/Reflect.js:130:24)',
  '    at __decorate (/Users/rstimmler/Code/mpx-api-service/src/entity/requirement.ts:5:21)',
  '    at Object.<anonymous> (/Users/rstimmler/Code/mpx-api-service/src/entity/requirement.ts:36:15)',
  '    at Module._compile (node:internal/modules/cjs/loader:1159:14)',
  '    at Module.m._compile (/Users/rstimmler/Code/mpx-api-service/node_modules/ts-node/src/index.ts:1618:23)',
  '    at Module.m._compile (/Users/rstimmler/Code/mpx-api-service/node_modules/ts-node/src/index.ts:1618:23)'
```

2022-11-08 17:16 UTC, oxc commented
Looks like the previous implementation would have caught that. I can confirm though that importHelper:true works for me in v5.5.1

@rstims, have you tried the latest releases?

2022-11-09 03:46 UTC, rstims commented
@oxc yes! Works great 🎉