fix(#3745): allow quering against parent abstract classes
mikro-orm/mikro-orm pull request #3746
Opened 2022-11-15 14:41 UTC by parisholley

2022-11-16 13:25 UTC, B4nan requested changes
i dont think this is the correct fix.

you need to distinguish a regular parent class (which will be inlined, not representing any database table) and parent class in STI (which is a valid entity on runtime, represents specific database table). your fix is affecting both, we should allow this only for the parent classes that are representing a database table.

maybe check if the entity has a `meta.tableName` or `meta.discriminatorColumn` would do it (as this is really just about the STI)

2022-11-16 13:25 UTC, B4nan commented on packages/core/src/metadata/MetadataDiscovery.ts
> +    const filtered = discovered.filter(meta => meta.name || meta.abstract);
the point of this line was to do the exact opposite. abstract === no name. now with your change it basically does `[...].filter(a => true || false)`

2022-11-16 14:18 UTC, parisholley commented
my issue is that in my modal example as pointed out in the issue, the intermediary class wouldn't have a table name or discriminator definition unless it was duplicated (which wouldn't be an intuitive solution to someone new to project). 

 > the point of this line was to do the exact opposite. abstract === no name.

perhaps instead of blindly looking for abstract, we do abstract + (any parent with name)?

2024-02-10 13:20 UTC, B4nan commented
resolved via 0c56118603c25a471a0c636912b976a4291290b3

2024-02-10 13:20 UTC, closed without merging