feat(cli): check database connection
mikro-orm/mikro-orm pull request #3875
Opened 2022-12-26 19:56 UTC by erie0210

Hi,

Even though @liang799 did his nice [PR work ](https://github.com/mikro-orm/mikro-orm/pull/3874), I tried mine, too 😹. As I knew we already have PR, I just want to get a review if it is okay. 

While working with this PR, I wanted to ask a question. Is it okay to fix existing test? As I added information to dump, it crashed with existing test. So I fixed them test but doesn't feel right.. 👀.. 

Thank you!

2022-12-27 08:20 UTC, B4nan reviewed
this one is much more in line with what i was expecting, still i believe it wont work for the same reason as the other PR - you need to connect explicitly, otherwise, it will never connect

> While working with this PR, I wanted to ask a question. Is it okay to fix existing test? 

Yeah that's totally fine, you changed behavior, so you need to adjust some assertions.

2022-12-29 01:44 UTC, erie0210 commented
@B4nan  May I ask you reviewing the fix? 🙌
Additionally, Can you recommend  other issues to try?

2022-12-31 08:00 UTC, rubiin requested changes
might also need some changes on documentation for the website

2022-12-31 09:40 UTC, B4nan commented on packages/cli/src/commands/DebugCommand.ts
> +        CLIHelper.dump(`   - ${colors.yellow('database not found')}`);
while i do understand the additional indent, i'd rather keep it on the same level as other checks, as they are also about the configuration...

also, lets improve the messages a bit, the cause might be different than db not existing. latest versions also ensure the database existing during the init phase, so unless you dont have some other problem in the config, this should never happen

```suggestion
        CLIHelper.dump(` - ${colors.green('database connection succesful')}`);
      } else {
        CLIHelper.dump(` - ${colors.yellow('database connection failed')}`);
```

2022-12-31 09:43 UTC, B4nan commented on tests/features/cli/CreateDatabaseCommand.test.ts
> +  jest.spyOn(CLIHelper, 'showHelp');
next time please dont make unrelated changes
```suggestion
const showHelpMock = jest.spyOn(CLIHelper, 'showHelp');
```

2022-12-31 09:43 UTC, B4nan commented on tests/features/cli/DebugCommand.test.ts
> +      ['   - database connected'],
```suggestion
      [' - database connection succesful'],
```

2022-12-31 09:43 UTC, B4nan commented on tests/features/cli/DebugCommand.test.ts
> +      ['   - database connected'],
```suggestion
      [' - database connection succesful'],
```

2022-12-31 09:43 UTC, B4nan commented on tests/features/cli/DebugCommand.test.ts
> +      ['   - database connected'],
```suggestion
      [' - database connection succesful'],
```

2022-12-31 09:43 UTC, B4nan commented on tests/features/cli/DebugCommand.test.ts
> +      ['   - database connected'],
```suggestion
      [' - database connection succesful'],
```

2022-12-31 09:43 UTC, B4nan commented on tests/features/cli/DebugCommand.test.ts
> +      ['   - database not found'],
```suggestion
      [' - database connection failed'],
```

2022-12-31 10:00 UTC, merged

2022-12-31 10:00 UTC, B4nan commented
Thanks!