docs: add jsdoc for property
mikro-orm/mikro-orm pull request #3918
Opened 2023-01-07 13:05 UTC by erie0210

Hi, 

I addded js-doc for `Property()`, but  I'm not sure it's what you meant in [the issue](https://github.com/mikro-orm/mikro-orm/issues/3893) Want to check if it is in line with your intention. 🫠

2023-01-07 13:11 UTC, B4nan requested changes
> BTW, some of the options of Property() are [in docs](https://mikro-orm.io/docs/decorators#property) while others like name, onCreation are not. Did you selected only some of them on purpose?

property `name` is not configurable, the one from the decorator options is an alias for `fieldName`. some things might be indeed missing like the `onCreate` callback

2023-01-07 13:11 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> + * @function
i dont think we need things like `@function` or `@template`, not inside TS, this is all inferred.

instead of this i would just add jsdoc comments above each property from the `PropertyOptions`

```ts
export type PropertyOptions<T> = {
  /** foo bar 1 */
  name?: string;
  /** foo bar 2 */
  fieldName?: string;
  ...
```

2023-01-07 13:14 UTC, erie0210 commented on packages/core/src/decorators/Property.ts
> + * @function
OMG. I got it. Let me retry 🥸

2023-01-08 10:27 UTC, B4nan requested changes

2023-01-08 10:27 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * Override default property name.
this is field name, or a column name if you want, not property name. field/column name is in the database, property name is on the entity. as said above, `PropertyOptions.name` is an alias for `fieldName`.

i would also document the plural variants - those are there as one entity property can be represented by multiple database columns - that happens for composite FKs

2023-01-08 10:27 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * 	Specify default column value for {@link https://mikro-orm.io/docs/schema-generator Schema Generator}. (SQL only)
```suggestion
   * Specify default column value for {@link https://mikro-orm.io/docs/schema-generator Schema Generator}. (SQL only)
```

2023-01-08 10:28 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    onCreate?: (entity: T) => any;
lets document those too, and also the `defaultRaw`. i hope its kind of self explanatory, let me know if i should provide some of the descriptions

2023-01-08 13:52 UTC, erie0210 commented on packages/core/src/decorators/Property.ts
>    onCreate?: (entity: T) => any;
Thanks! But before asking, I searched and found these lines from [this document](https://mikro-orm.io/docs/defining-entities#default-values). Thought it might be something close to your explanation. :)

2023-01-08 15:05 UTC, erie0210 commented on packages/core/src/decorators/Property.ts
>    onCreate?: (entity: T) => any;
I have a quick question, what does it mean by `SQL only` and how can I know?

2023-01-08 16:52 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    onCreate?: (entity: T) => any;
some of the options affect how the SchemaGenerator works, and those are SQL only, meaning they affect only SQL drivers - as in mongo there is no schema. maybe this should be explained somewhere on the top of that page.

2023-01-08 16:54 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    onCreate?: (entity: T) => any;
but speaking of the `default`, we should probably make this work with `em.create` too, as we know that will be a scalar value assignable to the entity property. as opposed to `defaultRaw` which is an SQL fragment, e.g. `now()`, or anything really, but if its a string, it needs to be quoted. that is what will be used directly in the create/alter table statement.

2023-01-09 09:41 UTC, B4nan requested changes

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * Automatically set the property value when entity gets created.
```suggestion
   * Automatically set the property value when entity gets created, executed during flush operation.
```

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * Automatically update the property value every time entity gets updated.
```suggestion
   * Automatically update the property value every time entity gets updated, executed during flush operation.
```

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * Specify default column value for {@link https://mikro-orm.io/docs/schema-generator Schema Generator}. (SQL only)
```suggestion
   * Specify default column value for {@link https://mikro-orm.io/docs/schema-generator Schema Generator}. This is a runtime value, assignable to the entity property. (SQL only)
```

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    formula?: string | ((alias: string) => string);
this one should point to https://mikro-orm.io/docs/defining-entities#formulas

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * Set column as nullable for {@link https://mikro-orm.io/docs/schema-generator Schema Generator}. (SQL only)
nowadays this flag also has an effect on how the hydration functions look like as well as some other internals (e.g. required fields validation, commit order calculation...), so its not just for SQL drivers.

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    trackChanges?: boolean;
https://mikro-orm.io/docs/unit-of-work#change-tracking-and-performance-considerations

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * Set to true to enable {@link https://mikro-orm.io/docs/transactions#concurrency-checks Concurrency Check} via concurrency fields.
i'd still call this optimistic locking. "enable concurrency check via concurrency fields" sounds weird...

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    index?: boolean | string;
this is an alternative to explicit `@Index` decorator on a property

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    check?: string | CheckCallback<T>;
https://mikro-orm.io/docs/defining-entities#check-constraints

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    lazy?: boolean;
https://mikro-orm.io/docs/defining-entities#lazy-scalar-properties

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
> +   * Specify a custom order for the column. (SQL only)
```suggestion
   * Specify a custom order based on the values. (SQL only)
```

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    extra?: string;
dumb github wont let me commet on the line 157, but that is for https://mikro-orm.io/docs/defining-entities#sql-generated-columns

2023-01-09 09:41 UTC, B4nan commented on packages/core/src/decorators/Property.ts
>    serializedName?: string;
those are about https://mikro-orm.io/docs/serializing#property-serializers

2023-01-10 13:15 UTC, erie0210 commented
I'm working on it, but a little bit busy with my work. 👾

2023-01-10 13:18 UTC, B4nan commented
No worries 👍

2023-01-13 16:28 UTC, erie0210 commented on packages/core/src/decorators/Property.ts
>    extra?: string;
haha thanks!

2023-01-13 17:36 UTC, erie0210 commented
Thanks for waiting !! 🙂 Amended PR contents based on your reviews. Added `@see + link` for the links you attached.

2023-01-14 02:57 UTC, erie0210 commented
While searching I found [property options description](https://mikro-orm.io/api/core#PropertyOptions), and there's `mysql only`. Can I ask you what it means?

2023-01-14 04:09 UTC, erie0210 commented
Added explanations for the options not mentioned above, like `precision`, `scale`, `setter/getter`, `serializedPrimaryKey` etc. I haven't used some them, so I wrote them by searching which makes me not sure about them. So it will be appreciated if you check them. 🤓 Thanks!

2023-01-19 05:53 UTC, erie0210 commented
@B4nan It would be grateful if you spare some time to check this PR.  (quick reminder in case you forgot!) 🙌

2023-01-22 21:19 UTC, B4nan approved these changes
looking good, thanks!

2023-01-22 21:19 UTC, merged