feat: implements cond parameter under Collection.loadCount
mikro-orm/mikro-orm pull request #3958
Opened 2023-01-18 17:52 UTC by manu-urba

This should close #3527.

2023-01-22 16:36 UTC, B4nan requested changes
thanks!

2023-01-22 16:36 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +  async loadCount(refresh = false, cond?: FilterQuery<T>): Promise<number> {
let's turn this into single options parameter, keep the bool form supported as well and I will remove that in v6 branch. and lets call this option `where`

2023-01-22 16:36 UTC, B4nan commented on tests/issues/GH3527.test.ts
> +import {
issue tests are for bugs/reproductions, lets put this somewhere to `tests/features`

2023-01-22 16:36 UTC, B4nan commented on tests/issues/GH3527.test.ts
> +  @OneToMany(() => Booking, booking => booking.endUser, { default: [] })
FYI that `default` option does not make much sense, its not doing anything

2023-01-22 16:36 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      const count = await em.count(this.property.type, this.createLoadCountCondition(cond ?? {} as FilterQuery<T>, pivotMeta));
this is wrongly indented

2023-01-22 16:36 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      return this._count;
```suggestion
      return this._count = this.length;
```

2023-01-22 16:36 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      const count = await em.count(this.property.type, this.createLoadCountCondition(cond ?? {} as FilterQuery<T>, pivotMeta));
and i would maybe rather keep the previous structure with the final else block, it felt more readable

2023-01-22 18:11 UTC, manu-urba commented on packages/core/src/entity/Collection.ts
> +  async loadCount(refresh = false, cond?: FilterQuery<T>): Promise<number> {
I'm not sure if you meant this:
```ts
async loadCount(options: LoadCountOptions<T> = {}): Promise<number>

export interface LoadCountOptions<T> {
  refresh?: boolean;
  where?: FilterQuery<T>;
}
```
Or this
```ts
async loadCount(refresh = false, options: LoadCountOptions<T> = {}): Promise<number>

export interface LoadCountOptions<T> {
  where?: FilterQuery<T>;
}
```

I thought the first option would be a breaking change so please let me know if it's ok now

2023-01-22 21:20 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +  async loadCount(refresh = false, options: LoadCountOptions<T> = {}): Promise<number> {
i meant something like this:
```suggestion
  async loadCount(options: LoadCountOptions<T> | boolean = {}): Promise<number> {
    options = typeof options === 'boolean' ? { refresh: options } : options;
```

2023-01-22 21:21 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +  async loadCount(refresh = false, options: LoadCountOptions<T> = {}): Promise<number> {
and i will remove the boolean variant in v6 as it will be a breaking change

2023-01-22 22:16 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +  where?: FilterQuery<T>;
refresh needs to be an option too

2023-01-22 22:17 UTC, manu-urba commented
Sorry for the confusion in these commits and force pushes, something really weird kept happening with git and husky. Everything should be done now though.

2023-01-23 10:02 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +    const refresh = typeof options === 'boolean' ? options : typeof options === 'object' ? options.refresh ?? false : false;
please do it the way i proposed, this is very overcomplicated, you dont need 3 ternaries (and nesting ternaries on its own is quite unreadable on its own)

```suggestion
    options = typeof options === 'boolean' ? { refresh: options } : options;
```

and use the `options` directly, no need to destruct anything

2023-01-23 14:39 UTC, B4nan approved these changes
two final nits and we can merge! 👍

2023-01-23 14:39 UTC, B4nan commented on packages/core/src/entity/Collection.ts
>     * The value is cached, use `refresh = true` to force reload it.
we should mention that the value is cached only if you don't provide the `where` option

2023-01-23 17:37 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      return count;
the linter is correct, we should do one final refactor - since we return from all the if/elseif branches, we dont need the else branch at all.

```ts
    }

    const count = await em.count(this.property.type, this.createLoadCountCondition(options.where ?? {} as FilterQuery<T>, pivotMeta));
    if (!options.where) {
      this._count = count;
    }

    return count;
```

2023-01-23 17:37 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +   * The value CAN'T be cached if `where` option is provided.
```suggestion
   * The value is cached (unless you use the `where` option), use `refresh = true` to force reload it.
```

2023-01-23 18:16 UTC, manu-urba commented on packages/core/src/entity/Collection.ts
> +      return count;
I made that because [you suggested it](https://github.com/mikro-orm/mikro-orm/pull/3958#discussion_r1083496060), but no worries we're reverting changes 💪🏻

2023-01-23 18:23 UTC, manu-urba commented
There you go, everything should be done now. By the way thank you for detailed review and for explaining me every single thing that wasn't right.

2023-01-23 19:19 UTC, merged