fix(mongo): move $fulltext from $and to top level
mikro-orm/mikro-orm pull request #4066
Opened 2023-02-23 10:23 UTC by funduck

Proposed solution to #4065

2023-02-25 11:17 UTC, B4nan requested changes
thanks!

2023-02-25 11:17 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +    const copiedData: T & { $fulltext?: string; $text?: { $search: string }; $and?: {$fulltext?: string}[] } = Object.assign({}, data); // copy first
this would introduce merge conficts with v6, lets do it the same [as there](https://github.com/mikro-orm/mikro-orm/blob/v6/packages/mongodb/src/MongoDriver.ts#L170) right ahead

```suggestion
    const copiedData: Dictionary = Object.assign({}, data); // copy first
```

2023-02-25 11:17 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +            throw new Error('Cannot merge multiple full text searches to top level of the query object.');
lets mention the `$fulltext` operator directly here instead of "full text searches"

2023-02-25 11:17 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +    }
can't say i like the solution, but i don't know any better right now. note that you introduced 4 levels of branching, you will need ~4 tests to cover what this does, not just one. 

also lets move this into a private method (we should do the same with the rest of the fulltext code, this method is crazy long and complex)

2023-02-26 11:30 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +            throw new Error('Cannot merge multiple full text searches to top level of the query object.');
```suggestion
            throw new Error('Cannot merge multiple $fulltext conditions to top level of the query object.');
```

2023-02-26 11:31 UTC, merged

2023-02-26 19:22 UTC, funduck commented on packages/mongodb/src/MongoDriver.ts
> +    }
Oh, I see you fixed those things by yourself. I was going to, but then started thinking about that limitation "Full text search is only supported on the top level of the query object", why is it so?
And it looks like mongodb (I checked 4.2.6 and latest) allows `$text` to appear in nested conditions. You can check it with these tests
```
  test('positive $text in nested conditions', async () => {
    const booksRepository = orm.em.getRepository(Book);
    const books = await booksRepository.find({ $or: [
      {$text: {$search: 'Bible'} },
      {title: {$regex: 'Something'} },
    ]} as unknown as FilterQuery<Book>);
    expect(books.length).toBe(1);
  })

  test('negative $text in nested conditions', async () => {
    const booksRepository = orm.em.getRepository(Book);
    const books = await booksRepository.find({ $or: [
      {$text: {$search: 'Something'} },
      {title: {$regex: 'Bible'} },
    ]} as unknown as FilterQuery<Book>);
    expect(books.length).toBe(1);
  })
```
So I thought is it really necessary to forbid `$fulltext` in nested objects?
Of course there are some limitations to use of `$text`, for example in `$or` mongo won't allow non-indexed fields together with `$text` and this kind of query will fail
```
{$or: [{$text:{$search: 'some full text request'}}, {'someNonIndexedField': 42}]}
``` 
If you think it's a good idea, I could work on that

2023-02-26 19:24 UTC, B4nan commented on packages/mongodb/src/MongoDriver.ts
> +    }
This came in as a community PR, feel free to improve it, the limitation indeed sounds quite artificial.