fix(core): infer property type from its default value if not set explicitly
mikro-orm/mikro-orm pull request #4081
Opened 2023-03-01 10:10 UTC by erie0210

Related to https://github.com/mikro-orm/mikro-orm/issues/4060

We talked about setting the type value in `initDefaultValue` before, but I think it's better to infer the type of the default value from the part that sets the type, so I implemented it this way. Can you give me some feedback on this PR?

2023-03-01 10:17 UTC, B4nan requested changes

2023-03-01 10:17 UTC, B4nan commented on tests/issues/GH4060.test.ts
> +      driver: MongoDriver,
please do not use mongo for this, it is the slowest driver to start, especially if you use replica sets (which you use here for no reason, you don't test anything transaction related)

any test that is not driver specific should prefer sqlite in-memory database as it is the fastest and does not require any cleanup.

2023-03-01 10:17 UTC, B4nan commented on tests/issues/GH4060.test.ts
> +  @Unique()
drop the indexes/uniques, that is also irrelevant

2023-03-01 10:17 UTC, B4nan commented on tests/issues/GH4060.test.ts
> +import { Entity, MikroORM, PrimaryKey, Property, Unique } from '@mikro-orm/core';
this is a new feature, the test should go to features folder (and have meaningful name), issues folder is for reproductions - the fact that this has been reported as a bug is irrelevant, it was never meant to be working before.

2023-03-01 10:17 UTC, B4nan commented on packages/core/src/metadata/EntitySchema.ts
> +    if (type === 'string' && options.default !== undefined) {
this is wrong, we dont want to override the type if it is `string`, we want to infer the value when it is not set. `string` is the default, but your code does not distinguish default property type (string) from a user-provided one (which can be also a string).

2023-03-01 10:18 UTC, B4nan commented
> We talked about setting the type value in initDefaultValue before, but I think it's better to infer the type of the default value from the part that sets the type, so I implemented it this way. Can you give me some feedback on this PR?

Why do you think it's better that way?

2023-03-01 10:21 UTC, B4nan commented
Also this should go to v6 branch, not master.

2023-03-01 10:34 UTC, erie0210 commented
> Why do you think it's better that way?

I thought it as "infering and setting type" and wondered if a typifying function would be more appropriate.

2023-03-01 10:35 UTC, B4nan commented
what is "a typifying function"? :]

2023-03-01 14:19 UTC, B4nan commented on packages/core/src/metadata/MetadataDiscovery.ts
> +    if (prop.default !== undefined && prop.type !== typeof prop.default) {
In the end I don't think this is a good idea either, the type might be already something more specific that uses string runtime values. 

Best would be to handle this in the reflect-metadata provider, as that is the place where the default string type is used when we can't infer anything.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/metadata/ReflectMetadataProvider.ts#L22-L24

Please check if it does not happen too early, e.g. before we infer the defaults from property initializers (so before this method is executed).

2023-03-01 15:01 UTC, erie0210 commented on packages/core/src/metadata/MetadataDiscovery.ts
> +    if (prop.default !== undefined && prop.type !== typeof prop.default) {
Thanks, I was looking for the part where type is set to string as the default value, I'll work on that and get back to you!

2023-03-05 16:18 UTC, B4nan commented on packages/core/src/metadata/ReflectMetadataProvider.ts
> +      if (prop.default!==undefined) {
`null` is also problematic + spacing
```suggestion
      if (prop.default != null) {
```

and i'd move this logic into the private method + rename it

2023-03-05 16:18 UTC, B4nan commented on packages/core/src/metadata/ReflectMetadataProvider.ts
> +  }
this can be greatly simplified and we should be smarter here, e.g. support at least buffers and dates - there is `UtilsgetObjectType()` you can use to get the type from such objects

```suggestion
  private getWrapperTypeObject(value: unknown): string {
    const type = Utils.getObjectType(value);
    return type === 'object' ? 'string' : type;
  }
```

please add more tests for this (can be just more properties in the test you have

2023-03-05 16:20 UTC, B4nan commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
```suggestion
  age = 0;
```

please follow this convention, there is more places with this 

and please dont rebase once you get a review, i cant see what changes you make

2023-03-05 16:42 UTC, erie0210 commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
Current lint didn't work in my environment, and it looks like adding this rule works.
Or is there other rule that should have worked?

```
"space-infix-ops": ["error", {"int32Hint": true}]
```

2023-03-05 18:04 UTC, B4nan commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
yes, but without the `int32Hint` option i guess

2023-03-05 18:08 UTC, B4nan commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
https://github.com/mikro-orm/mikro-orm/commit/428e41f8b69155cb41c1ba6ebd93358653d78ed9

2023-03-05 18:40 UTC, B4nan commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
dont forget to test this works with the inferred defaults:

```ts
  @Property()
  age = 0;
```

this needs to work too. i'd test numbers, strings, dates, buffers, booleans, and also some objects to test the fallback, as i am still not sure about that, if the default is object type, we might want to respect that and infer JSON property type

2023-03-08 01:50 UTC, erie0210 commented
Thanks for the review @B4nan 🙂. How long do you think we should do this for? I was wondering if you had a deadline in mind.

2023-03-08 09:22 UTC, B4nan commented
Not sure I follow?

2023-03-08 11:15 UTC, erie0210 commented
I asked if there was a deadline for this task, since I work a 9-6 job during the week and would only be able to work on it on the weekends! @B4nan

2023-03-08 11:23 UTC, B4nan commented
Not really, I might rebase the branch so worst case you will have some git issues, but v6 is still months ahead of us, so no rush.

2023-03-14 08:10 UTC, B4nan commented
Do you need some help with this? I keep getting notifications about rebases but I see no actual changes being made. 

FYI I will probably rebase the v6 branch during the week, as there are many new bug fixes in master. It will probably break your PR, I am kinda postponing it because of it.

2023-03-14 16:03 UTC, erie0210 commented
I understood about the rebase and its aftermath. Thanks for letting me know in advance.
Made some changes base on your review but still working on it. 
Think I won't be available until this weekend. If so, should this PR better be a draft?

2023-03-14 16:12 UTC, erie0210 commented on packages/core/src/metadata/ReflectMetadataProvider.ts
> +      if (prop.default!==undefined) {
I want to know more about `null` being problemtic and why you used `prop.default != null`? 🤓
I thought if there's no default value, `prop` won't have `default` field and will be `undefined`.
I considered using `if(!prop.default)` instead of `undefined` or `null`

2023-03-14 16:14 UTC, erie0210 commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
Sure, I will include types you mentioned. Thanks :)

2023-03-14 16:18 UTC, B4nan commented on packages/core/src/metadata/ReflectMetadataProvider.ts
> +      if (prop.default!==undefined) {
you can get `default === null` and that needs the same treatment as `undefined`, doing `!= null` will catch both `null` and `undefined`. 

you dont want `!prop.default` as that would also catch empty string or zero, both valid default values.

2023-03-17 12:32 UTC, erie0210 commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
The reflect-metadata library is not inferring the default value from the line below like ts-morph does.
```let type = Reflect.getMetadata('design:type', meta.prototype, prop.name);```
Is there a way to get default value from reflect-metadata, or do you have any idea on this?

2023-03-17 12:34 UTC, B4nan commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
The whole point of this PR is to support that, because `reflect-metadata` is not capable of that.

2023-03-17 17:52 UTC, erie0210 commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
Okay. So we have two problems. One is to infer type from `PropertyOptions`, which we can do it in `ReflectMetadataProvider`. The Other one is to infer type when assign default value with `=`. It seem a little tricky. Will it be appropriate to infer when creating `MetadataStorage.metadata`?

2023-03-17 18:03 UTC, B4nan commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
Not really, I'd say there is just one problem. I guess I will just take over if you don't mind, maybe the problem is harder than I envisioned.

2023-03-18 00:02 UTC, erie0210 commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
Okay. Thank you.

2023-03-19 13:48 UTC, B4nan commented on tests/features/schema-generator/type-infering-from-default.test.ts
> +  age=0;
It's indeed more complicated than I thought. The problem itself was rather easy (the trick is to move the `initDefaultValue` call before the metadata provider so the inference happens early, before the default string type is added), but when I started adjusting existing entities to test this there too, many tests were failing because of connected issues, like the `ref` helper not working with null values, causing constructors to fail.

2023-03-19 18:01 UTC, closed without merging