refactor(core): option to make migrator 'silent'
mikro-orm/mikro-orm pull request #4182
Opened 2023-03-29 19:40 UTC by AnimeshRy

#4124 -> This provides an option to make the migration logs silent/quiet

2023-03-29 21:39 UTC, B4nan requested changes

2023-03-29 21:39 UTC, B4nan commented on packages/migrations-mongodb/src/Migrator.ts
> +      }
bad indent

2023-03-29 21:39 UTC, B4nan commented on packages/migrations-mongodb/src/Migrator.ts
> +    if (!(this.options?.silent)) {
```suggestion
    if (!this.options.silent) {
```

2023-03-29 21:39 UTC, B4nan commented on packages/migrations/src/Migrator.ts
> +    if (!(this.options?.silent)) {
same here

2023-03-29 21:39 UTC, B4nan commented on packages/migrations-mongodb/src/Migrator.ts
>      const logger = this.config.get('logger');
this line can also go inside the if block

2023-03-30 04:54 UTC, AnimeshRy commented on packages/migrations/src/Migrator.ts
> +    if (!(this.options?.silent)) {
done

2023-03-30 04:54 UTC, AnimeshRy commented on packages/migrations-mongodb/src/Migrator.ts
>      const logger = this.config.get('logger');
done

2023-03-30 05:33 UTC, AnimeshRy commented
@B4nan Can we enforce indent with eslint aswell ? I can't find the indent setting present in the current config file

2023-03-30 06:57 UTC, merged

2023-03-30 06:58 UTC, B4nan commented
Thanks!

Feel free to send a separate PR improving the eslint config 👍