fix(core): update relationship when manually specifying PK on inverse side
mikro-orm/mikro-orm pull request #4209
Opened 2023-04-10 13:30 UTC by Anytinz

When creating an entity with many-to-one or one-to-one relationship on the inverse side, if the primary key is manually specified before flush(), the owning side's corresponding relationship definition will not be updated. This is because the manually specified primary key entity does not have a __identifier attribute, and the ChangeSetComputer.processToOne() method only adds a payload containing the updated relationship definition when the __identifier attribute is present. In this situation, if the owning side is only expected to update the relationship definition in this flush(), it will not trigger the onUpdate event, as the event relies on the changeSet, and an empty payload changeSet will not be added to the corresponding queue.

2023-04-10 14:26 UTC, B4nan requested changes
Your change is breaking 123 tests... :]

2023-04-10 14:26 UTC, B4nan commented on tests/features/unit-of-work/manual-pk-inverse-relation.test.ts
> +  orm.em.clear();
`foo` is detached entity, you need to reload it again after clearing, otherwise the whole test does not make much sense - such detached entity should be considered as new.

```suggestion
  foo = orm.em.create(Foo, {});
  await orm.em.flush();
//  orm.em.clear(); either this should be commented, or you need `em.findOne` call after it
```

2023-04-10 14:26 UTC, B4nan commented on tests/features/unit-of-work/manual-pk-inverse-relation.test.ts
> +    debug: true,
```suggestion
```

2023-04-10 14:26 UTC, B4nan commented on tests/features/unit-of-work/manual-pk-inverse-relation.test.ts
> +  orm = await MikroORM.init(defineConfig({
no need for `defineConfig` here

2023-04-10 14:26 UTC, B4nan commented on tests/features/unit-of-work/manual-pk-inverse-relation.test.ts
> +  public _id!: ObjectId;
dont use `public` modifier, its implicit

2023-04-10 14:26 UTC, B4nan commented on tests/features/unit-of-work/manual-pk-inverse-relation.test.ts
> +import { MikroORM, ObjectId, defineConfig } from '@mikro-orm/mongodb';
i would prefer sqlite with in memory database for tests that are not driver specific, as its the fastest

2023-04-10 15:51 UTC, Anytinz commented
I have made the changes based on your suggestions.

2023-04-10 15:54 UTC, Anytinz commented
> 您的更改正在打破 123 项测试... ：]

I'm sorry..... 😢

2023-04-16 07:07 UTC, Anytinz commented
Hi @B4nan , when can we merge this request?

2023-04-16 11:47 UTC, B4nan commented
As I said, this breaks many tests, so not mergable at all.

2023-04-25 20:15 UTC, closed without merging

2023-04-25 20:15 UTC, B4nan commented
So the problem was actually elsewhere, your problem was specific to using `em.create()` which uses the hydrator under the hood - and hydration did have disabled propagation of changes, or better say under hydration context the changes were considered as already saved in the database.

Fixed via 30778c35667d275bf4407a762feb1a92d91f7fe2