v6: Adding `LoggerContext` to allow for custom labels in log output
mikro-orm/mikro-orm pull request #4233
Opened 2023-04-17 22:51 UTC by SpencerKaiser

Fixes #4230

2023-04-17 23:52 UTC, SpencerKaiser commented
@B4nan I’m having a really difficult time tracking how data passes through the different abstract classes and where the context actually gets passed to `logger.logQuery`.

The changes to `AbstractSqlDriver` and `QueryBuilder` are the changes **_I_** think I need to get that data to `logQuery`, but not sure. I tried to test locally by bringing those changes into a real project but `yarn link` was seemingly breaking everything due to some strange types issue… I built the project, ran the link command from inside `core`, made sure all my other dependencies were on `58`, and successfully got it linked into my other, but I get weird type errors around `Loaded` entities: 
`Types have separate declarations of a private property 'entity'`

Any idea what I’m doing wrong there? Any suggestions on the approach?

2023-04-18 13:43 UTC, B4nan reviewed
i am usually going the old school way, compile the package and just copy paste the dist folder inside node_modules, maybe that will work? the error sounds like you have some private property with different type, maybe you need to link more packages than just core? as you did changes in knex package too

2023-04-18 15:02 UTC, SpencerKaiser commented on tests/Logger.test.ts
> +// Remove colors to allow for text matching in response
Resolved [via Slack](https://mikroorm.slack.com/archives/C053MQN67D0/p1681829077736189); keeping it as is.

2023-04-20 15:13 UTC, B4nan requested changes

2023-04-20 15:13 UTC, B4nan commented on packages/core/src/logging/Logger.ts
> +export type LoggerContext = Pick<LogContext, 'label'>;
maybe better this way so its universal way to pass params down to the logger?

```suggestion
export type LoggerContext = { label?: string } & Dictionary;
```

and add a note about that to the section about custom loggers

2023-04-20 15:13 UTC, B4nan commented on packages/knex/src/query/QueryBuilder.ts
> -    const res = await this.driver.getConnection(type).execute(query.sql, query.bindings as any[], method, this.context);
the same needs to be supported in mongo driver

2023-04-20 15:13 UTC, B4nan commented on tests/Logger.test.ts
> +        test('should print correctly without a label', () => {
bad indent (not just here, maybe we need to improve the eslint config, iirc this might be already fixed in master so maybe just rebase)

2023-04-20 15:13 UTC, B4nan commented on packages/knex/src/AbstractSqlDriver.ts
> +    );
side note: we should turn (most of) this into options object parameter in v6 (not in this PR)

2023-04-20 18:31 UTC, SpencerKaiser commented on packages/knex/src/AbstractSqlDriver.ts
> +    );
100% Agreed... I actually started down the path of doing that but didn't want to make that decision without getting your feedback and figured it would be a bigger change than the scope of this PR should be 😬

2023-04-22 10:30 UTC, B4nan commented
Will you have time to do the mongo support? We can merge without it too, I'll be happy to do it myself. 

Planning to ship v5.7 tomorrow probably, and want to rebase v6 again afterward, so would be good to merge this before instead of battling the rebases again :]

2023-04-24 22:23 UTC, SpencerKaiser commented
@B4nan sorry for the delay, I went on a mini vacation for the weekend + today; I'll work on it here shortly and/or tomorrow. I might have a question or two about it, but if I do I'll follow up in Slack for expediency! 

Re: rebasing; feel free to rebase main, just don't pull it into this branch... when that happens, I'll see the "Update branch" button and know to reset/stash/delete/recreate 😬

2023-04-25 00:55 UTC, SpencerKaiser commented on tests/Logger.test.ts
> +        test('should print correctly without a label', () => {
Fixed, but fwiw using `> Format Document` doesn't fix this, so yea, the eslint config might be a bit off

2023-04-25 00:56 UTC, SpencerKaiser commented on packages/core/src/logging/Logger.ts
> +export type LoggerContext = Pick<LogContext, 'label'>;
This change was also needed for `LogContext`... we might consider refactoring these at some point... one acts as a sort of public type where the other is more focused on internals unless someone uses `LoggerFactory`.

2023-04-25 00:57 UTC, SpencerKaiser commented on packages/core/src/logging/Logger.ts
> +export type LoggerContext = Pick<LogContext, 'label'>;
Also I personally prefer picking the `label` just to keep as much overlap as possible. If you still want that to be unique on it's own, let me know and I can fix it

2023-04-25 01:09 UTC, SpencerKaiser commented
@B4nan just added what I _**think**_ are the only changes needed for Mongo, but I'm not able to test tonight (don't have a quick repo to test against and I'm calling it for the night).

Also I made some pretty substantial changes to the logging docs because I felt they were a little all over the place after adding more so I just reorganized. Hope you like it; if not, let me know and I can revert back to the old structure but with the new content.

2023-04-25 01:10 UTC, SpencerKaiser commented on packages/knex/src/query/QueryBuilder.ts
> -    const res = await this.driver.getConnection(type).execute(query.sql, query.bindings as any[], method, this.context);
See my comment below 😬

2023-04-25 12:51 UTC, B4nan reviewed
few nits before i have time to review this fully

thanks for the docs improvements, that's amazing!

2023-04-25 12:51 UTC, B4nan commented on packages/core/src/logging/Logger.ts
> + * // [query] (user middleware) select * from user where id = 1;
this should be a codeblock i guess?

2023-04-25 12:51 UTC, B4nan commented on docs/docs/logging.md
> +### Using a custom `LoggerFactory`
keep a blank line around headings (all of them)

```suggestion
### Using a custom `LoggerFactory`

```

2023-04-25 12:51 UTC, B4nan commented on docs/docs/logging.md
> +
should be just a single blank line here

2023-04-25 13:24 UTC, SpencerKaiser commented on packages/core/src/logging/Logger.ts
> + * // [query] (user middleware) select * from user where id = 1;
I'm really not sure how to do those the proper way... the way above looks correct in VSCode: 
<img width="546" alt="image" src="https://user-images.githubusercontent.com/6445731/234290372-3f8b75b6-5094-4161-8ece-c4585f2af846.png">

And the other way (with a code block) doesn't... 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/6445731/234290444-97905d4b-77bf-4b44-9a84-3aafdfed439c.png">

Is the syntax you use a requirement for the auto-generated docs, maybe?

2023-04-25 13:25 UTC, SpencerKaiser commented on docs/docs/logging.md
> +### Using a custom `LoggerFactory`
Whoops, good catch... I had to disable my auto-formatting because what I use for other projects is _**very**_ different from yours (I don't even like mine but at least it's consistent with format-on-save haha)

2023-04-25 13:33 UTC, SpencerKaiser commented
Also re: tests, looks like they're all failing due to this error: 
```[Error: No driver specified, please fill in the `driver` option or use `defineConfig` helper (to define your ORM config) or `MikroORM` class (to call the `init` method) exported from the driver package (e.g. `import { defineConfig } from '@mikro-orm/mysql'; export defineConfig({ ... })`).]```

But I didn't change anything related to the CLI 🤔 thoughts?

2023-04-25 13:59 UTC, B4nan reviewed
the tests here are failing because you have out of sync lock file, probably because of the version change i mentioned

2023-04-25 13:59 UTC, B4nan commented on packages/core/package.json
> +  "version": "6.0.0-dev.57",
this should be reverted, same for change in knex package

2023-04-25 14:24 UTC, SpencerKaiser commented on packages/core/src/logging/Logger.ts
> + * // [query] (user middleware) select * from user where id = 1;
Ah ok sounds good!

2023-04-25 14:28 UTC, SpencerKaiser commented
Test are passing locally again! Should be ready for that through review once you have time 🙂 no rush though!

2023-04-25 21:09 UTC, B4nan commented on docs/docs/logging.md
> +We can use `loggerFactory` and use our own implementation of the `Logger` interface:
```suggestion
#### Creating a custom logger from scratch

You can use `loggerFactory` and use your own implementation of the `Logger` interface:
```

2023-04-25 21:25 UTC, B4nan approved these changes

2023-04-25 21:46 UTC, merged