fix(#4472): schema not inherited in query with relations
mikro-orm/mikro-orm pull request #4477
Opened 2023-06-22 04:12 UTC by mlusca

Fix issue error: #4472 .

When both tables have wildcard schema, join not use the correct schema.

2023-06-22 08:54 UTC, B4nan requested changes
thanks! just few nits

2023-06-22 08:54 UTC, B4nan commented on tests/issues/GH4472.test.ts
> +    orm.em.persist(topic);
you dont flush, so the database stays empty. in other words, those tree lines are not really needed, they dont do anything right now, and since you assert the actual query instead of the return value, its fine to just remove them

2023-06-22 08:54 UTC, B4nan commented on tests/issues/GH4472.test.ts
> +    await orm.em.flush();
kinda the same here, while you flush, you dont assert the return value, so this part is a bit irrelevant. 

will keep it up to you, either remove it or add assertions for the return value too

2023-06-22 08:54 UTC, B4nan commented on tests/issues/GH4472.test.ts
> +    await orm.schema.updateSchema(); // `*` schema will be ignored
```suggestion
    await orm.schema.updateSchema();
```

2023-06-22 08:54 UTC, B4nan commented on tests/issues/GH4472.test.ts
> +export class Topic {
```suggestion
class Topic {
```

2023-06-22 08:54 UTC, B4nan commented on tests/issues/GH4472.test.ts
> +export class Category {
```suggestion
class Category {
```

2023-06-23 02:38 UTC, mlusca commented
> thanks! just few nits

Thanks

2023-06-23 07:33 UTC, B4nan approved these changes

2023-06-23 14:22 UTC, merged