feat(core): add Collection.slice() method
mikro-orm/mikro-orm pull request #4608
Opened 2023-08-10 14:51 UTC by rubiin

2023-08-10 15:01 UTC, B4nan requested changes

2023-08-10 15:01 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +   * If $end is null it returns all elements from $start to the end of the Collection.
comments should be on the base class, and here you should have `@inheritDoc` tag

also there is no `$start` or `$end` parameter, its just `start` and `end`

2023-08-10 15:01 UTC, B4nan commented on tests/EntityManager.mongo.test.ts
> +    expect(book.tags.slice(0,1)).toEqual(items[0]);
formatting, same for all the other tests

```suggestion
    expect(book.tags.slice(0, 2)).toEqual(items);
    expect(book.tags.slice(1)).toEqual(items[1]);
    expect(book.tags.slice(0, 1)).toEqual(items[0]);
```

and the assertions are most probably wrong, how can you compare an array of items to the item (the second line)? you need to compare arrays with arrays, even if they have a single item in them

2023-08-10 16:08 UTC, B4nan requested changes

2023-08-10 16:08 UTC, B4nan commented on packages/core/src/entity/ArrayCollection.ts
> +    if (counter === end) { break; } // break the loop if we reach the end of the slice
```suggestion
    if (counter === end) {
      break;
    }
```

2023-08-10 16:08 UTC, B4nan commented on packages/core/src/entity/ArrayCollection.ts
> +    if (counter >= start &&  counter < end) {
```suggestion
    if (counter >= start && counter < end) {
```

we really need to make this fail in eslint, i am sure there is a rule for this

2023-08-10 16:08 UTC, B4nan commented on packages/core/src/entity/ArrayCollection.ts
> +    for (const item of this.items) {
wrong indent in the rest of this method

2023-08-10 16:08 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +  slice(start = 0, end?: number): T[]  {
no need for the default here, its enough to have it in the base method
```suggestion
  slice(start?: number, end?: number): T[]  {
```

2023-08-10 16:08 UTC, B4nan commented on tests/EntityManager.mongo.test.ts
> +    expect(book.tags.slice(1)).toEqual(items[1]);
as already said, this is wrong, you cant compare array with the item itself, should be something like following instead:

```suggestion
    expect(book.tags.slice(1)).toEqual([items[1], items[2]]);
```

2023-08-10 16:22 UTC, rubiin commented on packages/core/src/entity/ArrayCollection.ts
> +    if (counter === end) { break; } // break the loop if we reach the end of the slice
I think we should also setup prettier to run on lint stage

2023-08-10 17:28 UTC, rubiin commented
I was thinking instead of adding some minor collection methods in next pr, I will add them in here itself. What do you say

2023-08-10 17:44 UTC, B4nan commented
i'd say it should be separate PRs so it results in multiple items in the changelog

and please pay more attention to the comments, you still havent addressed all the missing spaces and wrong indents

2023-08-10 17:51 UTC, rubiin commented
I do have editorconfig extension setup and it should take care of the indentation afaik

2023-08-10 17:59 UTC, B4nan requested changes

2023-08-10 17:59 UTC, B4nan commented on packages/core/src/entity/ArrayCollection.ts
> +  }
```suggestion
  }
```

2023-08-10 17:59 UTC, B4nan commented on tests/EntityManager.mysql.test.ts
> +    expect(book.tags.slice(0,3).length).toBe(3);
this is still present all over the changes

2023-08-11 07:02 UTC, rubiin commented on tests/EntityManager.mysql.test.ts
> +    expect(book.tags.slice(0,3).length).toBe(3);
By this, did you mean the indent

2023-08-11 08:49 UTC, B4nan commented on tests/EntityManager.mysql.test.ts
> +    expect(book.tags.slice(0,3).length).toBe(3);
no, I mean the missing space, I told you about this problem 3 times already :]

2023-08-11 08:51 UTC, B4nan commented on tests/EntityManager.mysql.test.ts
> +    expect(book.tags.slice(0,3).length).toBe(3);
checked the eslint config, and we are missing this:

```
'comma-spacing': 'error',
```

so feel free to add that here to your PR and fix it via eslint, this rule should have a fixer

2023-08-11 10:30 UTC, rubiin commented on tests/EntityManager.mysql.test.ts
> +    expect(book.tags.slice(0,3).length).toBe(3);
Added and that took care of the spacing.

2023-08-11 12:55 UTC, B4nan approved these changes
all right, last few style changes. sorry for not having the linter set up properly, I hate to waste time (yours as well as mine) discussing style changes like this.

thanks!

2023-08-11 12:55 UTC, B4nan commented on .eslintrc.js
> +    'comma-spacing': 'error'
```suggestion
    'comma-spacing': 'error',
```

2023-08-11 12:55 UTC, B4nan commented on packages/core/src/entity/ArrayCollection.ts
> +      if (index === end) {
```suggestion
      if (index === end) {
```

2023-08-11 12:55 UTC, B4nan commented on tests/QueryBuilder.test.ts
> +  test('limit of 0 limits results to 0', ()=>{
hmm this is missing some spaces as well around the arrow, but that must have some eslint rule as well... damn, I though I got it set up well, but apparently I am missing some very basic rules in there.

```suggestion
  test('limit of 0 limits results to 0', () => {
```

2023-08-11 12:55 UTC, B4nan commented on tests/features/composite-keys/custom-pivot-entity.sqlite.test.ts
> +    // slice
```suggestion
    // slice
```

2023-08-11 13:37 UTC, rubiin commented
> all right, last few style changes. sorry for not having the linter set up properly, I hate to waste time (yours as well as mine) discussing style changes like this.
> 
> thanks!

No worries man. With codebase of this size, these are bound to happen.

2023-08-11 14:34 UTC, merged

2023-08-11 14:47 UTC, rubiin commented
Btw about the collections test, should I just add tests for a specific driver under `features/Collection.ts` or will the file hold for all drivers

2023-08-11 14:50 UTC, B4nan commented
We don't have to test this on all the drivers, in-memory sqlite is enough.