test: add 'features/collection' for collection related tests
mikro-orm/mikro-orm pull request #4617
Opened 2023-08-11 15:39 UTC by rubiin

Adds a separate test for collection

2023-08-12 06:15 UTC, rubiin commented
@B4nan need your input on this

2023-08-12 06:48 UTC, B4nan requested changes

2023-08-12 06:48 UTC, B4nan commented on tests/features/collection/collection.test.ts
> +  test('isConnected()', async () => {
this is unrelated copypaste

2023-08-12 06:48 UTC, B4nan commented on tests/features/collection/collection.test.ts
> +
you keep adding 2 blank lines on random places, please don't, there should be just one

2023-08-12 06:48 UTC, B4nan commented on tests/features/collection/collection.test.ts
> +    await orm.em.persist(book2);
persist is sync method

2023-08-12 06:48 UTC, B4nan commented on tests/features/collection/collection.test.ts
> +    const tagRepository = orm.em.getRepository<typeof BookTag3>(BookTag3);
if you wouldn't copy this from the JS entity test, it would be cleaner. those JS entities require such weird casting when used inside TS test

2023-08-12 06:48 UTC, B4nan commented on tests/features/collection/collection.test.ts
> +  afterAll(async () => {
this should go to the top ideally, where the other hooks are

2023-08-12 08:03 UTC, rubiin commented on tests/features/collection/collection.test.ts
> +  afterAll(async () => {
Yeah I copied most from the Sqlite test file . Will do that from another file

2023-08-12 08:21 UTC, rubiin commented on tests/features/collection/collection.test.ts
> +
Thats my IDE . Dont know why it happens. Perhaps we can add this rule https://eslint.org/docs/latest/rules/no-multiple-empty-lines

2023-08-18 09:41 UTC, B4nan commented
If this should add any value, you should extract the collection tests from the EM tests - move them, so we don't just duplicate what is already tested somewhere else.

2023-08-18 10:58 UTC, rubiin commented
> If this should add any value, you should extract the collection tests from the EM tests - move them, so we don't just duplicate what is already tested somewhere else.
> 
> And I guess I would rather do that in the v6 branch.

Yeah . I saw them on many files , one of the reason that i didnt move them out

2023-08-30 05:02 UTC, rubiin commented
Will be closing this for now and creating a new one

2023-08-30 05:02 UTC, closed without merging