feat: add cursor includeCount option
mikro-orm/mikro-orm pull request #4626
Opened 2023-08-14 05:28 UTC by bakura10

Hi !

This is my first contribution to a TypeScript project, let me know if there is anything wrong.

This PR adds the ability to opt-out for count in cursor pagination.

PS: I don't really know why the lock files are part of the PR, I did not update any dependencies:/

2023-08-14 07:24 UTC, B4nan requested changes
the lock file changes will need to go. i can see you used npm instead of yarn and you committed their lockfile too. and then I'd guess you used wrong yarn version (do you have corepack enabled?) which probably ended up with the yarn lockfile changes too.

just remove them from the git diff

2023-08-14 07:24 UTC, B4nan commented on docs/docs/entity-manager.md
remove all the line breaks

2023-08-14 07:24 UTC, B4nan commented on docs/docs/entity-manager.md
> +  totalCount: 50, // always null when `includeCount` is set to false
this should be `undefined`, not `null`
```suggestion
  totalCount: 50, // not defined when `includeCount` is set to false
```

2023-08-14 07:24 UTC, B4nan commented on docs/docs/entity-manager.md
> +  includeCount: false
```suggestion
  includeCount: false,
```

2023-08-14 07:24 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +   *   totalCount: 50, // not included if count is excluded
```suggestion
   *   totalCount: 50, // not included if `includeCount: false`
```

2023-08-14 07:24 UTC, B4nan commented on packages/core/src/utils/Cursor.ts
> +  readonly totalCount: number | null;
better to keep this optional instead of allowing `null` values
```suggestion
  readonly totalCount?: number;
```

and ideally this will be conditionally mapped so the property is not defined only when `includeCount: false`, I can take a look at that myself if you have no idea how to do that with TS

2023-08-14 07:24 UTC, B4nan commented on packages/core/src/utils/Cursor.ts
> +    this.totalCount = totalCount ?? null;
```suggestion
    this.totalCount = totalCount;
```

2023-08-14 07:24 UTC, B4nan commented on packages/core/src/utils/Cursor.ts
> +    totalCount?: number | undefined,
this is the same

```suggestion
    totalCount?: number,
```

2023-08-14 07:24 UTC, B4nan commented on tests/features/cursor-based-pagination/simple-cursor.test.ts
> +    expect(cursor1.totalCount).toBe(null);
```suggestion
    expect(cursor1.totalCount).toBeUndefined();
```

2023-08-14 07:24 UTC, B4nan commented on tests/features/cursor-based-pagination/simple-cursor.test.ts
> +    const mock = mockLogger(orm, ['query', 'query-params']);
this is not used apparently - check other tests how they assert the logged queries, you can use that to ensure only the select query is fired and no count query is there

2023-08-14 08:40 UTC, bakura10 commented on packages/core/src/utils/Cursor.ts
> +  readonly totalCount: number | null;
I will let you do that, I am not sure how to tackle this :).

2023-08-14 08:47 UTC, bakura10 commented
This should be good!

2023-08-14 08:50 UTC, bakura10 commented on tests/features/cursor-based-pagination/simple-cursor.test.ts
> -    const mock = mockLogger(orm, ['query', 'query-params']);
I have added the "toMatchSnapshot" (I've figured out this was adding extra queries in the snapshot file, so I think this is what I needed here no?

2023-08-14 08:50 UTC, B4nan approved these changes
I guess this is good to go, let's just wait for the green CI.

Thanks!

2023-08-15 05:21 UTC, bakura10 commented
I don't really understand the tests failure. When I try locally I indeed have some errors with mysql and mongo (most likely because I don't have them installed on my machine?), but SQLite works properly. However it seems that this may due to the tests not running locally, that the snapshot are not properly generated.

What is the best way to solve such issues?

2023-08-15 08:23 UTC, B4nan commented
Having the tests pass locally is the very first step. Have you followed the contributing guide? It should be just about `docker compose up` nowadays.

2023-08-16 02:08 UTC, bakura10 commented
After doing the compose up, all the tests are now passing locally! Thanks, this PR should be good to go :)

2023-08-19 15:14 UTC, rubiin reviewed
LGTM

2023-08-21 10:30 UTC, merged

2025-03-19 22:01 UTC, Nexfader commented
@B4nan Any reason it hasn't been merged into the `main` branch with `v6`? I could help port it to the upcoming `v7`

2025-03-19 22:21 UTC, B4nan commented
no idea, i guess it could get lost during a bad rebase. feel free to PR it to the master branch, i don't see why this couldn't be released in v6.

2025-03-19 22:22 UTC, B4nan commented
hmm maybe the change in the cursor class params is a bit breaking, I'll leave it up to you, either come up with a non breaking way for v6 or target v7