feat: allow to select fields for upsert
mikro-orm/mikro-orm pull request #4627
Opened 2023-08-15 06:22 UTC by bakura10

This PR attempts to solve #4602 by allowing passing specific columns on which the upsert condition is done. This allows to use entities and generate an ID server-side.

2023-08-15 08:25 UTC, B4nan reviewed
I would actually like to see this targetting the master branch, I want to do a feature release next and I wanted to take a look exactly at those upsert improvements like this one

2023-08-15 08:25 UTC, B4nan commented on packages/core/src/drivers/IDatabaseDriver.ts
> +  onConflictFields?: string[];
this should go only to the `em.upsert` options ideally, having it on this level seems confusing as it won't do anything with `em.insert()` and similar methods.

2023-08-15 08:49 UTC, B4nan requested changes
I can see there are some TS and linter errors...

2023-08-15 08:49 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +    const unique = options.onConflictFields || meta.props.filter(p => p.unique).map(p => p.name);
this could be an empty array too, would be good to have a test case for that (it might be already properly handled by existing validations)

2023-08-15 08:49 UTC, B4nan commented on tests/features/upsert/GH4602.test.ts
> +  await orm.em.upsert(User, user1, { onConflictFields: ['email'] });
test this with `upsertMany` too, those two methods need to work the same when it comes to the options

2023-08-15 08:49 UTC, B4nan commented on tests/features/upsert/GH4602.test.ts
> +test('GH issue 4602', async () => {
this file should have a better name, only bug reproductions can have a name based on issue number, not features (same for the test description)

maybe it would be best to move this into the existing suite for upsert methods, where we already test on all the drivers automatically.

2023-08-15 08:49 UTC, B4nan commented on packages/knex/src/AbstractSqlDriver.ts
> +        const uniqueFieldsContainPK = uniqueFields.filter(value => meta!.primaryKeys.includes(value)).length > 0;
I see you haven't changed anything in the mongo driver, not sure if this can have some support in mongo or we should throw in case the option is used.

2023-08-15 08:49 UTC, B4nan commented on packages/core/src/drivers/IDatabaseDriver.ts
> +  onConflictFields?: string[];
I guess we can keep this the way you have it for v5 and polish it in v6 together with the `upsert` option that has a similar problem. There should be different a interface for upsert options.

Btw this should be `keyof T` to have some intellisense, right?

2023-08-28 08:18 UTC, B4nan commented
Do you plan to work on this in the near future? I'd like to ship new feature release (from master, so this would need to be targetting that instead of v6), and wanted to have this in there as well.

Ideally, I'd ship it during this week, so will be happy to take over if you don't have time. I don't mind the proposal for `onConflictFields` and `onConflictAction`.

2023-08-28 08:19 UTC, bakura10 commented
Hi @B4nan ,

Sorry, I am on holiday for two weeks and won't be able to work on this for this week :(.

2023-08-29 23:01 UTC, B4nan commented
Closing in favor of #4669

2023-08-29 23:01 UTC, closed without merging