feat(schema multi tenancy): schema based multi tenancy support
mikro-orm/mikro-orm pull request #4717
Opened 2023-09-21 08:29 UTC by EmmEm

Hi,

I want to start with thanking you all for this great ORM that is so actively maintained and offer so many great features. One thing that really catches my eye is the per request (shell)EntityManager that I think will make this ORM a winner when it comes to multi tenancy. Almost all of the other big ORM libraries are based on a global concept. 

My aim with this PR is to make a shoot at implementing schema based multi tenancy support with help of the per request EntityManager. With this PR it's possible to set a schema when forking the EntityManager. That schema will be applied as a default schema if no other schema is present. It makes use of the schema options introduced in: https://github.com/mikro-orm/mikro-orm/pull/2296 

If this seems like an approach to pursue there is some more work to do:
- Add a hook in the other packages like Nestjs to allow for setting schema / request
- Documentation
- More extensive tests

Some questions
- Should the number of `this.context()` calls be reduced?
- When `.fork()` an existing fork with schema, should schema be inherited and should it be possible to clear schema?

2023-09-21 08:48 UTC, B4nan requested changes
i like the idea, but the implementation can simplified

2023-09-21 08:48 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +  >(entityName: EntityName<Entity>, where: FilterQuery<Entity>, _options: FindOptions<Entity, Hint> = {}): Promise<Loaded<Entity, Hint>[]> {
please dont rename the parameters, there is no need for this, you just alter the options interface but retain the type, so you can just reassign to the same `options` variable
```suggestion
  >(entityName: EntityName<Entity>, where: FilterQuery<Entity>, options: FindOptions<Entity, Hint> = {}): Promise<Loaded<Entity, Hint>[]> {
```

2023-09-21 08:48 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +    fork._schema = options.schema || em.schema;
```suggestion
    fork._schema = options.schema ?? em.schema;
```

2023-09-21 08:48 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +    let options = this.mergeOptions<FindOptions<Entity, Hint>>(_options);
i also dont think we need the `mergeOptions` method, its already a one-liner (and if we do, it cant be a public method). i would say it should be just this instead:

```suggestion
    options.schema ??= this._schema;
```

2023-09-21 09:02 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +    let options = this.mergeOptions<FindOptions<Entity, Hint>>(_options);
I agree that it doesn't need to be public, but I added the method to allow for other similar options to be applied easily. But that can be done when/if it's needed. I will implement your feedback.

2023-09-21 12:05 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +  >(entityName: EntityName<Entity>, where: FilterQuery<Entity>, _options: FindOptions<Entity, Hint> = {}): Promise<Loaded<Entity, Hint>[]> {
Resolved

2023-09-21 12:10 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +    };
I got in an racing condition error, for example in https://github.com/mikro-orm/mikro-orm/blob/master/tests/issues/GH228.test.ts with `findAndCount()`. The problem was that `count()` was able to delete `options.orderBy` before the `find()` sql was created.

2023-09-21 12:12 UTC, B4nan requested changes

2023-09-21 12:12 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +    options.schema ??= this._schema;
i'd expect this should be only in the `find` methods, not here (same for the `applyFilters`, `lockAndPopulate`, `assign`, and few others)? maybe also `create` methods

2023-09-21 12:12 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +
```suggestion
```

2023-09-21 12:16 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +    options.schema ??= this._schema;
That seems fair, the only place where it should be needed is the entry points. Then it should cascade from there. I will go trough it and check.

2023-09-21 12:59 UTC, B4nan commented on packages/core/src/unit-of-work/UnitOfWork.ts
> +    wrapped.__schema ??= this.em.schema;
i dont think those changes in UoW are needed, managed entities will have the schema already set in their state object (wrapped entity)

2023-09-21 13:26 UTC, B4nan commented on packages/core/src/unit-of-work/UnitOfWork.ts
> +    wrapped.__schema ??= this.em.schema;
actually, this method shouldn't mutate the entity state anyhow. 

do you have tests that show those changes are needed? if they are needed, we should find a better place. i'd say this should work the same as the global schema option, and since its only about inserts, it should be enough to do it here: 

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/unit-of-work/UnitOfWork.ts#L927

2023-09-22 08:50 UTC, EmmEm commented on packages/core/src/unit-of-work/UnitOfWork.ts
> +    wrapped.__schema ??= this.em.schema;
It seems to be enough to have it in `findNewEntities`. But if that is the optimal placement is up to you to decide. You know more about the repo then anyone. :)

2023-09-22 09:31 UTC, B4nan commented on packages/core/src/unit-of-work/UnitOfWork.ts
> +    wrapped.__schema ??= this.em.schema;
Ok, I guess we can keep it there, it will have a similar effect to the `uow.persist`.

2023-09-22 09:32 UTC, B4nan commented
So I guess the last missing thing is to document this somewhere? We should also come up with a better commit message as this is a bit too generic for what this PR is actually doing.

2023-09-22 12:02 UTC, EmmEm commented
I've tested some more with request context and found an issue. I think we need to change `this._schema` for `this.schema` otherwise it wont work when using request context. `this._schema` will refer to the global `EntityManager` instance which will be wrong.

2023-09-22 12:03 UTC, B4nan commented
I don't follow, change it where?

2023-09-22 12:18 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +
```suggestion
    Entity extends object,
    Hint extends string = never,
  >(entityName: EntityName<Entity>, where: FilterQuery<Entity>, options: FindOneOptions<Entity, Hint> = {}): Promise<Loaded<Entity, Hint> | null> {
    options.schema ??= this.schema;

```
If you use NestJs package and get a repo for example
```
constructor(@InjectRepository(Comment) private readonly commentRepo: EntityRepository<Comment>) {}

findComment() {
        const repoManager = this.commentRepo.getEntityManager();
        // Will set schema on the contextual EntityManager
        repoManager.schema = 'client_4';
        
       // client_4
       // Will output the contextual schema
        console.log(repoManager.schema)

       // undefined
       // Will output the schema on global entity manager
        console.log(repoManager._schema)

        // Will query against the orm schema since we use this._schema in findOne
        const comment = await this.commentRepo.findOne({
            id: 2,
        });
}
```

So I guess we need to change to use the contextual schema (`this.schema`)

2023-09-22 12:20 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +
Right, what you should do is to use the EM from context, all the methods first get that and work with it instead of using `this`.

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/EntityManager.ts#L500

No need to duplicate the `getContext` calls for this.

2023-09-22 12:29 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +
Great, that should solve the problem

2023-09-22 12:31 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +
I will try and add a test for context schema as well

2023-09-22 13:02 UTC, EmmEm commented on packages/core/src/unit-of-work/UnitOfWork.ts
> +    wrapped.__schema ??= this.em.schema;
Should we avoid spamming getContext here as well? Should we send em here or move this?

2023-09-22 13:04 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +      options.schema ??= em._schema;
no need to do it here

2023-09-22 13:05 UTC, B4nan commented on packages/core/src/EntityManager.ts
> +      options.schema ??= em._schema;
neither here

2023-09-22 13:06 UTC, EmmEm commented on packages/core/src/EntityManager.ts
> +      options.schema ??= em._schema;
true, it will be sorted in the next find

2023-09-22 13:11 UTC, B4nan commented on packages/core/src/unit-of-work/UnitOfWork.ts
> +    wrapped.__schema ??= this.em.schema;
`this.em` is already the contextual EM, so it should be safe, as it will have `useContext = false` on it and `getContext` will just return `this` right ahead.

2023-09-22 18:49 UTC, B4nan approved these changes
Unless you plan to make more changes, we can merge.

2023-09-24 16:48 UTC, B4nan commented on docs/docs/multiple-schemas.md
> +## Default schema on `EntityManager`
one more thing, i dont plan to ship any more feature releases for some time, so this will go out in a patch update - and it wont have its own docs snapshot, so please add this part to the versioned docs for v5.8 too

2023-09-24 19:44 UTC, EmmEm commented on docs/docs/multiple-schemas.md
> +## Default schema on `EntityManager`
ok, I will fix that tomorrow. Otherwise I'm happy with the changes 👍

2023-09-25 06:52 UTC, merged

2023-09-25 06:52 UTC, B4nan commented
Thanks!