fix(serialization): run custom serializer on getters
mikro-orm/mikro-orm pull request #4860
Opened 2023-10-20 20:14 UTC by ivanpondal

Fixes https://github.com/mikro-orm/mikro-orm/issues/4859

2023-10-21 09:23 UTC, B4nan commented on packages/core/src/serialization/EntitySerializer.ts
>      meta.props
we should do the same here as well, right?

2023-10-21 09:28 UTC, B4nan requested changes
two more nits

2023-10-21 09:28 UTC, B4nan commented on tests/features/serialization/GH4859.test.ts
> +export class TimeSeriesEntityTest {
no need to export things from the tests
```suggestion
class TimeSeriesEntityTest {
```

2023-10-21 09:28 UTC, B4nan commented on tests/features/serialization/GH4859.test.ts
> +import { Entity,  PrimaryKey, Property, serialize } from '@mikro-orm/core';
```suggestion
import { Entity, PrimaryKey, Property, serialize } from '@mikro-orm/core';
```

2023-10-21 09:29 UTC, B4nan commented on packages/core/src/serialization/EntitySerializer.ts
> -      .forEach(prop => ret[this.propertyName(meta, prop.name, wrapped.__platform)] = entity[prop.name]);
actually, this also needs to be addressed in the `EntityTransformer` class, which is used for implicit serialization. which reminds me i wanted to look into deduplicating this in v6, now the two classes are almost the same

2023-10-22 15:33 UTC, ivanpondal commented on packages/core/src/serialization/EntitySerializer.ts
>      meta.props
Yep, had to do some small changes. First off, added a `getterName === undefined` check to the accessor serializer. This was to avoid it being called twice (for method getters too). Then I modified the `processProperty` function so that if the property is a function (the method getter case) then it gets the corresponding value by calling the function. Let me know if I'm missing something or if you can think of a more elegant way of doing it 👍

2023-10-22 15:34 UTC, ivanpondal commented on packages/core/src/serialization/EntitySerializer.ts
> -      .forEach(prop => ret[this.propertyName(meta, prop.name, wrapped.__platform)] = entity[prop.name]);
Could you point me to some examples where `EntityTransformer` is being used as to test it accordingly? Thanks!

2023-10-22 15:37 UTC, ivanpondal commented on packages/core/src/serialization/EntitySerializer.ts
> +        return serializer((entity[prop] as unknown as () => T[keyof T & string])());
This is the same cast that was being used to [obtain the getter method value](https://github.com/mikro-orm/mikro-orm/pull/4860/files#diff-8fd27dc733983b948f557254ee3f4f004f49b7ab4188eab091b9052d90624451L105).

2023-10-22 15:38 UTC, B4nan commented on packages/core/src/serialization/EntitySerializer.ts
> -      .forEach(prop => ret[this.propertyName(meta, prop.name, wrapped.__platform)] = entity[prop.name]);
`wrap(entity).toObject()` is using it, same for `JSON.stringify(entity)`

2023-10-22 22:43 UTC, ivanpondal commented on packages/core/src/serialization/EntitySerializer.ts
> -      .forEach(prop => ret[this.propertyName(meta, prop.name, wrapped.__platform)] = entity[prop.name]);
added a test case for `wrap(entity).toObject()` 👍

2023-10-22 22:45 UTC, ivanpondal commented
Will squash commits once the pr is ready to conform with commit format.

2023-10-23 15:45 UTC, ivanpondal commented
I'm looking into the test failure. Things broke with the `EntityTransformer` changes.

2023-10-23 19:31 UTC, B4nan approved these changes
thanks!

2023-10-23 19:32 UTC, merged