Fixes Reference.load(), Collection.loadItems(), dataloader enabling logic. Dataloaders honor options and filters.
mikro-orm/mikro-orm pull request #4978
Opened 2023-11-29 21:22 UTC by darkbasic

It's mostly done and tests are passing but I'm marking this as draft until I add more tests for filters and options with the Collection dataloader.

2023-11-30 10:05 UTC, darkbasic commented
It's ready for review. Please don't squash the commits when you merge it because I'd like to keep track of all the changes if something breaks. I've tested it against my project as well and the suite passes.

2023-11-30 17:20 UTC, B4nan reviewed
thanks, left few initial comments

2023-11-30 17:20 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      ? [...(options.populate.includes('*') ? Object.keys(this.property.targetMeta!.properties) : options.populate)].map(f => `${this.property.name}.${f}`)
This looks wrong, the star needs to work recursively and you are only expanding one level here.

The idea was that we pass down the star and it's gonna be handled in the EntityLoader. So it should be rather this:

```suggestion
      ? options.populate.map(f => f === '*' ? f : `${this.property.name}.${f}`)
```

2023-11-30 17:41 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      const items: TT[] = await this.getEntityManager().colLoader.load([this, {
Got it, I thought the `load` method is our own implementation.

2023-11-30 17:46 UTC, darkbasic commented on packages/core/src/entity/Collection.ts
> +        ...(options?.logging && { logging: options?.logging }),
Just making sure we don't pass unneeded properties, for example dataloader.
Wouldn't hurt anyway because we don't support dataloader in find queries yet, but mostly I hate the fact that Typescript's structural subtyping allows you to pass additional properties like `dataloader` despite option's type is specifically `Omit<InitOptions<any, any>, 'dataloader'>`. We can safely pass options as is I guess.

2023-11-30 17:54 UTC, darkbasic commented on packages/core/src/entity/Collection.ts
> +      ? [...(options.populate.includes('*') ? Object.keys(this.property.targetMeta!.properties) : options.populate)].map(f => `${this.property.name}.${f}`)
I've tried your suggestion but `await Promise.all(colsA.map(col => col.loadItems({ populate: [ '*' ] })));` times out.

2023-11-30 17:56 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      ? [...(options.populate.includes('*') ? Object.keys(this.property.targetMeta!.properties) : options.populate)].map(f => `${this.property.name}.${f}`)
Yes, because there is some bug in there, I saw this in another test just a few days ago. But it's the correct way of doing this.

2023-11-30 18:19 UTC, B4nan commented on packages/core/src/entity/WrappedEntity.ts
> +    await this.__em.findOne(this.entity.constructor.name, this.entity, { filters: false, refresh: true, lockMode, populate, connectionType, schema: this.__schema });
>  If you don't ignore filters you won't have loaded the reference:

Yes, and that is correct behavior, as it is not valid with current default filters. Your change would break one of the main use cases for filters - soft deletes. 

> I expect to be able to load references anyway,

You can, by disabling filters - explicitly.

2023-11-30 18:42 UTC, darkbasic commented on packages/core/src/entity/WrappedEntity.ts
> +    await this.__em.findOne(this.entity.constructor.name, this.entity, { filters: false, refresh: true, lockMode, populate, connectionType, schema: this.__schema });
> Your change would break one of the main use cases for filters - soft deletes.

If that's a desired feature it should return null/undefined rather than keep returning the id, like if the property was nullable. Otherwise if find it rather confusing.
There should also be a way to disable the filters and to customize them, like `Collection.loadItems` does (but currently there is no `where` option for `Reference.load`.
Also would be nice to have an option to globally disable default filters on References and/or Collections.
Niche bonus: the collection/reference should have a property storing the combination of filters which have been used to load it.

2023-12-02 12:08 UTC, darkbasic commented on packages/core/src/entity/WrappedEntity.ts
> +    await this.__em.findOne(this.entity.constructor.name, this.entity, { filters: false, refresh: true, lockMode, populate, connectionType, schema: this.__schema });
I've removed the commit which disables default filters for References. I'll update the bug report later today.

2023-12-10 13:43 UTC, darkbasic commented on packages/core/src/entity/Collection.ts
> +      ? [...(options.populate.includes('*') ? Object.keys(this.property.targetMeta!.properties) : options.populate)].map(f => `${this.property.name}.${f}`)
Rebased against https://github.com/mikro-orm/mikro-orm/pull/5001

2023-12-10 14:19 UTC, B4nan requested changes
can we also add the `filters` option to both `InitOptions` and `LoadReferenceOptions`? that way users can disable default filters or enable the opt-in ones (and provide arguments to them), that seems to be the last missing thing

2023-12-10 14:19 UTC, B4nan commented on packages/core/src/entity/Reference.ts
> +  async load<TT extends T, K extends keyof T = never, P extends string = never>(options?: LoadReferenceOptions<T, P> | K, dataloader?: boolean): Promise<Loaded<TT, P> | T[K]> {
what's the reason for the additional parameter? we already have such option, if we need some kind of override (which i still dont really think, how would it be different than overriding the already existing option), i'd rather see it as yet another option instead of a separate parameter, the signature this way feels weird

2023-12-10 14:19 UTC, B4nan commented on packages/core/src/entity/Reference.ts
> +          ...(opts?.connectionType && { populate: opts?.connectionType }),
this is not needed, right? lets pass whole options object

2023-12-10 14:19 UTC, B4nan commented on packages/core/src/utils/DataloaderUtils.ts
> +         In real world scenarios (GraphQL) msot of the times you will end up batching the same sets of options anyway,
```suggestion
         In real-world scenarios (GraphQL) most of the time you will end up batching the same sets of options anyway,
```

2023-12-10 14:19 UTC, B4nan commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
can we resolve this? sounds rather easy

2023-12-10 14:19 UTC, B4nan commented on packages/core/src/utils/DataloaderUtils.ts
> +          ...(opts?.logging && { logging: opts?.logging }),
same here, iirc we removed it from one place already and it just stayed here and there, or is it needed? does it have effect on the map keys if we keep everything? if thats the reason, it sounds better to introduce a helper to compute a key out of all options, which will only respect those we can about

2023-12-10 14:19 UTC, B4nan commented on packages/core/src/utils/DataloaderUtils.ts
> +            prop => em.getMetadata().get(className).properties[prop]?.ref !== true)] as any,
```suggestion
            prop => em.getMetadata(className).properties[prop]?.ref !== true)] as any,
```

2023-12-10 14:45 UTC, darkbasic commented on packages/core/src/entity/Reference.ts
> +  async load<TT extends T, K extends keyof T = never, P extends string = never>(options?: LoadReferenceOptions<T, P> | K, dataloader?: boolean): Promise<Loaded<TT, P> | T[K]> {
I's because of this overload: `async load<K extends keyof T>(prop: K, dataloader?: boolean): Promise<T[K]>;`
Previously there was no way to pass options when you picked a specific `prop`, so I had to add an additional second parameter to allow enabling/disabling the dataloader.

2023-12-10 14:51 UTC, darkbasic commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
Should be a matter of adding `:ref` to the populate array right? I didn't do so because there were issues with populate so I wanted the dust to settle before doing so.

2023-12-10 14:51 UTC, darkbasic commented on packages/core/src/entity/Reference.ts
> +          ...(opts?.connectionType && { populate: opts?.connectionType }),
No it's not needed: I removed it from Collection but forgot to do so from Reference as well.

2023-12-10 14:59 UTC, darkbasic commented on packages/core/src/utils/DataloaderUtils.ts
> +          ...(opts?.logging && { logging: opts?.logging }),
Yeah we can pass opts directly, we just need to make sure to do so **before** specifying the custom populate.

2023-12-10 15:10 UTC, B4nan commented on packages/core/src/entity/Reference.ts
> +  async load<TT extends T, K extends keyof T = never, P extends string = never>(options?: LoadReferenceOptions<T, P> | K, dataloader?: boolean): Promise<Loaded<TT, P> | T[K]> {
I was actually thinking about removing this signature to simplify how it works, wdyt about that? The `Collection` class also has `load` method which only takes options, I wanted to align this in v6.

We could introduce a new method for this instead, e.g. `loadProperty` (as we already have `getProperty` which returns without checking the state).

Alternatively, we could add `options` parameter to the property getter overload, as it should be there as well, that feels like an omission.

2023-12-10 15:14 UTC, B4nan commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
is there actually something to fix? i mean, the `:ref` should be already added by user in `options.populate`, why would it require some additional handling?

2023-12-10 15:14 UTC, B4nan commented on tests/issues/GH4977.test.ts
> +import { mockLogger } from '../helpers';
this is also not used :]

2023-12-11 09:06 UTC, darkbasic commented on tests/issues/GH4977.test.ts
> +import { mockLogger } from '../helpers';
I'm pretty sure there is an issue with your eslint/prettier config at this point because I'm certain that lint-staged did run after amending the commit yet it didn't remove it. I'll remove the unused import manually.

2023-12-11 09:18 UTC, B4nan commented on tests/issues/GH4977.test.ts
> +import { mockLogger } from '../helpers';
There is no issue, those rules are simply disabled in the tests as more often than not, it's fine to have some statement that does something and never use its value (e.g. because you assert the queries made by the ORM).

2023-12-11 10:05 UTC, darkbasic commented on tests/issues/GH4977.test.ts
> +import { mockLogger } from '../helpers';
I agree for statements that don't use its value, but what's the utility of unused imports?

2023-12-11 10:39 UTC, B4nan commented on tests/issues/GH4977.test.ts
> +import { mockLogger } from '../helpers';
Looks more like we don't have a lint rule for this at all.

2023-12-12 13:53 UTC, darkbasic commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
@B4nan `find` doesn't have a `ref` property in its options while `loadItems` does, so it won't work without additional handling. I guess that conditionally adding `:ref` to the populate array every time `loadItems` has the `ref` property set should do the trick.

2023-12-12 13:57 UTC, darkbasic commented on packages/core/src/entity/Reference.ts
> +  async load<TT extends T, K extends keyof T = never, P extends string = never>(options?: LoadReferenceOptions<T, P> | K, dataloader?: boolean): Promise<Loaded<TT, P> | T[K]> {
@B4nan yes we should simplify the signature if possible: either `loadProperty` or an additional `options` param or both.
I suggest making a separate PR for this together with the `InitOptions`/`LoadReferenceOptions` `filters` option so that we can merge this, release a new alpha and start testing it in my app.

2023-12-12 14:13 UTC, darkbasic commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
![image](https://github.com/mikro-orm/mikro-orm/assets/1047358/2c0ff9e5-c106-43f0-8295-2a988dca916c)
Are you suggesting that we should get rid of the `ref` prop in `InitOptions`?

2023-12-12 14:18 UTC, B4nan commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
no, thats for collections, i am saying that the option (nor `:ref` populate hints) make sense for M:1 and 1:1 relations, that's what i am referring to as owning sides. collections are technically always inverse sides (m:n have a concept of owning side but technically it is not, the owning sides are the m:1 relations in pivot entity)

2023-12-12 14:20 UTC, B4nan commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
i guess i just confused myself, i thought you are talking about the reference wrapper (and therefore about m:1/1:1 relations)

2023-12-12 14:31 UTC, darkbasic commented on packages/core/src/utils/DataloaderUtils.ts
> +          // FIXME: loadItems "ref" option must be taken into consideration as well
Good, so if the proposed fix is fine I think this is ready to be merged and I will open a new PR filters and loadProperty.

2023-12-12 16:05 UTC, merged

2023-12-12 16:06 UTC, B4nan commented
lets improve in another PR, this is indeed too huge already. 

(and of course, thanks a lot!)