fix(postgres): parse timestamp dates less than year 1000
mikro-orm/mikro-orm pull request #5071
Opened 2024-01-04 17:13 UTC by Robert-Schirmer

### Bug
Parsing a timestamp column in postgresql with a date less than year 1000 will create an invalid Date when using the `forceUtcTimezone` set to `true`.
### Reproduction
Created test for reproduction, run without the fix to `PostgresSqlConnection.ts`.
### Fix
Use the date parsing function from `postgres-date` that is used by default in `pg` for parsing dates but add the `Z` to force the utc timezone. `new Date('0022-01-01 09:17:58.000Z')` when parsing the timestamp column str creates an invalid date in js.

2024-01-04 17:26 UTC, B4nan commented
please target master branch, then once we merge, we can cherry pick to 5.x

2024-01-04 17:29 UTC, Robert-Schirmer commented
> please target master branch, then once we merge, we can cherry pick to 5.x

Thats what I originally wanted to do but there seems to be a refractor of the `PostgreSqlConnection` in `master`, it will require two different fixes. How do you want to do that?

2024-01-04 17:30 UTC, B4nan requested changes
few notes about the test

2024-01-04 17:32 UTC, B4nan commented
> Thats what I originally wanted to do but there seems to be a refractor of the PostgreSqlConnection in master, it will require two different fixes. How do you want to do that?

Then I'd like to first see a PR for master/v6, keep this one targeting v5. Once we have it fixed in v6, we can merge this one, but I don't want to fix things only here.

2024-01-04 17:34 UTC, B4nan commented
Btw, just curious, what kind of dates are you storing that you've hit this? :]

2024-01-05 16:51 UTC, B4nan commented
gave this a closer look, and its not just about postgres, neither it is about year 1000, just about some particular years close to 0. looks like its enough to add `T` into the datetime string instead of the space to fix this. fixing this in v6 is actually much easier than v5, as date parsing happens on a single place for all drivers. since nobody else asked about this, i am fine with merging this in for v5, and keeping the proper fix to all drivers in v6 only

2024-01-05 22:56 UTC, merged