fix: embeddable hydration of non persistent properties
mikro-orm/mikro-orm pull request #5579
Opened 2024-05-15 16:41 UTC by toonvanstrijp

Closes #5578

2024-05-15 16:44 UTC, B4nan requested changes
please add a test case so its clear what you are fixing and to confirm your changes actually resolves it

2024-05-15 16:44 UTC, toonvanstrijp commented
> please add a test case so its clear what you are fixing and to confirm your changes actually resolves it

Will do as soon as I can :)

2024-05-15 16:55 UTC, B4nan commented on packages/core/src/hydration/ObjectHydrator.ts
> +      if (prop.getter && !prop.setter) {
why is that? feels like a breaking change to me, i think we do support having a getter only and it can be persisted to the database (i think the persistence needs is opt-in).

2024-05-15 17:56 UTC, toonvanstrijp commented on packages/core/src/hydration/ObjectHydrator.ts
> +      if (prop.getter && !prop.setter) {
@B4nan If I don't do this I'm getting the following errors: 
```
 FAIL  tests/features/virtual-entities/virtual-entities.postgres.test.ts
  ● virtual entities (sqlite) › with SQL expression

    TypeError: Cannot set property fooBar of #<Identity> which has only a getter

      at eval (eval at createFunction (packages/core/src/utils/Utils.ts:1114:14), <anonymous>:58:30)
      at Function.callCompiledFunction (packages/core/src/utils/Utils.ts:1125:14)
      at ObjectHydrator.hydrate (packages/core/src/hydration/ObjectHydrator.ts:29:11)
      at EntityFactory.hydrate (packages/core/src/entity/EntityFactory.ts:316:21)
      at EntityFactory.create (packages/core/src/entity/EntityFactory.ts:72:12)
      at SqlEntityManager.find (packages/core/src/EntityManager.ts:251:39)
          at async Promise.all (index 0)
      at SqlEntityManager.findAndCount (packages/core/src/EntityManager.ts:569:31)
      at Object.<anonymous> (tests/features/virtual-entities/virtual-entities.postgres.test.ts:108:31)

  ● virtual entities (sqlite) › with callback

    TypeError: Cannot set property fooBar of #<Identity> which has only a getter

      at eval (eval at createFunction (packages/core/src/utils/Utils.ts:1114:14), <anonymous>:251:30)
      at Function.callCompiledFunction (packages/core/src/utils/Utils.ts:1125:14)
      at ObjectHydrator.hydrate (packages/core/src/hydration/ObjectHydrator.ts:29:11)
      at EntityFactory.hydrate (packages/core/src/entity/EntityFactory.ts:316:21)
      at EntityFactory.mergeData (packages/core/src/entity/EntityFactory.ts:179:10)
      at EntityFactory.create (packages/core/src/entity/EntityFactory.ts:87:12)
      at SqlEntityManager.find (packages/core/src/EntityManager.ts:251:39)
      at EntityLoader.findChildren (packages/core/src/entity/EntityLoader.ts:388:19)
      at EntityLoader.populateMany (packages/core/src/entity/EntityLoader.ts:261:18)
      at EntityLoader.populateField (packages/core/src/entity/EntityLoader.ts:427:23)
      at EntityLoader.populate (packages/core/src/entity/EntityLoader.ts:101:7)
      at SqlEntityManager.find (packages/core/src/EntityManager.ts:262:5)
          at async Promise.all (index 0)
      at SqlEntityManager.findAndCount (packages/core/src/EntityManager.ts:569:31)
      at Object.<anonymous> (tests/features/virtual-entities/virtual-entities.postgres.test.ts:185:28)

  ● virtual entities (sqlite) › em.populate

    TypeError: Cannot set property fooBar of #<Identity> which has only a getter

      at eval (eval at createFunction (packages/core/src/utils/Utils.ts:1114:14), <anonymous>:251:30)
      at Function.callCompiledFunction (packages/core/src/utils/Utils.ts:1125:14)
      at ObjectHydrator.hydrate (packages/core/src/hydration/ObjectHydrator.ts:29:11)
      at EntityFactory.hydrate (packages/core/src/entity/EntityFactory.ts:316:21)
      at EntityFactory.mergeData (packages/core/src/entity/EntityFactory.ts:179:10)
      at EntityFactory.create (packages/core/src/entity/EntityFactory.ts:87:12)
      at SqlEntityManager.find (packages/core/src/EntityManager.ts:251:39)
      at EntityLoader.findChildren (packages/core/src/entity/EntityLoader.ts:388:19)
      at EntityLoader.populateMany (packages/core/src/entity/EntityLoader.ts:261:18)
      at EntityLoader.populateField (packages/core/src/entity/EntityLoader.ts:427:23)
      at EntityLoader.populate (packages/core/src/entity/EntityLoader.ts:101:7)
      at SqlEntityManager.populate (packages/core/src/EntityManager.ts:1831:5)
      at Object.<anonymous> (tests/features/virtual-entities/virtual-entities.postgres.test.ts:332:5)

 FAIL  tests/features/virtual-entities/virtual-entities.sqlite.test.ts
  ● virtual entities (sqlite) › with SQL expression

    TypeError: Cannot set property fooBar of #<Identity> which has only a getter

      at eval (eval at createFunction (packages/core/src/utils/Utils.ts:1114:14), <anonymous>:52:30)
      at Function.callCompiledFunction (packages/core/src/utils/Utils.ts:1125:14)
      at ObjectHydrator.hydrate (packages/core/src/hydration/ObjectHydrator.ts:29:11)
      at EntityFactory.hydrate (packages/core/src/entity/EntityFactory.ts:316:21)
      at EntityFactory.create (packages/core/src/entity/EntityFactory.ts:72:12)
      at SqlEntityManager.find (packages/core/src/EntityManager.ts:251:39)
          at async Promise.all (index 0)
      at SqlEntityManager.findAndCount (packages/core/src/EntityManager.ts:569:31)
      at Object.<anonymous> (tests/features/virtual-entities/virtual-entities.sqlite.test.ts:144:31)
```

Maybe the hydration should handle this differently?

2024-05-20 21:14 UTC, B4nan approved these changes

2024-05-20 21:14 UTC, B4nan commented on tests/features/embeddables/embeddable-custom-types.postgres.test.ts
> +    }
```suggestion
  @Property({ type: DoubleType })
  total: number;

  @Property({ type: DoubleType, persist: true })
  views!: number;

  constructor(total: number) {
    this.total = total;
  }
```

2024-05-20 21:14 UTC, B4nan commented on tests/features/embeddables/__snapshots__/embeddable-custom-types.postgres.test.ts.snap
> +create table "user" ("id" serial primary key, "savings_amount" numeric(14,2) not null, "views" double precision null, "after" int null);
I believe we agreed the `persist: true` would be overridden, and in such case there cant be any column. But on a second thought I guess it makes sense to leave it like this.

2024-05-20 21:54 UTC, merged