Improve grammar and typos of docs
mikro-orm/mikro-orm pull request #5888
Opened 2024-08-01 17:09 UTC by sergioalmela

Docs of the latest version revised to improve English grammar and fix typos

2024-08-01 20:08 UTC, B4nan requested changes
thanks, but please make all those changes to the next version too, you only modified the v6.3 snapshot

2024-08-01 20:08 UTC, B4nan commented on docs/versioned_docs/version-6.3/defining-entities.md
> +1. Use runtime default value of the property. This approach should be preferred as long as we are not using any native database function like `now()`. With this approach our entities will have the de
```suggestion
1. Use runtime default value of the property. This approach should be preferred as long as we are not using any native database function like `now()`. With this approach our entities will have the default value set even before it is actually persisted into the database (e.g. when we instantiate new entity via `new Author()` or `em.create(Author, { ... })`).
```

2024-08-01 20:12 UTC, B4nan commented on docs/versioned_docs/version-6.3/deployment.md
> +In following example [`require.context`](https://webpack.js.org/guides/dependency-management/#requirecontext) is used. This 'function' is only usable during the building process from Webpack so there
this sounds weird, maybe better to remove `so` instead of `therefore`?

2024-08-01 20:13 UTC, B4nan commented on docs/versioned_docs/version-6.3/filters.md
> +Since v6, filters are applied to the relations too, as part of `JOIN ON` condition. If a filter exists on an M:1 or 1:1 relation target, such an entity will be automatically joined, and when the fore
to me this reads as `on a many to one`, i hope nobody reads `m:1` as `em to one`

```suggestion
Since v6, filters are applied to the relations too, as part of `JOIN ON` condition. If a filter exists on a M:1 or 1:1 relation target, such an entity will be automatically joined, and when the foreign key is defined as `NOT NULL`, it will result in an `INNER JOIN` rather than `LEFT JOIN`. This is especially important for implementing soft deletes via filters, as the foreign key might point to a soft-deleted entity. When this happens, the automatic `INNER JOIN` will result in such a record not being returned at all. You can disable this behavior via `autoJoinRefsForFilters` ORM option.
```

2024-08-01 20:15 UTC, B4nan commented on docs/versioned_docs/version-6.3/inheritance-mapping.md
> +The `discriminatorColumn` specifies the name of the special column that will be used to define what type of class a given row should be represented with. It will be defined automatically for us, and
```suggestion
The `discriminatorColumn` specifies the name of a special column that will be used to define what type of class a given row should be represented with. It will be defined automatically for us, and it will stay hidden (it won't be hydrated as a regular property).
```

2024-08-01 20:15 UTC, sergioalmela commented
> thanks, but please make all those changes to the next version too, you only modified the v6.3 snapshot

Where is the next folder?

2024-08-01 20:19 UTC, B4nan requested changes
found few more weird things. i guess you ran this through Grammarly, right? most of the places were indeed worth improving, i just feel like you picked the first suggestion and that's not always the correct one. 

not a native speaker myself, so all of my comments are up for a discussion 🙃

2024-08-01 20:19 UTC, B4nan commented on docs/versioned_docs/version-6.3/relationships.md
> +There are multiple ways how to define the relationship, all following is equivalent:
this feels wrong to me, if something, i would add a definite article

```suggestion
There are multiple ways how to define the relationship, all of the following is equivalent:
```

2024-08-01 20:19 UTC, B4nan commented on docs/versioned_docs/version-6.3/relationships.md
> +Again, all following is equivalent:
same

2024-08-01 20:19 UTC, B4nan commented
> Where is the next folder?

in the root https://github.com/mikro-orm/mikro-orm/tree/master/docs

2024-08-02 07:36 UTC, sergioalmela commented
@B4nan Hi, just checked all changes again, with more natural meaning :)

2024-08-02 08:11 UTC, B4nan commented
gave it a quick look and i dont see anything wrong right now, so lets port the changes to the next docs

2024-08-02 13:31 UTC, sergioalmela commented
> docs

Done :)

2024-08-02 13:34 UTC, B4nan approved these changes

2024-08-02 13:46 UTC, merged