refactor(schema): move increment related changes to `MySqlSchemaHelper`
mikro-orm/mikro-orm pull request #6098
Opened 2024-10-02 07:10 UTC by lsh4711

2024-10-02 07:25 UTC, B4nan requested changes
lets add the test case from #6095 here

2024-10-02 07:25 UTC, B4nan commented on packages/knex/src/dialects/mysql/MySqlColumnCompiler.ts
> +import type { MySqlIncrementOptions } from '../..//typings';
```suggestion
import type { MySqlIncrementOptions } from '../../typings';
```

2024-10-02 07:25 UTC, B4nan commented on tests/features/embeddables/GH5847.test.ts
> +  readonly id!: string;
why this change?

2024-10-02 08:23 UTC, lsh4711 commented on tests/features/embeddables/GH5847.test.ts
> +  readonly id!: string;
This part was the code before the changes, and the tests were passing.
I was curious why no error occurred when `autoIncrement` was `true` for a string type without explicitly specifying the `type`, but the existing `SchemaHelper` works with both `string` and `bigint` types, and the tests pass as well.
Based on your suggestion, I can change it to `number` or` bigint`, as this is indeed the correct way to use it. :)

2024-10-02 08:26 UTC, B4nan commented on tests/features/embeddables/GH5847.test.ts
> +  readonly id!: string;
i was just curious, all of those variants should work.

2024-10-02 09:43 UTC, B4nan commented on tests/issues/GH6095.test.ts
> +test('6095', async () => {
lets also test this is not producing extra schema diffs. just check if `orm.schema.getUpdateSchemaSQL()` returns empty string.

2024-10-02 10:03 UTC, B4nan commented on tests/issues/GH6095.test.ts
> +  expect(sql).toMatchSnapshot();
again, lets not use snapshots for this, checking empty strings with snapshots make no sense

2024-10-02 10:03 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
seeing this, it sounds like my hunch was right :D

2024-10-02 10:07 UTC, lsh4711 commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
In SQLite, getUpdateSchemaSQL() always generates SQL in a way that replaces the existing table,
so I used a snapshot to verify if the format is correct in createTable.
I'm not sure if this is the appropriate method 😢

2024-10-02 10:18 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
there should be no diff if the schema is up to date, we have many tests checking that. so if you always see something generated, it means the changes are not correct.

2024-10-02 10:19 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
maybe its again caused by the driver mismatch, since the test is using pg specific types which are only recognized by the pg platform, but it uses sqlite platform instead

2024-10-02 10:35 UTC, lsh4711 commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
There seems to be a misunderstanding.. 😢 
I checked your suggestion before using createSchemaSQL() and tried using createUpdateSQL(),
but as you can see from https://github.com/mikro-orm/mikro-orm/commit/56f11810076d3f5ea8d319075090140f220940be, a DDL for creating a new schema was generated.

And, I just checked again, and even in version 6.3.10, entities other than the number type or { type: 'Integer' } are generating DDLs for creating new tables instead of an empty diff.

Could this be a bug?

2024-10-02 10:40 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
what should be happening behind the scenes:
- you use sqlite platform, so the column types should be resolved based on that
- diffing works based on the column types
- sqlite uses TEXT for pretty much everything which is not a number, so this should result in comparing TEXT with TEXT or NUMBER with NUMBER
- no diffs should be produced

i can have a closer look to see whats happening, i would only consider this as a bug if it happens with the platform that knows those types, using sqlite for other types is an option for tests, but its not relevant that we produce extra diffs there. its important not to produce those for your actual database/when using from the CLI, e.g. for migrations

2024-10-02 10:41 UTC, lsh4711 commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
With the PostgreSQL driver, an empty diff is generated, meaning it works correctly, and an empty diff, as expected, also appears with MySQL.
It seems that only with SQLite, when trying to use types other than integer, a new schema is being created.

2024-10-02 10:50 UTC, lsh4711 commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Exactly, in the above test, PostgreSQL works correctly with both default entities and custom entities using varchar type and custom types, respectively. For the remaining entities, an empty diff is generated. It seems that PostgreSQL is functioning properly.

2024-10-02 10:59 UTC, lsh4711 commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
I've reconsidered, and I think PostgreSQL should also have empty diffs for all entities.
However, it keeps generating alter statements by comparing anew each time.
I'll take a closer look at this.

2024-10-02 11:00 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
indeed, let me say it for the third time, there should be no queries if the schema is up to date.

2024-10-02 11:05 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
i would first check the logs from schema comparator, they should give you a good understanding why a diff is created

https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/schema/SchemaComparator.ts#L698

the logs are disabled by default, you need to enable `verbose` option to see them, or just replace this method with `console.log` in your fork to see

2024-10-02 11:21 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
i checked the test once again, and not sure what you are trying to show with the `type: 'custom'`? its weird that it resolves to integer to be honest, but its rather undefined behaviour, people should use `columnType` here if they want that as a type in their schema. i would personally expect that to resolve to string/text, since that is the default type mapping iirc

2024-10-02 11:40 UTC, B4nan commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
The default mapping is string, not number, so fallback to integer is not normal, definitely not what I would expect here. I can feel its caused by knex and its `increments` helper. Which we should really get rid of in the first place, but we don't have to deal with that in this PR, it might require quite a lot of changes in all the drivers.

2024-10-02 15:30 UTC, lsh4711 commented on tests/issues/__snapshots__/GH6095.test.ts.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
I identified the cause and understood how the code operates.
I discovered that using `autoIncrement: true` with `text` type or `custom-naming` type can lead to unintended diffs.
```
@Entity()
class Bigserial {

  @PrimaryKey({ autoincrement: true, type: 'bigserial' })
  id!: string;

}
```
If autoIncrement is explicitly set to true like in the example above, create DDL is always generated as `Integer auto_increment.`.
This leads to a diff between the table type `Integer` and the entity type `bigserial` during updates or migrations.
The issue is that the altered schema also becomes `Integer auto_increment`, causing diffs to occur continuously.

Additionally, I found that `autoIncrement: true` can be problematic even when the table already exists.
Typically, SQLite is used for testing purposes on in-memory, but if we are using a file-based mode and the existing schema uses (id bigserial not null, primary key (id)), setting `autoIncrement: true` in the entity code will cause an autoIncrement diff.
Up to this point, it might not seem problematic.
However, it always changes to `Integer auto_increment`, regardless of `bigserial`, leading to diffs continuously...

If auto increment is necessary, we must use it carefully as follows:
Use only `number` type or specify `{ type: 'int|integer|number' }`.

In issue #6095, should remove `autoIncrement: true` part.
If autoIncrement is needed, ensure that type is explicitly set to `int, integer, or number` to prevent unintended diffs by comparing correct values. :)

2024-10-02 16:34 UTC, B4nan commented on tests/features/embeddables/GH5847.test.ts
> +  readonly id!: string;
i would remove this change completely. what you did there now is wrong, integers are always mapped to numbers. only bigints support mapping to number/string/bigint, not integers.

2024-10-02 16:53 UTC, lsh4711 commented on tests/features/embeddables/GH5847.test.ts
> +  readonly id!: string;
I agree with what you said.
I will only keep the part about bigserial.
However, it is true that using autoincrement as true in the use case of the related issue causes continuous diff errors,
so I am curious about how this part should be improved in the future.

2024-10-03 07:20 UTC, B4nan commented on tests/features/embeddables/GH5847.test.ts
> +  readonly id!: string;
```suggestion
  @PrimaryKey()
  readonly id!: bigint;
```

2024-10-03 07:20 UTC, B4nan commented on tests/features/embeddables/GH5847.test.ts
>    readonly id!: bigint;
```suggestion
  @PrimaryKey()
  readonly id!: number;
```

2024-10-03 07:33 UTC, merged

2024-10-03 07:40 UTC, lsh4711 commented
I apologize.
It was a review for test 5847, but I only made changes to the recent test.
And now, both `schema first` approach and `entity first` approach seem to be working well in MySQL. :)
Thank you for your help.