fix(core): add a `prefixBehavior` option to correct prefixes on nested embeddables
mikro-orm/mikro-orm pull request #6113
Opened 2024-10-05 08:10 UTC by HugoMendes98

fixes #6112 

I'm not totally convinced by the documentation I propose ...

2024-10-05 08:36 UTC, B4nan requested changes
thanks!

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/metadata/MetadataDiscovery.ts
> +    const behavior = prefixBehavior ?? this.config.getAll().embeddable.prefixBehavior;
i also renamed the key here to `embeddables` instead of `embeddable`

```suggestion
    const behavior = prefixBehavior ?? this.config.get('embeddables').prefixBehavior;
```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/utils/Configuration.ts
> +    embeddable: {
```suggestion
    embeddables: {
```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/typings.ts
> +import type { EmbeddedPrefixBehavior } from './decorators';
```suggestion
import type { EmbeddedPrefixBehavior } from './decorators/Embedded';
```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/utils/Configuration.ts
> +import type { EmbeddedPrefixBehavior } from '../decorators';
```suggestion
import type { EmbeddedPrefixBehavior } from '../decorators/Embedded';
```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/utils/Configuration.ts
> +  embeddable: {
```suggestion
  embeddables: {
```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/utils/Configuration.ts
> +    prefixBehavior: EmbeddedPrefixBehavior;
`prefixMode` sounds better to me

2024-10-05 08:36 UTC, B4nan commented on tests/features/embeddables/GH6112.test.ts
> +import { Embeddable, Embedded, Entity, EntityClass, PrimaryKey, Property } from '@mikro-orm/core';
```suggestion
import { Embeddable, Embedded, Entity, EntityClass, PrimaryKey, Property, MikroORM, Options } from '@mikro-orm/better-sqlite';
```

2024-10-05 08:36 UTC, B4nan commented on tests/features/embeddables/GH6112.test.ts
> +    const repo = orm.em.getRepository(Person);
don't use repositories in tests, it only makes them more complex for no reason

2024-10-05 08:36 UTC, B4nan commented on tests/features/embeddables/GH6112.test.ts
> +      validateRequired: true,
none of this is relevant here

```suggestion
```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/decorators/Embedded.ts
> +/** With `absolute` the prefix is set at the root of the entity (whatever the nesting level) */
```suggestion
/** With `absolute` the prefix is set at the root of the entity (regardless of the nesting level) */
```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/decorators/Embedded.ts
> +export type EmbeddedPrefixBehavior = 'absolute' | 'relative';
```suggestion
export type EmbeddedPrefixBehavior = 'absolute' | 'relative';

```

2024-10-05 08:36 UTC, B4nan commented on packages/core/src/decorators/Embedded.ts
> +  /** Behavior of the `prefix` when explicitly set (string) */
this comment feels moot
```suggestion
```

2024-10-05 08:36 UTC, B4nan commented on docs/docs/embeddables.md
> +MikroORM.init({ embeddable: { prefixBehavior: "absolute" }})
be consistent, code style in docs should be the same as in code

```suggestion
MikroORM.init({ embeddables: { prefixBehavior: 'absolute' }})
```

2024-10-05 08:36 UTC, B4nan commented on docs/docs/embeddables.md
> +
there are many code style issues in this block, pay more attention to blank lines (one between every class/interface, but no blank line at the end of the code block

2024-10-05 08:36 UTC, B4nan commented on docs/docs/embeddables.md
> +With the example below:
```suggestion
You can also decide more precisely how the column name is determined with an explicit prefix. With the example below:
```

2024-10-05 08:37 UTC, B4nan commented
btw if you would be up for another PR, there is also #5361 which might be quite similar to what you did here. but lets first finish this one and not mix those two problems

2024-10-05 12:28 UTC, B4nan commented on docs/docs/embeddables.md
> +- A `relative` mode **concatenates** the prefix with its parent's prefix (if any), naming them `contact_addr2_city`, `contact_addr2_street`, ...
```suggestion
- `absolute` mode (default) sets the prefix at the beginning of the **column**, naming them `addr_city`, `addr_street`, ...
- `relative` mode **concatenates** the prefix with its parent's prefix (if any), naming them `contact_addr2_city`, `contact_addr2_street`, ...

:::warning

The default value of `prefixMode` will change in v7 to `relative`.

:::
```

2024-10-05 12:31 UTC, B4nan requested changes
next time please allow others to change your PR, i cant commit the suggestion myself

2024-10-05 14:47 UTC, HugoMendes98 commented
> next time please allow others to change your PR, I cant commit the suggestion myself

Oh sorry about that, but it seems that I can not allow it from a _fork living under an organisation_ (cf. [discussion](https://github.com/orgs/community/discussions/5634)).

I'll use a _personal fork_ for future PRs.

2024-10-06 11:50 UTC, B4nan approved these changes

2024-10-06 12:25 UTC, merged