feat(entity-generator,knex): filter tables before fetching table details
mikro-orm/mikro-orm pull request #6138
Opened 2024-10-14 06:45 UTC by patrykbojczuk

This moves table filtering from after retrieving all table details (i.e. columns, foreign keys, etc.) to after retrieving a list of tables as described in #5900.

Closes #5900

2024-10-14 11:09 UTC, patrykbojczuk commented
I’ve found an issue with the `OddTableNames.mysql.test.ts`.

Previously, in the `E123TableName` entity, there was a nonexistent `Table$39s$32name$32has$32apostrophe$44$32also$32$96$32this` entity used (it’s part of another database) as a `prototype` property type, but as it does not exist in the metadata, it’s typed as a `string` instead.

I’m not sure how you’d want to address this.

2024-10-14 12:04 UTC, patrykbojczuk commented
> Same way as if the name was a completely typical name that doesn't need any escapes...

@boenrobot It could be different name (it just happened to be odd in this case), but it still wouldn't get any tables from other schemas (which in mysql are equivalent to databases), and therefore it won't add schema name to the entity options.

This was the case before too - the test snapshot does not contain the entity model of the aforementioned table.

2024-10-14 12:32 UTC, patrykbojczuk commented
@boenrobot Yes, I think it will be better if addressed in the future PR, perhaps by someone with more experience in mysql/mariadb realm.

2024-10-15 09:32 UTC, B4nan commented on tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
> +  test!: number;
this doesn't feel correct, neither the other change in this file

2024-10-15 09:41 UTC, patrykbojczuk commented on tests/features/entity-generator/__snapshots__/EntityGenerator.postgres.test.ts.snap
> +  test!: number;
I've assumed, that this snapshot was previously incorrect, as skipped or not taken tables' entity models were used.

2024-10-22 10:48 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
> -  author?: Author;
The test you're referring to - `multiple connected schemas in postgres generate entities for given schema only` - is specifically checking if entities from other schemas are filtered out.

I couldn't reproduce the issue with `Author` entity not existing even if not filtering by schema.
When generating the entities without the `schema` property specified, entity models for all tables are correctly generated.

2024-10-22 11:11 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
> -  author?: Author;
I've added a test to check entity model generation for all schemas (without `schema` option specified) to both mssql and postgres `multiple-schemas` test suites.

2024-10-22 11:17 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
> -  author?: Author;
And now I see that problem.

2024-10-22 11:45 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
>  @Entity({ schema: 'n2' })
@boenrobot Do you have any idea why would an entity model for `n2.book` be generated twice, once without the `N2` class prefix and `tableName` in the `EntityOptions` and the second time, under the `Author` entity model, with the class prefix and `tableName` option set?

2024-10-22 11:51 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
>  @Entity({ schema: 'n2' })
When debugging the issue, I've got correct result when other tests are skipped, but the output keeps changing - it's not sorted.

2024-10-22 12:10 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
>  @Entity({ schema: 'n2' })
Ok, the sorting issue should now be fixed.

2024-10-22 12:52 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
>  @Entity({ schema: 'n2' })
The problem with doubled entity models for a single table still does occur.

2024-10-22 13:08 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
>  @Entity({ schema: 'n2' })
So in short the entities generated in the first test to run appear in the second test to run.

2024-10-22 13:18 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
>  @Entity({ schema: 'n2' })
Which is because the `EntityGenerator` instance is reused between the tests and therefore all of the `EntityGenerator`'s fields are shared between test runs.

2024-10-22 13:29 UTC, patrykbojczuk commented on tests/features/multiple-schemas/__snapshots__/multiple-schemas.postgres.test.ts.snap
>  @Entity({ schema: 'n2' })
Now each test should have its own ORM instance.

2024-10-25 06:31 UTC, patrykbojczuk commented
> you've [indirectly](https://app.codecov.io/gh/mikro-orm/mikro-orm/pull/6138/indirect-changes) caused loss of coverage in [MsSqlQueryBuilder's getKnexQuery() when using it for truncate type queries](https://app.codecov.io/gh/mikro-orm/mikro-orm/pull/6138/blob/packages/mssql/src/MsSqlQueryBuilder.ts#L26) (like... how?)

It's probably because truncate is not tested anywhere, whereas earlier, for each test the table was truncated, which probably counted as a coverage 🤔

As for the `getTableName`, it is used in the truncate, so that was probably covered with truncate.

2024-10-25 11:02 UTC, B4nan requested changes

2024-10-25 11:02 UTC, B4nan commented on tests/features/truncate/truncate.mssql.test.ts
> +      .getKnex()
please dont use knex directly in tests, just do `em.execute()`

i already have a local branch that removes knex from the QB implementation, this would only add conflicts for no reason

2024-10-25 12:48 UTC, merged

2024-10-25 13:51 UTC, B4nan commented
Looks like there is still one line that is no longer covered by tests, not a big deal in terms of coverage, I just wonder if it's needed or what happened.

https://app.codecov.io/gh/mikro-orm/mikro-orm/commit/74bf43fa34cc129e4561f6ad5596af9ecbba32a9/blob/packages/core/src/drivers/DatabaseDriver.ts#L486

2024-10-25 14:46 UTC, B4nan commented
That method was quite overcomplicated, we don't need 4 return statements and nested conditions at all, refactored here to get around this without more tests.

04321e06ce083ec129432cc3436846737382b006