feat(core): add `@Transactional()` decorator
mikro-orm/mikro-orm pull request #6143
Opened 2024-10-15 08:46 UTC by lsh4711

This is implementation of `@Transactional()` decorator, which internally uses `em.transactional()`.
It works on async functions and can be used alongside `em.transactional()`.

2024-10-15 08:56 UTC, B4nan commented on packages/core/src/utils/DatasourceUtils.ts
> +export class DatasourceUtils {
What is this for and why you think you need it? Because I don't believe you do. 

It looks like this is destined to leak memory. Also lets not bring typeorm terms in here, we don't call anything in the whole codebase a datasource.

2024-10-15 09:06 UTC, B4nan reviewed
I'd like to see a different approach, this feels way too hacked. Try to think of this as an alternative to `@CreateRequestContext` decorator which also opens a transaction (and flushes at the end because of that).

2024-10-15 09:06 UTC, B4nan commented on packages/core/src/utils/DatasourceUtils.ts
> +   * To start first transaction using @Transactional(), need to set datasource.
It should behave just like the existing `@CreateRequestContext` decorator. The user needs to inject something into the context, either the ORM instance or EM or some repository (or pass it in the decorator parameters), and we will use that. You can use `em.transactional` on a global EM too.

2024-10-15 09:06 UTC, B4nan commented on packages/core/src/decorators/Transactional.ts
> + * To use forked EntityManager, use TransactionContext.getEntityManager().
`TransactionContext.getEntityManager()` is internal method, users should be using whatever they inject, e.g. `this.em`, not those.

2024-10-15 09:19 UTC, lsh4711 commented on packages/core/src/utils/DatasourceUtils.ts
> +export class DatasourceUtils {
When attempting to start a transaction with the `@Transactional()` decorator, if there is no valid EntityManager (in RequestContext or TransactionContext), a reference to the EntityManager was needed.
To address this, I created a class to store references to the ORM. Additionally, in scenarios where multiple ORMs are used and a reference is needed, it stores the reference and name of the ORM, allowing the user to specify which ORM to create a transaction with using `@Transactional({ name: 'ormName' })`.

Although I wrote the code with this thought process, after hearing your advice, I realized how to improve it. :)

2024-10-16 05:22 UTC, lsh4711 commented on packages/core/src/decorators/Transactional.ts
> +      return em.transactional(() => originalMethod.apply(this, args), options);
I thought it would be good to function the same as `em.transactional()`,
but should I improve it by using `em.begin()`, `flush()`, and `commit()` instead?

2024-10-16 10:31 UTC, B4nan commented on packages/core/src/decorators/Transactional.ts
> +      return em.transactional(() => originalMethod.apply(this, args), options);
Nope, that would also mean creating your own async context (to be able to use services from DI container), which `em.transactional` does for you, I don't see a reason to reimplement what the method is doing already.

2024-10-16 10:36 UTC, B4nan reviewed
i will have a closer look later, but it looks quite good now. we are missing docs (as well as jsdoc)

2024-10-16 10:36 UTC, B4nan commented on packages/core/src/decorators/Transactional.ts
> +function getEntityManager(caller: { orm?: MikroORM; em?: EntityManager }, context: unknown) {
lets move this to some shared file and use the same in the other context decorators

2024-10-16 10:36 UTC, B4nan commented on packages/core/src/decorators/Transactional.ts
> +export function Transactional<T extends object>(getContext?: GetContext<T> | TransactionOptions, options?: TransactionOptions): MethodDecorator {
i would like to see a single signature, instead of mixing what the first parameter is doing, create extension of the `TransactionOptions` which also lets you pass the context getter as one of the options

2024-10-18 17:10 UTC, B4nan requested changes
few nits

2024-10-18 17:10 UTC, B4nan commented on packages/core/src/typings.ts
> +export type SyncOrAsync<T> = T | Promise<T>;
we already have `MaybePromise` type

2024-10-18 17:10 UTC, B4nan commented on packages/core/src/decorators/Transactional.ts
> +import { RequestContext, resolveGetContext, TransactionContext, type TransactionOptions } from '../';
don't import from barrel files

2024-10-18 17:10 UTC, B4nan commented on packages/core/src/decorators/CreateRequestContext.ts
> +import { resolveGetContext } from '../';
don't import from barrel files

2024-10-20 08:50 UTC, B4nan requested changes
lets document this

https://mikro-orm.io/docs/transactions#approach-2-explicitly
https://mikro-orm.io/docs/identity-map#ensurerequestcontext-decorator

2024-10-20 09:24 UTC, B4nan requested changes
few more notes

2024-10-20 09:24 UTC, B4nan commented on packages/core/src/decorators/Transactional.ts
> + * you can specify context to open transaction by providing `getContext` property.
lets make this more informative, starting a comment with "you can" feels weird. describe what the decorator is about, not just one of its options.

```suggestion
 * you can specify context to open transaction by providing `getContext` option.
```

2024-10-20 09:24 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +  return getEntityManager({ orm: await caller.orm, em: caller.em }, context);
the EM can be also async callback
```suggestion
  return getEntityManager({ orm: await caller.orm, em: await caller.em }, context);
```

2024-10-20 09:24 UTC, B4nan commented on packages/core/src/utils/Utils.ts
> +import { EntityManager, EntityRepository, MikroORM } from '@mikro-orm/core';
you cant import from `core` package like this from inside the `core` package, this needs to be relative import. and it feels like an import cycle, the Utils class is imported from the EM, lets move all those changes to a separate file.

2024-10-21 13:31 UTC, B4nan reviewed
we are almost there, good job!

2024-10-21 13:31 UTC, B4nan commented on packages/core/src/utils/resolveGetContext.ts
> + import { EntityRepository } from '../entity/EntityRepository';
```suggestion
import { EntityRepository } from '../entity/EntityRepository';
```

2024-10-21 13:31 UTC, B4nan commented on packages/core/src/typings.ts
> + * and callback parameter is injected with `this`.
either improve this comment or mark it as `@internal`, otherwise, it will end up in docs and there we need something better than a comment starting with "you can also...".

not to mention there are some typos (`callbck`) and missing code blocks

2024-10-21 13:31 UTC, B4nan commented on packages/core/src/decorators/Transactional.ts
> +type TransactionalOptions<T> = TransactionOptions & { getContext?: GetContext<T> };
I would maybe call this just `context` instead of `getContext`. `getContext` sounds like a getter name, not a parameter name. We already have `context` option in the ORM and this feels like a very similar use case.

2024-10-21 13:31 UTC, B4nan commented on docs/docs/identity-map.md
> +If you want to ensure that the method runs within a transaction scope, use `@Transactional()` decorator. The operations inside the function are performed within a new transaction context, and upon fu
we should also mention the context option and that it works the same as the one for `@CreateRequestContext` decorator

2024-10-22 14:59 UTC, B4nan requested changes

2024-10-22 14:59 UTC, B4nan commented on docs/docs/identity-map.md
> +You can provide the same callback that can be used in `@CreateRequestContext()` decorator as `context` option, which means you can specify the context in which the transaction begins. The function ar
```suggestion
You can provide the same callback that can be used in the `@CreateRequestContext()` decorator via the `context` option, allowing you to handle the injection of the EntityManager in non-standard scenarios. The function is executed within a new transaction context, and upon completion, flush and commit are automatically executed. This decorator can also be used in a nested manner.
```

2024-10-22 14:59 UTC, B4nan commented on docs/docs/identity-map.md
> +For more details about transactions, check the document on [Transactions](./transactions).
```suggestion
For more details about transactions, check the [Transactions section](./transactions).
```

2024-10-22 14:59 UTC, B4nan commented on docs/docs/transactions.md
> +Another way to handle explicit transactions is by using `@Transactional()` decorator.
```suggestion
Another way to handle explicit transactions is by using the`@Transactional()` decorator.
```

2024-10-22 14:59 UTC, B4nan commented on docs/docs/transactions.md
> +`em.transactional(cb)` and `@Transactional()` will flush the inner `EntityManager` prior to transaction commit.
```suggestion
`em.transactional(cb)` and the `@Transactional()` will flush the inner `EntityManager` before transaction commit.
```

2024-10-22 14:59 UTC, B4nan commented on packages/core/src/typings.ts
> +export type Context<T> = MaybePromise<MikroORM> | ((type: T) => MaybePromise<MikroORM | EntityManager | EntityRepository<any> | { getEntityManager(): EntityManager }>);
I wouldn't call this "Context", since it does not really represent one, I said I would rename the option, not the type. I can't say I like the previous name either, but this one feels way too generic, we might want to use "Context" for something else in the long run.

A context is what the `@CreateRequestContext` provides, not its input. Maybe we could call this "context provider", I guess that sounds better.

2024-10-23 09:04 UTC, B4nan requested changes
one last bit before we merge. the test is currently quite slow, because you use the `init...` methods from the bootstrap file. especially with MySQL, this is terribly slow, since it creates 2 replicas, so it issues the create schema queries 3 times, not to mention those methods register quite a lot of entities, but you need just one in here.

i am also not sure if we really need to test this with different drivers, since you haven't touched anything driver specific, i would simplify the test to use sqlite in memory database only to make it fast.

2024-10-23 16:36 UTC, B4nan approved these changes
thanks!

2024-10-23 16:36 UTC, merged