WIP: feat: seeder
mikro-orm/mikro-orm pull request #929
Opened 2020-10-19 14:32 UTC by Langstra

Currently this is still a WIP, but I am opening the PR already to gather some feedback. Nothing from this code has been tested yet and I am not even sure it will transpile or pass eslint and/or prettier.

Closes #251

2020-10-19 15:47 UTC, B4nan requested changes
Nice, thanks! left some comments here, but in general without tests or docs its hard to suggest what to change how, so please add some tests or at least adjust the description with some example usage. I don't really like the global storage, I'd expect this to work similarly to migrations or entity generator - you as a user need to initialize the ORM and get the seed manager from that - that is where the context should be, no need to have anything globally.

2020-10-19 15:47 UTC, B4nan commented on package.json
> +    "test": "jest Logger --runInBand",
this should not be here

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/package.json
> +    "typescript-mix": "^3.1.3"
looks like its not used anywhere, is it needed?

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/factory.ts
> +      Object.assign(o, Object.assign({}, this.definition(), overrideParameters));
using Object.assign is usually wrong, if `o` is an entity,  you should use `em.assign` that will handle collections and references

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/factory.ts
> +      wrap(o).assign(Object.assign({}, this.definition(), overrideParameters),
use `em.assign()` instead of `wrap().assign()` (the same but more readable)

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/factory.ts
> +    const objects = [...Array(this.amount)].map(() => {
using `Array` without `new` looks quite weird to me :]

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/has-factory.decorator.ts
> +    if (!(global as any).imported) {
why is `global` needed here? why cant we use static variables?

if it really needs to be stored on `global`, use `Utils.getGlobalStorage()` at least, but it looks wrong in general to need global state here. and we should have some object instance there, instead of writing to the global object directly. 

but without tests or documentation i am not sure how things are supposed to be used, so that is definitely needed for better review

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/refresh-database.decorator.ts
> +export const refreshDatabase = async (orm: MikroORM): Promise<void> => {
those do not really look like decorators :]

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/refresh-database.decorator.ts
> +  orm.config.getLogger().log('info', 'Dropped schema');
afaik schema generator already logs success messages so this looks redundant

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/refresh-database.decorator.ts
> +  (global as any).orm = orm;
this sounds wrong, as i mentioned above, i'd prefer not to have global state

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/seeder.ts
> +    return Promise.all(seeders.map(s => s.run()));
i would say this should be executed serially (in general that is how i would expect things to work as a user). if we wanted to execute it in parallel, each "thread" would need its own context (fork) probably.

2020-10-19 15:47 UTC, B4nan commented on packages/seeder/src/utils/file.util.ts
> +    .map(pattern => glob.sync(path.resolve(process.cwd(), pattern)))
let's not use sync methods

2020-10-30 11:55 UTC, AsyncLegs commented on packages/seeder/src/factory.ts
> +    const objects = [...Array(this.amount)].map(() => {
or maybe Array.from

2020-11-04 08:36 UTC, B4nan commented
Do you plan to finalize this?

2020-11-04 17:39 UTC, merceyz requested changes
Have some comments on dependencies, staying out of the implementation part

2020-11-04 17:39 UTC, merceyz commented on packages/seeder/package.json
> +    "@mikro-orm/core": "^4.0.7",
Should be a peer dependency and for lerna to work it needs to be a devDependency as well

2020-11-04 17:39 UTC, merceyz commented on packages/seeder/package.json
> +    "yargs": "^15.4.1"
Seems to be unused

2020-11-04 17:39 UTC, merceyz commented on packages/seeder/src/utils/file.util.ts
> +import * as glob from 'glob';
This is an undeclared dependency, but since the core uses `globby` should probably use that here as well

2021-02-09 14:56 UTC, B4nan commented
Do you plan to continue working on this? I could pick it up myself, but I really need some docs (for the public api) and tests (or example usage) for what is done already.

2021-02-11 07:10 UTC, rubiin commented
i think it would be better https://github.com/CyriacBr/mikro-resources/tree/develop/packages/fixtures as its documeneted

2021-02-11 09:24 UTC, B4nan commented
@CyriacBr could you present a bit what's there and how it fits the #251? 

I don't really want to add more decorators and drive it that way, the idea was to have something similar to laravel. Maybe your `FixturesFactory` is exactly that?

(sorry for dumb questions, never used any kind of seeder myself, same with laravel, so this issue is rather abstract to me)

2021-02-11 11:41 UTC, CyriacBr commented
> @CyriacBr could you present a bit what's there and how it fits the #251?
> 
> I don't really want to add more decorators and drive it that way, the idea was to have something similar to laravel. Maybe your `FixturesFactory` is exactly that?
> 
> (sorry for dumb questions, never used any kind of seeder myself, same with laravel, so this issue is rather abstract to me)

Hello. I haven't used Laravel myself so I don't know how its Seeder behaves, but basically my package allows you to generate random entities on the fly using `FixturesFactory`. Thanks to MikroORM metadatas, decorators are only there for customization. (e.g if you do not want random values). I opted for decorators because it fits well within Typescript and MikroORM entities and everything is centralized.

It was written more for testing but can be used as a CLI by creating a `.ts` file and use the API there.
```ts
const orm = await MikroORM.init(ormConfig);
const factory = new FixturesFactory(ormInstance);
// Generate a fixture
const author = await factory.make(Author).oneAndPersist();
// Generate multiple fixtures
const authors = await factory.make(Author).manyAndPersist(10);
```

But note that I haven't used MikroORM in a while so I do not know if the package is up to date with the latest release.

2021-02-12 20:32 UTC, Langstra commented
Yeah I am sorry for not working on this anymore.work took up a lot of time lately. I'll try and make some documentation and code for this in the coming weekends. I'll keep you posted.

2021-02-13 14:37 UTC, rubiin commented
> Yeah I am sorry for not working on this anymore.work took up a lot of time lately. I'll try and make some documentation and code for this in the coming weekends. I'll keep you posted.
A documentation upto now would be great so that me or anyone else can pickup things where you left off

2021-02-15 22:13 UTC, Langstra commented
I am still working on it and it is far from done, but I pushed my progress so you get a bit more feeling for and know I am working on it ;)

2021-02-23 10:44 UTC, Langstra commented
I think right now would be a good moment for some feedback. In my opinion it is mostly done.

2021-02-23 21:48 UTC, Langstra commented on packages/seeder/src/factory.ts
> +    const objects = [...Array(this.amount)].map(() => {
https://tc39.es/ecma262/#sec-array-constructor
>also creates and initializes a new Array object when called as a function rather than as a constructor. Thus the function call Array(…) is equivalent to the object creation expression new Array(…) with the same arguments.

2021-02-25 10:34 UTC, B4nan commented
Thanks a lot, gave it a quick scan and it looks good! Will review the code in detail soon, and ideally we can get this out in v4.5

2021-02-26 11:24 UTC, B4nan requested changes
looking good, but i'd like to change the api to be sync as much as possible (while allowing to have async callbacks probably) to truly leverage the UoW

also the `eval` should go, i dont understand why it should be needed - seeders should be exported and we should require them as we do with entities or the orm config. dont worry about the eslint rule (add ignore comment for it) - this is the right place to do it.

2021-02-26 11:24 UTC, B4nan commented on docs/docs/seeding.md
> +mikro-orm database:seed
i'd remove the `database:` prefix, also in the previous text you call it `db:` instead

also add `npx` in front of all calls to be consistent

2021-02-26 11:24 UTC, B4nan commented on docs/docs/seeding.md
> +    seeder.closeConnection();
should be awaited

2021-02-26 11:24 UTC, B4nan commented on packages/seeder/src/mikro-orm-seeder.ts
> +export class MikroOrmSeeder {
`SeedManager` or something down that path sounds better, right? i'd rather not use `MikroORM` in class names

2021-02-26 11:24 UTC, B4nan commented on packages/seeder/src/seeder.ts
> +  public abstract run(em: EntityManager): Promise<void>;
remove `public` modifier (will need to review why this is not caught by eslint)

2021-02-26 11:24 UTC, B4nan commented on packages/seeder/tsconfig.json
> +}
not sure what the `run-seeders` file is, probably should not be there?

(cant comment on it as it has no content)

2021-02-26 11:24 UTC, B4nan commented on tests/cli/CLIHelper.test.ts
> +      'database:seed',
to add a bit more reasoning why i dont like the prefix - the command will work with entities, while `import` command (the only one with that prefix) works with raw SQL dumps only.

2021-02-26 11:24 UTC, B4nan commented on tests/cli/DatabaseSeedCommand.test.ts
> +    seeder = await MikroOrmSeeder.init(await initORMSqlite());
i'd go the same way as with schema generator and migrator - having a getter on the `MikroORM` instance, so we would do `orm.getSeeder()` or `orm.getSeedManager()` or something like that.

2021-02-26 11:24 UTC, B4nan commented on packages/seeder/src/mikro-orm-seeder.ts
> +    return seeder;
do we really need to be that flexible here? i'd rather always require the orm intance, as as noted elsewhere, we should have a getter on the orm object

also that way there is no need to have this method async

2021-02-26 11:24 UTC, B4nan commented on packages/seeder/src/mikro-orm-seeder.ts
> +      await this.seed(eval(seederClass));
ouch, `eval`? why dont you just require the class (and as said, export the seeder from it). i would even drop the dynamic import, especially if it is causing headaches when mocking

just like with entities during folder based discovery

2021-02-26 11:24 UTC, B4nan commented on packages/seeder/src/mikro-orm-seeder.ts
> +    await generator.createSchema();
do we need the create call?

2021-02-26 11:28 UTC, B4nan commented
anyway thanks a lot for this, especially for the docs. if you would struggle with the requests, testing or with time in general, this is already in a shape where i will be happy to take over myself. if so, i'd suggest to merge this to `dev` branch instead of master, so i can work with it directly.

2021-02-26 22:52 UTC, totomakers commented
Sorry if im wrong.
Seeder would be very nice \o/
I have made a proposal for Factory API here: https://github.com/totomakers/mikro-orm/tree/seeder-propose
Quite bit simpler with less type casting.

2021-02-27 19:25 UTC, Langstra commented
Thanks for the comments, I'll work on it and let you know when I have finished ;)

2021-02-27 19:36 UTC, Langstra commented on docs/docs/seeding.md
> +The `make` method returns the type `Author | Author[]`, so be sure to cast it to the correct type.
My suggestion would be this
```ts
public async make(overrideParameters?: Partial<C>, count?: number): Promise<C[]>
  public async make(overrideParameters?: Partial<C>, count?: 1): Promise<C>
  public async make(overrideParameters?: Partial<C>, count?: 1 | number) {
```
Based on the count parameter you know the return type. This seems better than having multiple methods.

2021-02-27 23:14 UTC, Langstra commented on docs/docs/seeding.md
> +The `make` method returns the type `Author | Author[]`, so be sure to cast it to the correct type.
Oh well, in my opinion an even better way is to change the class generic signature after calling the `count()` method.
```ts
public make(this: Factory<C>, overrideParameters?: Partial<C>): C
public make(this: Factory<C[]>, overrideParameters?: Partial<C>): C[]
public make(overrideParameters?: Partial<C>) {

public count(this: Factory<C>, amount: number): Factory<C[]> {
```
Before calling `count()`,  `make()` will return a non-array entity e.g. `Project`. After calling `count()`, `make()` will return an array of entities e.g. `Project[]`

2021-02-27 23:18 UTC, Langstra commented on docs/docs/seeding.md
> +}) as Book;
Agreed on this, definitely cleans up the code and makes it more readable. Will change.

2021-02-27 23:20 UTC, Langstra commented on packages/seeder/tsconfig.json
> +}
No idea, something must have gone wrong here ;)

2021-02-27 23:22 UTC, Langstra commented on packages/seeder/src/mikro-orm-seeder.ts
> +    await generator.createSchema();
Shouldn't we need to recreate the schema after dropping it? Otherwise we cannot seed it again, right? The idea of the `refreshDatabase` method is that you get a clean/fresh database without data, but with the schema.

2021-02-27 23:26 UTC, Langstra commented on docs/docs/seeding.md
> +    em.clear();
I think it is up to the user if they want to `flush` and `clear`. Most of the time after using a seeder you'd like to clear the em to prevent having a large memory foot print. If you seed a lot of entities and after that start running some tests you'd be using a lot of memory where it is probably not necessary.

Yes should be exported.

2021-02-27 23:35 UTC, Langstra commented
> also the `eval` should go, i dont understand why it should be needed - seeders should be exported and we should require them as we do with entities or the orm config. dont worry about the eslint rule (add ignore comment for it) - this is the right place to do it.

The cli has a command to seed the database and you can the seederclass as argument.
`npx mikro-orm seed --class=ProjectsSeeder`
In this case ProjectsSeeder is a string. This class must then be imported and instantiated. Agree that eval() is evil(), but I could not find a suitable solution.

2021-02-28 13:07 UTC, Langstra commented on tests/cli/CLIHelper.test.ts
> +      'database:seed',
Personally I think the prefix is correct. The entities define the schema of the database. The instances of entities define the data which is saved in the database. This kind of package would also be called a database seeder. Also when looking at other frameworks this kind of functionality is called database seeding. So to keep it straight forward en recognizable I think this is the right command. However I'd like to hear your opinion and suggestion for the command you'd like to see.

2021-02-28 13:13 UTC, Langstra commented on packages/seeder/src/mikro-orm-seeder.ts
> +export class MikroOrmSeeder {
What about `DatabaseSeeder`?

2021-02-28 14:03 UTC, B4nan requested changes

2021-02-28 14:03 UTC, B4nan commented on tests/seeder/factory.test.ts
> +import * as Faker from 'faker';
we have `@types/faker` installed, is this really needed (using `* as Faker`)? and the `typeof Faker`?

2021-02-28 15:17 UTC, Langstra commented on docs/docs/seeding.md
> +The `make` method returns the type `Author | Author[]`, so be sure to cast it to the correct type.
It does decrease the complexity of the abstract factory class implementation, but I think it also increases the ease with which it can be implemented by a developer wanting to create a factory. Personally I do not like the `makeOne` and `makeMany` methods, if really necessary I'd go with `make` and `makeMany` or `makeOne` and `make`, but I'd prefer only to have the `make`.

2021-02-28 15:23 UTC, B4nan commented on docs/docs/seeding.md
> +The `make` method returns the type `Author | Author[]`, so be sure to cast it to the correct type.
lets agree to disagree. this has already bitten me more than once, i would go for `make` and `makeOne`, just like we have `em.find` and `em.findOne`.

2021-02-28 16:19 UTC, Langstra commented on docs/docs/seeding.md
> +    em.clear();
Been giving this some thought, but I am not sure how we could `flush` and `clear` on the level above. This is something a user should do when implementing the seeder, right? The factory does this automatically when called in a seeder (at least if they call `create` and not `make`).

2021-02-28 16:29 UTC, B4nan commented on docs/docs/seeding.md
> +    em.clear();
Nope, this is something to be called in the seeder manager (or however you call it), where the `run` method is called - that is the one level above I am referring to. As mentioned, this should happen only in the top level seeder, so not in those invoked via `call` method.

2021-02-28 23:05 UTC, Langstra commented on docs/docs/seeding.md
> +The `make` method returns the type `Author | Author[]`, so be sure to cast it to the correct type.
Aight, guess I'll have to settle ;)

2021-02-28 23:06 UTC, Langstra commented on tests/cli/CLIHelper.test.ts
> +      'database:seed',
I think we could have some great discussions :sunglasses:

2021-02-28 23:34 UTC, Langstra commented on tests/seeder/factory.test.ts
> +import * as Faker from 'faker';
Yes I do believe so, there is no exported member `Faker`

2021-03-02 07:48 UTC, B4nan commented on tests/seeder/factory.test.ts
> +import * as Faker from 'faker';
this project uses `esModuleInterop` so it should be always possible to do just `import Faker from 'faker';`

2021-03-03 08:11 UTC, B4nan commented
So what is it? draft? wip? or ready for review? :] I see you cracked the coverage 👍 

One thing I can say right ahead - I don't like the `seedString` method, why should we have something like that? Also from the implementation you require default export, not cool as well. Looks like its not documented (so probably internal), and I kinda understand why its there (but the name is pretty bad 😉), will give it a bit more thinking...

Another quick note, it looks like you have the `DatabaseSeeder` name for the default seeder hardcoded in some places (`handleFreshCommand`, `handleSchemaCommand`), this should be probably configurable.

2021-03-03 09:15 UTC, Langstra commented
Yeah, yesterday I thought I finished it, but then this morning I was like "oh shit this and this needs to be done".
So yeah, things I still need to work on:
- [ ] Add documentation for the other CLI commands
- [ ] Add configurable seeder class for `--seed` option for migration and schema fresh commands
- [ ] Add configurable default seed class for fresh commands
- [ ] Add documentation on the config option for the path for seed files
- [ ] Refactor seed commands to `seed:action`
- [ ] Add `seed:create` command for creating a seeder class

We need the `seedString` method for commands like `npx database:seed --class=BookSeeder`, because in the command `BookSeeder` is a string. So we load the seeder class file using `require` and then execute the seeder.

2021-03-03 09:19 UTC, RDeluxe commented
Any chance you took a look at @totomakers proposal ?

2021-03-03 09:30 UTC, Langstra commented
> Any chance you took a look at @totomakers proposal ?

Yeah, I used some ideas from it, but I do not like loading all SeederClasses and running them I'd like to give the user the option to run whatever seeder he/she wants.

2021-03-03 09:48 UTC, B4nan commented
Yeah we want this "main seeder" that orchestrates child ones, having an array of classes is not that powerful - we need to control the flow.

2021-03-03 17:09 UTC, totomakers commented
@Langstra i make some improvement in my company project. I can't share the whole project but i can let you take a peek.

2021-03-05 16:30 UTC, Langstra commented
> One thing I can say right ahead - I don't like the `seedString` method, why should we have something like that? Also from the implementation you require default export, not cool as well. Looks like its not documented (so probably internal), and I kinda understand why its there (but the name is pretty bad ), will give it a bit more thinking...

Any suggestions for this? I believe this would be the last part of the feature to fix. Otherwise I am quite confident that the feature is ready.

2021-03-05 16:36 UTC, B4nan commented
Don't worry too much about that, I am fine having it there, we should just pick a better name. 

Will try to look into this in more detail during weekend.

2021-04-16 21:16 UTC, B4nan commented
Time has come, please rebase this and let's merge it, master is now officially 5.x. I might tweak some things/naming directly there.

2021-04-18 16:21 UTC, Langstra commented
> Time has come, please rebase this and let's merge it, master is now officially 5.x. I might tweak some things/naming directly there.

Will work on it asap, won't have time for it this weekend, but I am aiming to fix it this week.

2021-05-13 15:54 UTC, B4nan commented
What about this? The rebase should be rather easy, right? :] 

Or did I miss it and we have new conflicts? If so, sorry about that, I guess (force) pushing won't trigger any notifications...

2021-05-13 21:23 UTC, Langstra commented
Yeah I already had, but now I have rebased it again. Should be fine and pass the pipeline again.

2021-05-14 07:17 UTC, merged

2021-05-14 12:09 UTC, rubiin commented
cool waiting for new version soon to use this

2021-06-04 19:08 UTC, edorgeville commented
Great job @Langstra !