docs: improve parameter documentation of filters
mikro-orm/mikro-orm pull request #952
Opened 2020-10-22 14:54 UTC by Langstra

Add documentation for all parameters and describe when global filters
are default enabled or not

2020-10-22 15:03 UTC, Langstra commented
Probably more of a bug that the Filter is not enabled by default when added through the configuration. Will try to fix that and then update this PR.

2020-10-23 08:20 UTC, B4nan requested changes

2020-10-23 08:20 UTC, B4nan commented on docs/docs/filters.md
> +There are three parameters you can use:
For me this is actually adding confusion. The paragraph is about filter parameters, and you start the sentence describing filter properties as if they are the parameters the paragraph is about. But that is not true, it's about the user params, that is the `args` in the `cond` callback. 

If this should be described somewhere, its the section above.

also the description is missing some important information

- `name` is used also for passing parameters
- `cond` can be callback, possibly async
- the default desc is weird (the word order), maybe just drop the ` to the query` at the end

and use `-` instead of `*` to be consistent

2020-10-23 08:20 UTC, B4nan commented on packages/core/src/utils/Configuration.ts
> +      this.options.filters[key].default = this.options.filters[key].default ?? true;
this branch is not tested

2020-10-23 12:04 UTC, Langstra commented on docs/docs/filters.md
> +There are three parameters you can use:
Ah alright, in that case I must have misunderstood the thing. Maybe we can rename the title `# Parameters` to `# Parameters of cond`, making it even more clear that we are talking about those?

2020-10-23 12:12 UTC, B4nan commented on docs/docs/filters.md
> +There are three parameters you can use:
idk, to me it is not that confusing, `Parameters of cond` sounds weird. maybe better name would be `Parametric filters`

2020-10-23 14:09 UTC, Langstra commented on docs/docs/filters.md
> +There are three parameters you can use:
Guess it is fine like it is then. I'll resolve all comments.

2020-10-23 14:51 UTC, B4nan commented
Looking good, thanks!

2020-10-23 14:52 UTC, merged