feat(count): initial implementation of loadCount (WIP)
mikro-orm/mikro-orm pull request #955
Opened 2020-10-23 12:32 UTC by AzariasB

Instead of populating a collection to get the number of items, fetches the count directly from the database. (`collection.loadCount()`)
An optional parameter `refresh` (false by default) can be passed to the function to force a database query instead of using the cache.

I still need to update the documentation.

Any feedback would be greatly appreciated :)

2020-10-23 13:59 UTC, B4nan commented
please remove all code style changes.

2020-10-23 14:03 UTC, AzariasB commented
Ow, didn't see all the changes made by the vscode plugin :|, will fix that

2020-10-24 07:37 UTC, B4nan requested changes
left some comments, but in general its looking good, ty!

2020-10-24 07:37 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +   * Counts the number of entries in the database
this sounds a bit misleading, it's count of items of this collection, loaded from database. 

```suggestion
   * Gets the count of collection items from database instead of counting loaded items.
   * The value is cached, use `refresh = true` to force reload it.
```

2020-10-24 07:37 UTC, B4nan commented on packages/core/src/entity/ArrayCollection.ts
> +    }
i would prefer raw `typeof` instead of the `Utils` helper (in this particular file), as it could result in circular requires easily.

but here the condition does not make sense anyway, you would be re-adding to the cached value every time its re-hydrated

```suggestion
    this._count = 0;
```

2020-10-24 07:37 UTC, B4nan commented on packages/core/src/entity/ArrayCollection.ts
> +import { Utils } from '../utils';
i would prefer raw typeof instead of the Utils helper (in this particular file), as it could result in circular requires easily.

```suggestion
```

2020-10-24 07:37 UTC, B4nan commented on tests/issues/GH949.test.ts
> +describe('GH issue 949', () => {
i would prefer to test this in existing test cases, there are many entities with collections. this issues folder is meant for bugs that are hard to reproduce with what we already have, but in general the more files we have here, the slower the tests will run.

use author.books for 1:m, book.tags for m:n owner and tag.books for inverse, i'd put it in one of the sqlite EM tests. 

also use real description, instead of just pointing to issue. again, this is mainly for bugs, where its hard to describe it.

2020-10-24 07:37 UTC, B4nan commented on tests/issues/GH949.test.ts
> +    if (!aEntity) { return; }
uh why? you just defined it, this will be always true

2020-10-24 07:37 UTC, B4nan commented on tests/issues/GH949.test.ts
> +    aEntity = (await orm.em.findOne(A, aEntity.id))!;
instead of the parens and `!`, we can use `findOneOrFail`

2020-10-24 07:37 UTC, B4nan commented on tests/issues/GH949.test.ts
> +    expect(await aEntity.bItems.loadCount()).toEqual(3);
in general the async expectations should be written this way:

```suggestion
    await expect(aEntity.bItems.loadCount()).resolves.toEqual(3);
```

2020-10-24 07:37 UTC, B4nan commented on tests/issues/GH949.test.ts
> +    // Testing array collection implemntation
typo

2020-10-24 09:13 UTC, AzariasB commented
I'm having an issue that has been fixed for #956, should I merge mikro-orm master's branch into my own ?

2020-10-24 09:15 UTC, B4nan commented
Yes, you need to rebase and resolve conflicts. Or close it and create new PR if you struggle with that, and just pick the changes you made.

2020-10-24 10:13 UTC, AzariasB commented on packages/core/src/entity/Collection.ts
> +      this._count = await em.count(this.property.type,{ [this.property.mappedBy || this.property.inversedBy]: this.owner.__helper!.getPrimaryKey() });
So, `createCondition`  was incorrect for n:m relations as it just returned a condition dictionary with empty ids: `{id : {$in : [] } }`
I'm not sure what I did is the correct way of creating the condition though ...

2020-10-24 10:22 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      this._count = await em.count(this.property.type,{ [this.property.mappedBy || this.property.inversedBy]: this.owner.__helper!.getPrimaryKey() });
`createCondition` works fine, the collection items need to be set upfront to use it. in other words, it is not the method you should be using for this use case.

take a look at `loadFromPivotTable`, that is where this happens (but it loads the items - their PKs - so its again not what you should use, but a method for inspiration).

2020-10-24 11:54 UTC, AzariasB commented on packages/core/src/entity/Collection.ts
> +      this._count = await em.count(this.property.type,{ [this.property.mappedBy || this.property.inversedBy]: this.owner.__helper!.getPrimaryKey() });
Are there existing entities with composite primary keys and many-to-many relationships so that I can test this case ?

2020-10-24 14:28 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +      this._count = await em.count(this.property.type,{ [this.property.mappedBy || this.property.inversedBy]: this.owner.__helper!.getPrimaryKey() });
https://github.com/mikro-orm/mikro-orm/blob/master/tests/composite-keys.sqlite.test.ts
https://github.com/mikro-orm/mikro-orm/blob/master/tests/composite-keys.mysql.test.ts

2020-10-24 18:06 UTC, AzariasB commented
I'm having an issue when testing the loadCount with many-to-many relationShips :
With composite keys, the count queries [looks like](https://github.com/mikro-orm/mikro-orm/pull/955/checks?check_run_id=1302792939#step:12:139) : ``select count(distinct `e0`.`first_name`, `e0`.`last_name`) as count ...`` which is not a valid SQL query (too many arguments for count). I'm not sure how to deal with this ?

2020-10-24 18:32 UTC, B4nan commented
That's a bug in knex, sqlite dialect does not support distinct count with multiple fields. I'd say ignore that for now, maybe comment that test out and point to this issue as this is blocked by knex:

https://github.com/mikro-orm/mikro-orm/issues/889

In the long run I am planning to remove the dependency on knex and build the queries myself to have absolute control, there are more and more issue popping up that are hard or impossible to work around...

2020-10-26 08:19 UTC, B4nan commented
There are few minor things I'd do differently, but let's not clutter this up :] 

Last thing worth testing is how this works with mongo, as the m:n collections are implemented differently (no pivot tables). 

Also there is still one brach not tested in `Collection.ts:270`.

2020-10-26 09:04 UTC, AzariasB commented
Yes, I still need to add more tests (mysql composite keys)
For mongo, is there an existing test file  for composite keys ?

2020-10-26 09:06 UTC, B4nan commented
There are no composite keys in mongo, don't worry about that.

2020-10-26 11:10 UTC, AzariasB commented
I'm having an issue with the count method of the entitymanager for mongod-db :
[The tests fails when using count with a filter](https://github.com/mikro-orm/mikro-orm/pull/955/checks?check_run_id=1308372632#step:12:145). Am I using the filters incorrectly ?

2020-10-26 18:30 UTC, B4nan commented
There are no joins in mongo, it is not possible to query anything from the inverse side, so yes, this is correct behaviour in mongo unfortunately. 

Also M:N collections are implemented as arrays on the owning entity, so the actual count on the entity will be always the correct one. You should make it conditional in a similar way to the `Collection.init()` (based on reference type and `Platform.usesPivotTable` method).

2020-10-27 08:42 UTC, AzariasB commented
All right, I think everything's good now :)

2020-10-27 08:51 UTC, B4nan commented on packages/core/src/entity/Collection.ts
> +        this._count = this.length;
this will not work for 1:m relations in mongo (that should be handled just like in SQL)

2020-10-27 10:29 UTC, B4nan commented
Ok, let's merge it, thanks!

2020-10-27 10:32 UTC, merged

2020-10-27 10:34 UTC, AzariasB commented
Perfect, thanks !
It was a bit toughter than I expected
Thank a lot for the help throughout this pull request :), and thank you very much for the work you put into mikro-orm !